//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPC.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkUp
    {
        public int MarkUpId { get; set; }
        public string MarkUpName { get; set; }
        public Nullable<double> MarkUpRate { get; set; }
        public Nullable<int> IsFixed { get; set; }
        public int SystemSiteId { get; set; }
        public int UserDomainKey { get; set; }
    }
}
