//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets791752E81DA279E0313843D1A682975580004CD6CDE1E5D9849776BCEE942014))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets791752E81DA279E0313843D1A682975580004CD6CDE1E5D9849776BCEE942014 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets791752E81DA279E0313843D1A682975580004CD6CDE1E5D9849776BCEE942014()
        {
            this.EdmEntityContainerName = "BaseDbContext";
            this.StoreEntityContainerName = "DomainModelsStoreContainer";
            this.HashOverMappingClosure = "e4f033d5b07871c019049897a861cb14ee2909b914cce58bd56c879d764489db";
            this.HashOverAllExtentViews = "72631f17760db10a65e3b8bc651d9e331abb340ec35c4ac4ee9a19f1ecbce2fb";
            this.ViewCount = 22;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for DomainModelsStoreContainer.Company
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(9102);
            viewString.Append("\r\n    SELECT VALUE -- Constructing Company\r\n        [DomainModels.Store.Company]");
            viewString.Append("(T1.Company_CompanyId, T1.Company_AccountNumber, T1.Company_Name, T1.Company_URL");
            viewString.Append(", T1.Company_CreditReference, T1.Company_CreditLimit, T1.Company_Terms, T1.Compa");
            viewString.Append("ny_TypeId, T1.Company_DefaultNominalCode, T1.Company_DefaultMarkUpId, T1.Company");
            viewString.Append("_AccountOpenDate, T1.Company_AccountManagerId, T1.Company_Status, T1.Company_IsC");
            viewString.Append("ustomer, T1.Company_Notes, T1.Company_NotesLastUpdatedDate, T1.Company_NotesLast");
            viewString.Append("UpdatedBy, T1.Company_AccountStatusId, T1.Company_IsDisabled, T1.Company_LockedB");
            viewString.Append("y, T1.Company_AccountBalance, T1.Company_CreationDate, T1.Company_VATRegNumber, ");
            viewString.Append("T1.Company_VATRegReference, T1.Company_FlagId, T1.Company_PhoneNo, T1.Company_Is");
            viewString.Append("General, T1.Company_SalesPerson, T1.Company_Image, T1.Company_WebAccessCode, T1.");
            viewString.Append("Company_isArchived, T1.Company_PayByPersonalCredeitCard, T1.Company_PONumberRequ");
            viewString.Append("ired, T1.Company_ShowPrices, T1.Company_CarrierWebPath, T1.Company_CarrierTracki");
            viewString.Append("ngPath, T1.Company_CorporateOrderingPolicy, T1.Company_isDisplaySiteHeader, T1.C");
            viewString.Append("ompany_isDisplayMenuBar, T1.Company_isDisplayBanners, T1.Company_isDisplayFeatur");
            viewString.Append("edProducts, T1.Company_isDisplayPromotionalProducts, T1.Company_isDisplayChooseU");
            viewString.Append("sIcons, T1.Company_isDisplaySecondaryPages, T1.Company_isDisplaySiteFooter, T1.C");
            viewString.Append("ompany_RedirectWebstoreURL, T1.Company_defaultPalleteId, T1.Company_isDisplaylBr");
            viewString.Append("okerBanners, T1.Company_isBrokerCanLaminate, T1.Company_isBrokerCanRoundCorner, ");
            viewString.Append("T1.Company_isBrokerCanDeliverSameDay, T1.Company_isBrokerCanAcceptPaymentOnline,");
            viewString.Append(" T1.Company_isBrokerOrderApprovalRequired, T1.Company_isBrokerPaymentRequired, T");
            viewString.Append("1.Company_isWhiteLabel, T1.Company_TwitterURL, T1.Company_FacebookURL, T1.Compan");
            viewString.Append("y_LinkedinURL, T1.Company_WebMasterTag, T1.Company_WebAnalyticCode, T1.Company_i");
            viewString.Append("sShowGoogleMap, T1.Company_isTextWatermark, T1.Company_WatermarkText, T1.Company");
            viewString.Append("_CoreCustomerId, T1.Company_StoreBackgroundImage, T1.Company_isDisplayBrokerSeco");
            viewString.Append("ndaryPages, T1.Company_PriceFlagId, T1.Company_isIncludeVAT, T1.Company_isAllowR");
            viewString.Append("egistrationFromWeb, T1.Company_MarketingBriefRecipient, T1.Company_isLoginFirstT");
            viewString.Append("ime, T1.Company_facebookAppId, T1.Company_facebookAppKey, T1.Company_twitterAppI");
            viewString.Append("d, T1.Company_twitterAppKey, T1.Company_isStoreModePrivate, T1.Company_CustomCSS");
            viewString.Append(", T1.Company_TaxPercentageId, T1.Company_XeroAccessCode, T1.Company_canUserPlace");
            viewString.Append("OrderWithoutApproval, T1.Company_CanUserEditProfile, T1.Company_OrganisationId, ");
            viewString.Append("T1.Company_includeEmailBrokerArtworkOrderReport, T1.Company_includeEmailBrokerAr");
            viewString.Append("tworkOrderXML, T1.Company_includeEmailBrokerArtworkOrderJobCard, T1.Company_make");
            viewString.Append("EmailBrokerArtworkOrderProductionReady, T1.Company_SalesAndOrderManagerId1, T1.C");
            viewString.Append("ompany_SalesAndOrderManagerId2, T1.Company_ProductionManagerId1, T1.Company_Prod");
            viewString.Append("uctionManagerId2, T1.Company_StockNotificationManagerId1, T1.Company_StockNotifi");
            viewString.Append("cationManagerId2, T1.Company_IsDeliveryTaxAble, T1.Company_IsDisplayDeliveryOnCh");
            viewString.Append("eckout, T1.Company_DeliveryPickUpAddressId)\r\n    FROM (\r\n        SELECT \r\n      ");
            viewString.Append("      T.CompanyId AS Company_CompanyId, \r\n            T.AccountNumber AS Company");
            viewString.Append("_AccountNumber, \r\n            T.Name AS Company_Name, \r\n            T.URL AS Com");
            viewString.Append("pany_URL, \r\n            T.CreditReference AS Company_CreditReference, \r\n        ");
            viewString.Append("    T.CreditLimit AS Company_CreditLimit, \r\n            T.Terms AS Company_Terms");
            viewString.Append(", \r\n            T.TypeId AS Company_TypeId, \r\n            T.DefaultNominalCode A");
            viewString.Append("S Company_DefaultNominalCode, \r\n            T.DefaultMarkUpId AS Company_Default");
            viewString.Append("MarkUpId, \r\n            T.AccountOpenDate AS Company_AccountOpenDate, \r\n        ");
            viewString.Append("    T.AccountManagerId AS Company_AccountManagerId, \r\n            T.Status AS Co");
            viewString.Append("mpany_Status, \r\n            T.IsCustomer AS Company_IsCustomer, \r\n            T.");
            viewString.Append("Notes AS Company_Notes, \r\n            T.NotesLastUpdatedDate AS Company_NotesLas");
            viewString.Append("tUpdatedDate, \r\n            T.NotesLastUpdatedBy AS Company_NotesLastUpdatedBy, ");
            viewString.Append("\r\n            T.AccountStatusId AS Company_AccountStatusId, \r\n            T.IsDi");
            viewString.Append("sabled AS Company_IsDisabled, \r\n            T.LockedBy AS Company_LockedBy, \r\n  ");
            viewString.Append("          T.AccountBalance AS Company_AccountBalance, \r\n            T.CreationDa");
            viewString.Append("te AS Company_CreationDate, \r\n            T.VATRegNumber AS Company_VATRegNumber");
            viewString.Append(", \r\n            T.VATRegReference AS Company_VATRegReference, \r\n            T.Fl");
            viewString.Append("agId AS Company_FlagId, \r\n            T.PhoneNo AS Company_PhoneNo, \r\n          ");
            viewString.Append("  T.IsGeneral AS Company_IsGeneral, \r\n            T.SalesPerson AS Company_Sales");
            viewString.Append("Person, \r\n            T.Image AS Company_Image, \r\n            T.WebAccessCode AS");
            viewString.Append(" Company_WebAccessCode, \r\n            T.isArchived AS Company_isArchived, \r\n    ");
            viewString.Append("        T.PayByPersonalCredeitCard AS Company_PayByPersonalCredeitCard, \r\n      ");
            viewString.Append("      T.PONumberRequired AS Company_PONumberRequired, \r\n            T.ShowPrices");
            viewString.Append(" AS Company_ShowPrices, \r\n            T.CarrierWebPath AS Company_CarrierWebPath");
            viewString.Append(", \r\n            T.CarrierTrackingPath AS Company_CarrierTrackingPath, \r\n        ");
            viewString.Append("    T.CorporateOrderingPolicy AS Company_CorporateOrderingPolicy, \r\n            ");
            viewString.Append("T.isDisplaySiteHeader AS Company_isDisplaySiteHeader, \r\n            T.isDisplayM");
            viewString.Append("enuBar AS Company_isDisplayMenuBar, \r\n            T.isDisplayBanners AS Company_");
            viewString.Append("isDisplayBanners, \r\n            T.isDisplayFeaturedProducts AS Company_isDisplay");
            viewString.Append("FeaturedProducts, \r\n            T.isDisplayPromotionalProducts AS Company_isDisp");
            viewString.Append("layPromotionalProducts, \r\n            T.isDisplayChooseUsIcons AS Company_isDisp");
            viewString.Append("layChooseUsIcons, \r\n            T.isDisplaySecondaryPages AS Company_isDisplaySe");
            viewString.Append("condaryPages, \r\n            T.isDisplaySiteFooter AS Company_isDisplaySiteFooter");
            viewString.Append(", \r\n            T.RedirectWebstoreURL AS Company_RedirectWebstoreURL, \r\n        ");
            viewString.Append("    T.defaultPalleteId AS Company_defaultPalleteId, \r\n            T.isDisplaylBr");
            viewString.Append("okerBanners AS Company_isDisplaylBrokerBanners, \r\n            T.isBrokerCanLamin");
            viewString.Append("ate AS Company_isBrokerCanLaminate, \r\n            T.isBrokerCanRoundCorner AS Co");
            viewString.Append("mpany_isBrokerCanRoundCorner, \r\n            T.isBrokerCanDeliverSameDay AS Compa");
            viewString.Append("ny_isBrokerCanDeliverSameDay, \r\n            T.isBrokerCanAcceptPaymentOnline AS ");
            viewString.Append("Company_isBrokerCanAcceptPaymentOnline, \r\n            T.isBrokerOrderApprovalReq");
            viewString.Append("uired AS Company_isBrokerOrderApprovalRequired, \r\n            T.isBrokerPaymentR");
            viewString.Append("equired AS Company_isBrokerPaymentRequired, \r\n            T.isWhiteLabel AS Comp");
            viewString.Append("any_isWhiteLabel, \r\n            T.TwitterURL AS Company_TwitterURL, \r\n          ");
            viewString.Append("  T.FacebookURL AS Company_FacebookURL, \r\n            T.LinkedinURL AS Company_L");
            viewString.Append("inkedinURL, \r\n            T.WebMasterTag AS Company_WebMasterTag, \r\n            ");
            viewString.Append("T.WebAnalyticCode AS Company_WebAnalyticCode, \r\n            T.isShowGoogleMap AS");
            viewString.Append(" Company_isShowGoogleMap, \r\n            T.isTextWatermark AS Company_isTextWater");
            viewString.Append("mark, \r\n            T.WatermarkText AS Company_WatermarkText, \r\n            T.Co");
            viewString.Append("reCustomerId AS Company_CoreCustomerId, \r\n            T.StoreBackgroundImage AS ");
            viewString.Append("Company_StoreBackgroundImage, \r\n            T.isDisplayBrokerSecondaryPages AS C");
            viewString.Append("ompany_isDisplayBrokerSecondaryPages, \r\n            T.PriceFlagId AS Company_Pri");
            viewString.Append("ceFlagId, \r\n            T.isIncludeVAT AS Company_isIncludeVAT, \r\n            T.");
            viewString.Append("isAllowRegistrationFromWeb AS Company_isAllowRegistrationFromWeb, \r\n            ");
            viewString.Append("T.MarketingBriefRecipient AS Company_MarketingBriefRecipient, \r\n            T.is");
            viewString.Append("LoginFirstTime AS Company_isLoginFirstTime, \r\n            T.facebookAppId AS Com");
            viewString.Append("pany_facebookAppId, \r\n            T.facebookAppKey AS Company_facebookAppKey, \r\n");
            viewString.Append("            T.twitterAppId AS Company_twitterAppId, \r\n            T.twitterAppKe");
            viewString.Append("y AS Company_twitterAppKey, \r\n            T.isStoreModePrivate AS Company_isStor");
            viewString.Append("eModePrivate, \r\n            T.CustomCSS AS Company_CustomCSS, \r\n            T.Ta");
            viewString.Append("xPercentageId AS Company_TaxPercentageId, \r\n            T.XeroAccessCode AS Comp");
            viewString.Append("any_XeroAccessCode, \r\n            T.canUserPlaceOrderWithoutApproval AS Company_");
            viewString.Append("canUserPlaceOrderWithoutApproval, \r\n            T.CanUserEditProfile AS Company_");
            viewString.Append("CanUserEditProfile, \r\n            T.OrganisationId AS Company_OrganisationId, \r\n");
            viewString.Append("            T.includeEmailBrokerArtworkOrderReport AS Company_includeEmailBroker");
            viewString.Append("ArtworkOrderReport, \r\n            T.includeEmailBrokerArtworkOrderXML AS Company");
            viewString.Append("_includeEmailBrokerArtworkOrderXML, \r\n            T.includeEmailBrokerArtworkOrd");
            viewString.Append("erJobCard AS Company_includeEmailBrokerArtworkOrderJobCard, \r\n            T.make");
            viewString.Append("EmailBrokerArtworkOrderProductionReady AS Company_makeEmailBrokerArtworkOrderPro");
            viewString.Append("ductionReady, \r\n            T.SalesAndOrderManagerId1 AS Company_SalesAndOrderMa");
            viewString.Append("nagerId1, \r\n            T.SalesAndOrderManagerId2 AS Company_SalesAndOrderManage");
            viewString.Append("rId2, \r\n            T.ProductionManagerId1 AS Company_ProductionManagerId1, \r\n  ");
            viewString.Append("          T.ProductionManagerId2 AS Company_ProductionManagerId2, \r\n            ");
            viewString.Append("T.StockNotificationManagerId1 AS Company_StockNotificationManagerId1, \r\n        ");
            viewString.Append("    T.StockNotificationManagerId2 AS Company_StockNotificationManagerId2, \r\n    ");
            viewString.Append("        T.IsDeliveryTaxAble AS Company_IsDeliveryTaxAble, \r\n            T.IsDisp");
            viewString.Append("layDeliveryOnCheckout AS Company_IsDisplayDeliveryOnCheckout, \r\n            T.De");
            viewString.Append("liveryPickUpAddressId AS Company_DeliveryPickUpAddressId, \r\n            True AS ");
            viewString.Append("_from0\r\n        FROM BaseDbContext.Companies AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("DomainModelsStoreContainer.Company", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for DomainModelsStoreContainer.CompanyDomain
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DomainModelsStoreContainer.CompanyDomain", @"
    SELECT VALUE -- Constructing CompanyDomain
        [DomainModels.Store.CompanyDomain](T1.CompanyDomain_CompanyDomainId, T1.CompanyDomain_Domain, T1.CompanyDomain_CompanyId)
    FROM (
        SELECT 
            T.CompanyDomainId AS CompanyDomain_CompanyDomainId, 
            T.Domain AS CompanyDomain_Domain, 
            T.CompanyId AS CompanyDomain_CompanyId, 
            True AS _from0
        FROM BaseDbContext.CompanyDomains AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DomainModelsStoreContainer.CmsSkinPageWidget
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DomainModelsStoreContainer.CmsSkinPageWidget", @"
    SELECT VALUE -- Constructing CmsSkinPageWidget
        [DomainModels.Store.CmsSkinPageWidget](T1.CmsSkinPageWidget_PageWidgetId, T1.CmsSkinPageWidget_PageId, T1.CmsSkinPageWidget_WidgetId, T1.CmsSkinPageWidget_SkinId, T1.CmsSkinPageWidget_Sequence, T1.CmsSkinPageWidget_CompanyId, T1.CmsSkinPageWidget_OrganisationId)
    FROM (
        SELECT 
            T.PageWidgetId AS CmsSkinPageWidget_PageWidgetId, 
            T.PageId AS CmsSkinPageWidget_PageId, 
            T.WidgetId AS CmsSkinPageWidget_WidgetId, 
            T.SkinId AS CmsSkinPageWidget_SkinId, 
            T.Sequence AS CmsSkinPageWidget_Sequence, 
            T.CompanyId AS CmsSkinPageWidget_CompanyId, 
            T.OrganisationId AS CmsSkinPageWidget_OrganisationId, 
            True AS _from0
        FROM BaseDbContext.CmsSkinPageWidgets AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DomainModelsStoreContainer.CmsSkinPageWidgetParam
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DomainModelsStoreContainer.CmsSkinPageWidgetParam", @"
    SELECT VALUE -- Constructing CmsSkinPageWidgetParam
        [DomainModels.Store.CmsSkinPageWidgetParam](T1.CmsSkinPageWidgetParam_PageWidgetParamId, T1.CmsSkinPageWidgetParam_PageWidgetId, T1.CmsSkinPageWidgetParam_ParamName, T1.CmsSkinPageWidgetParam_ParamValue)
    FROM (
        SELECT 
            T.PageWidgetParamId AS CmsSkinPageWidgetParam_PageWidgetParamId, 
            T.PageWidgetId AS CmsSkinPageWidgetParam_PageWidgetId, 
            T.ParamName AS CmsSkinPageWidgetParam_ParamName, 
            T.ParamValue AS CmsSkinPageWidgetParam_ParamValue, 
            True AS _from0
        FROM BaseDbContext.CmsSkinPageWidgetParams AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DomainModelsStoreContainer.Widgets
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DomainModelsStoreContainer.Widgets", @"
    SELECT VALUE -- Constructing Widgets
        [DomainModels.Store.Widgets](T1.Widgets_WidgetId, T1.Widgets_WidgetCode, T1.Widgets_WidgetName, T1.Widgets_WidgetControlName)
    FROM (
        SELECT 
            T.WidgetId AS Widgets_WidgetId, 
            T.WidgetCode AS Widgets_WidgetCode, 
            T.WidgetName AS Widgets_WidgetName, 
            T.WidgetControlName AS Widgets_WidgetControlName, 
            True AS _from0
        FROM BaseDbContext.Widgets AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DomainModelsStoreContainer.ProductCategory
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(3698);
            viewString.Append("\r\n    SELECT VALUE -- Constructing ProductCategory\r\n        [DomainModels.Store.");
            viewString.Append("ProductCategory](T1.ProductCategory_ProductCategoryId, T1.ProductCategory_Catego");
            viewString.Append("ryName, T1.ProductCategory_ContentType, T1.ProductCategory_Description1, T1.Prod");
            viewString.Append("uctCategory_Description2, T1.ProductCategory_LockedBy, T1.ProductCategory_Compan");
            viewString.Append("yId, T1.ProductCategory_ParentCategoryId, T1.ProductCategory_DisplayOrder, T1.Pr");
            viewString.Append("oductCategory_ImagePath, T1.ProductCategory_ThumbnailPath, T1.ProductCategory_is");
            viewString.Append("Enabled, T1.ProductCategory_isMarketPlace, T1.ProductCategory_TemplateDesignerMa");
            viewString.Append("ppedCategoryName, T1.ProductCategory_isArchived, T1.ProductCategory_isPublished,");
            viewString.Append(" T1.ProductCategory_TrimmedWidth, T1.ProductCategory_TrimmedHeight, T1.ProductCa");
            viewString.Append("tegory_isColorImposition, T1.ProductCategory_isOrderImposition, T1.ProductCatego");
            viewString.Append("ry_isLinkToTemplates, T1.ProductCategory_Sides, T1.ProductCategory_ApplySizeRest");
            viewString.Append("rictions, T1.ProductCategory_ApplyFoldLines, T1.ProductCategory_WidthRestriction");
            viewString.Append(", T1.ProductCategory_HeightRestriction, T1.ProductCategory_CategoryTypeId, T1.Pr");
            viewString.Append("oductCategory_RegionId, T1.ProductCategory_ZoomFactor, T1.ProductCategory_ScaleF");
            viewString.Append("actor, T1.ProductCategory_isShelfProductCategory, T1.ProductCategory_MetaKeyword");
            viewString.Append("s, T1.ProductCategory_MetaDescription, T1.ProductCategory_MetaTitle, T1.ProductC");
            viewString.Append("ategory_OrganisationId)\r\n    FROM (\r\n        SELECT \r\n            T.ProductCateg");
            viewString.Append("oryId AS ProductCategory_ProductCategoryId, \r\n            T.CategoryName AS Prod");
            viewString.Append("uctCategory_CategoryName, \r\n            T.ContentType AS ProductCategory_Content");
            viewString.Append("Type, \r\n            T.Description1 AS ProductCategory_Description1, \r\n          ");
            viewString.Append("  T.Description2 AS ProductCategory_Description2, \r\n            T.LockedBy AS Pr");
            viewString.Append("oductCategory_LockedBy, \r\n            T.CompanyId AS ProductCategory_CompanyId, ");
            viewString.Append("\r\n            T.ParentCategoryId AS ProductCategory_ParentCategoryId, \r\n        ");
            viewString.Append("    T.DisplayOrder AS ProductCategory_DisplayOrder, \r\n            T.ImagePath AS");
            viewString.Append(" ProductCategory_ImagePath, \r\n            T.ThumbnailPath AS ProductCategory_Thu");
            viewString.Append("mbnailPath, \r\n            T.isEnabled AS ProductCategory_isEnabled, \r\n          ");
            viewString.Append("  T.isMarketPlace AS ProductCategory_isMarketPlace, \r\n            T.TemplateDesi");
            viewString.Append("gnerMappedCategoryName AS ProductCategory_TemplateDesignerMappedCategoryName, \r\n");
            viewString.Append("            T.isArchived AS ProductCategory_isArchived, \r\n            T.isPublis");
            viewString.Append("hed AS ProductCategory_isPublished, \r\n            T.TrimmedWidth AS ProductCateg");
            viewString.Append("ory_TrimmedWidth, \r\n            T.TrimmedHeight AS ProductCategory_TrimmedHeight");
            viewString.Append(", \r\n            T.isColorImposition AS ProductCategory_isColorImposition, \r\n    ");
            viewString.Append("        T.isOrderImposition AS ProductCategory_isOrderImposition, \r\n            ");
            viewString.Append("T.isLinkToTemplates AS ProductCategory_isLinkToTemplates, \r\n            T.Sides ");
            viewString.Append("AS ProductCategory_Sides, \r\n            T.ApplySizeRestrictions AS ProductCatego");
            viewString.Append("ry_ApplySizeRestrictions, \r\n            T.ApplyFoldLines AS ProductCategory_Appl");
            viewString.Append("yFoldLines, \r\n            T.WidthRestriction AS ProductCategory_WidthRestriction");
            viewString.Append(", \r\n            T.HeightRestriction AS ProductCategory_HeightRestriction, \r\n    ");
            viewString.Append("        T.CategoryTypeId AS ProductCategory_CategoryTypeId, \r\n            T.Regi");
            viewString.Append("onId AS ProductCategory_RegionId, \r\n            T.ZoomFactor AS ProductCategory_");
            viewString.Append("ZoomFactor, \r\n            T.ScaleFactor AS ProductCategory_ScaleFactor, \r\n      ");
            viewString.Append("      T.isShelfProductCategory AS ProductCategory_isShelfProductCategory, \r\n    ");
            viewString.Append("        T.MetaKeywords AS ProductCategory_MetaKeywords, \r\n            T.MetaDesc");
            viewString.Append("ription AS ProductCategory_MetaDescription, \r\n            T.MetaTitle AS Product");
            viewString.Append("Category_MetaTitle, \r\n            T.OrganisationId AS ProductCategory_Organisati");
            viewString.Append("onId, \r\n            True AS _from0\r\n        FROM BaseDbContext.ProductCategories");
            viewString.Append(" AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("DomainModelsStoreContainer.ProductCategory", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for BaseDbContext.Companies
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(9109);
            viewString.Append("\r\n    SELECT VALUE -- Constructing Companies\r\n        [DomainModels.Company](T1.");
            viewString.Append("Company_CompanyId, T1.Company_AccountNumber, T1.Company_Name, T1.Company_URL, T1");
            viewString.Append(".Company_CreditReference, T1.Company_CreditLimit, T1.Company_Terms, T1.Company_T");
            viewString.Append("ypeId, T1.Company_DefaultNominalCode, T1.Company_DefaultMarkUpId, T1.Company_Acc");
            viewString.Append("ountOpenDate, T1.Company_AccountManagerId, T1.Company_Status, T1.Company_IsCusto");
            viewString.Append("mer, T1.Company_Notes, T1.Company_NotesLastUpdatedDate, T1.Company_NotesLastUpda");
            viewString.Append("tedBy, T1.Company_AccountStatusId, T1.Company_IsDisabled, T1.Company_LockedBy, T");
            viewString.Append("1.Company_AccountBalance, T1.Company_CreationDate, T1.Company_VATRegNumber, T1.C");
            viewString.Append("ompany_VATRegReference, T1.Company_PhoneNo, T1.Company_IsGeneral, T1.Company_Sal");
            viewString.Append("esPerson, T1.Company_Image, T1.Company_WebAccessCode, T1.Company_isArchived, T1.");
            viewString.Append("Company_PayByPersonalCredeitCard, T1.Company_PONumberRequired, T1.Company_ShowPr");
            viewString.Append("ices, T1.Company_CarrierWebPath, T1.Company_CarrierTrackingPath, T1.Company_Corp");
            viewString.Append("orateOrderingPolicy, T1.Company_isDisplaySiteHeader, T1.Company_isDisplayMenuBar");
            viewString.Append(", T1.Company_isDisplayBanners, T1.Company_isDisplayFeaturedProducts, T1.Company_");
            viewString.Append("isDisplayPromotionalProducts, T1.Company_isDisplayChooseUsIcons, T1.Company_isDi");
            viewString.Append("splaySecondaryPages, T1.Company_isDisplaySiteFooter, T1.Company_RedirectWebstore");
            viewString.Append("URL, T1.Company_defaultPalleteId, T1.Company_isDisplaylBrokerBanners, T1.Company");
            viewString.Append("_isBrokerCanLaminate, T1.Company_isBrokerCanRoundCorner, T1.Company_isBrokerCanD");
            viewString.Append("eliverSameDay, T1.Company_isBrokerCanAcceptPaymentOnline, T1.Company_isBrokerOrd");
            viewString.Append("erApprovalRequired, T1.Company_isBrokerPaymentRequired, T1.Company_isWhiteLabel,");
            viewString.Append(" T1.Company_TwitterURL, T1.Company_FacebookURL, T1.Company_LinkedinURL, T1.Compa");
            viewString.Append("ny_WebMasterTag, T1.Company_WebAnalyticCode, T1.Company_isShowGoogleMap, T1.Comp");
            viewString.Append("any_isTextWatermark, T1.Company_WatermarkText, T1.Company_CoreCustomerId, T1.Com");
            viewString.Append("pany_StoreBackgroundImage, T1.Company_isDisplayBrokerSecondaryPages, T1.Company_");
            viewString.Append("PriceFlagId, T1.Company_isIncludeVAT, T1.Company_isAllowRegistrationFromWeb, T1.");
            viewString.Append("Company_MarketingBriefRecipient, T1.Company_isLoginFirstTime, T1.Company_faceboo");
            viewString.Append("kAppId, T1.Company_facebookAppKey, T1.Company_twitterAppId, T1.Company_twitterAp");
            viewString.Append("pKey, T1.Company_isStoreModePrivate, T1.Company_CustomCSS, T1.Company_XeroAccess");
            viewString.Append("Code, T1.Company_canUserPlaceOrderWithoutApproval, T1.Company_CanUserEditProfile");
            viewString.Append(", T1.Company_OrganisationId, T1.Company_includeEmailBrokerArtworkOrderReport, T1");
            viewString.Append(".Company_includeEmailBrokerArtworkOrderXML, T1.Company_includeEmailBrokerArtwork");
            viewString.Append("OrderJobCard, T1.Company_makeEmailBrokerArtworkOrderProductionReady, T1.Company_");
            viewString.Append("SalesAndOrderManagerId1, T1.Company_SalesAndOrderManagerId2, T1.Company_Producti");
            viewString.Append("onManagerId1, T1.Company_ProductionManagerId2, T1.Company_StockNotificationManag");
            viewString.Append("erId1, T1.Company_StockNotificationManagerId2, T1.Company_IsDeliveryTaxAble, T1.");
            viewString.Append("Company_IsDisplayDeliveryOnCheckout, T1.Company_DeliveryPickUpAddressId, T1.Comp");
            viewString.Append("any_FlagId, T1.Company_TaxPercentageId)\r\n    FROM (\r\n        SELECT \r\n          ");
            viewString.Append("  T.CompanyId AS Company_CompanyId, \r\n            T.AccountNumber AS Company_Acc");
            viewString.Append("ountNumber, \r\n            T.Name AS Company_Name, \r\n            T.URL AS Company");
            viewString.Append("_URL, \r\n            T.CreditReference AS Company_CreditReference, \r\n            ");
            viewString.Append("T.CreditLimit AS Company_CreditLimit, \r\n            T.Terms AS Company_Terms, \r\n");
            viewString.Append("            T.TypeId AS Company_TypeId, \r\n            T.DefaultNominalCode AS Co");
            viewString.Append("mpany_DefaultNominalCode, \r\n            T.DefaultMarkUpId AS Company_DefaultMark");
            viewString.Append("UpId, \r\n            T.AccountOpenDate AS Company_AccountOpenDate, \r\n            ");
            viewString.Append("T.AccountManagerId AS Company_AccountManagerId, \r\n            T.Status AS Compan");
            viewString.Append("y_Status, \r\n            T.IsCustomer AS Company_IsCustomer, \r\n            T.Note");
            viewString.Append("s AS Company_Notes, \r\n            T.NotesLastUpdatedDate AS Company_NotesLastUpd");
            viewString.Append("atedDate, \r\n            T.NotesLastUpdatedBy AS Company_NotesLastUpdatedBy, \r\n  ");
            viewString.Append("          T.AccountStatusId AS Company_AccountStatusId, \r\n            T.IsDisabl");
            viewString.Append("ed AS Company_IsDisabled, \r\n            T.LockedBy AS Company_LockedBy, \r\n      ");
            viewString.Append("      T.AccountBalance AS Company_AccountBalance, \r\n            T.CreationDate A");
            viewString.Append("S Company_CreationDate, \r\n            T.VATRegNumber AS Company_VATRegNumber, \r\n");
            viewString.Append("            T.VATRegReference AS Company_VATRegReference, \r\n            T.PhoneN");
            viewString.Append("o AS Company_PhoneNo, \r\n            T.IsGeneral AS Company_IsGeneral, \r\n        ");
            viewString.Append("    T.SalesPerson AS Company_SalesPerson, \r\n            T.Image AS Company_Image");
            viewString.Append(", \r\n            T.WebAccessCode AS Company_WebAccessCode, \r\n            T.isArch");
            viewString.Append("ived AS Company_isArchived, \r\n            T.PayByPersonalCredeitCard AS Company_");
            viewString.Append("PayByPersonalCredeitCard, \r\n            T.PONumberRequired AS Company_PONumberRe");
            viewString.Append("quired, \r\n            T.ShowPrices AS Company_ShowPrices, \r\n            T.Carrie");
            viewString.Append("rWebPath AS Company_CarrierWebPath, \r\n            T.CarrierTrackingPath AS Compa");
            viewString.Append("ny_CarrierTrackingPath, \r\n            T.CorporateOrderingPolicy AS Company_Corpo");
            viewString.Append("rateOrderingPolicy, \r\n            T.isDisplaySiteHeader AS Company_isDisplaySite");
            viewString.Append("Header, \r\n            T.isDisplayMenuBar AS Company_isDisplayMenuBar, \r\n        ");
            viewString.Append("    T.isDisplayBanners AS Company_isDisplayBanners, \r\n            T.isDisplayFea");
            viewString.Append("turedProducts AS Company_isDisplayFeaturedProducts, \r\n            T.isDisplayPro");
            viewString.Append("motionalProducts AS Company_isDisplayPromotionalProducts, \r\n            T.isDisp");
            viewString.Append("layChooseUsIcons AS Company_isDisplayChooseUsIcons, \r\n            T.isDisplaySec");
            viewString.Append("ondaryPages AS Company_isDisplaySecondaryPages, \r\n            T.isDisplaySiteFoo");
            viewString.Append("ter AS Company_isDisplaySiteFooter, \r\n            T.RedirectWebstoreURL AS Compa");
            viewString.Append("ny_RedirectWebstoreURL, \r\n            T.defaultPalleteId AS Company_defaultPalle");
            viewString.Append("teId, \r\n            T.isDisplaylBrokerBanners AS Company_isDisplaylBrokerBanners");
            viewString.Append(", \r\n            T.isBrokerCanLaminate AS Company_isBrokerCanLaminate, \r\n        ");
            viewString.Append("    T.isBrokerCanRoundCorner AS Company_isBrokerCanRoundCorner, \r\n            T.");
            viewString.Append("isBrokerCanDeliverSameDay AS Company_isBrokerCanDeliverSameDay, \r\n            T.");
            viewString.Append("isBrokerCanAcceptPaymentOnline AS Company_isBrokerCanAcceptPaymentOnline, \r\n    ");
            viewString.Append("        T.isBrokerOrderApprovalRequired AS Company_isBrokerOrderApprovalRequired");
            viewString.Append(", \r\n            T.isBrokerPaymentRequired AS Company_isBrokerPaymentRequired, \r\n");
            viewString.Append("            T.isWhiteLabel AS Company_isWhiteLabel, \r\n            T.TwitterURL A");
            viewString.Append("S Company_TwitterURL, \r\n            T.FacebookURL AS Company_FacebookURL, \r\n    ");
            viewString.Append("        T.LinkedinURL AS Company_LinkedinURL, \r\n            T.WebMasterTag AS Co");
            viewString.Append("mpany_WebMasterTag, \r\n            T.WebAnalyticCode AS Company_WebAnalyticCode, ");
            viewString.Append("\r\n            T.isShowGoogleMap AS Company_isShowGoogleMap, \r\n            T.isTe");
            viewString.Append("xtWatermark AS Company_isTextWatermark, \r\n            T.WatermarkText AS Company");
            viewString.Append("_WatermarkText, \r\n            T.CoreCustomerId AS Company_CoreCustomerId, \r\n    ");
            viewString.Append("        T.StoreBackgroundImage AS Company_StoreBackgroundImage, \r\n            T.");
            viewString.Append("isDisplayBrokerSecondaryPages AS Company_isDisplayBrokerSecondaryPages, \r\n      ");
            viewString.Append("      T.PriceFlagId AS Company_PriceFlagId, \r\n            T.isIncludeVAT AS Comp");
            viewString.Append("any_isIncludeVAT, \r\n            T.isAllowRegistrationFromWeb AS Company_isAllowR");
            viewString.Append("egistrationFromWeb, \r\n            T.MarketingBriefRecipient AS Company_Marketing");
            viewString.Append("BriefRecipient, \r\n            T.isLoginFirstTime AS Company_isLoginFirstTime, \r\n");
            viewString.Append("            T.facebookAppId AS Company_facebookAppId, \r\n            T.facebookAp");
            viewString.Append("pKey AS Company_facebookAppKey, \r\n            T.twitterAppId AS Company_twitterA");
            viewString.Append("ppId, \r\n            T.twitterAppKey AS Company_twitterAppKey, \r\n            T.is");
            viewString.Append("StoreModePrivate AS Company_isStoreModePrivate, \r\n            T.CustomCSS AS Com");
            viewString.Append("pany_CustomCSS, \r\n            T.XeroAccessCode AS Company_XeroAccessCode, \r\n    ");
            viewString.Append("        T.canUserPlaceOrderWithoutApproval AS Company_canUserPlaceOrderWithoutAp");
            viewString.Append("proval, \r\n            T.CanUserEditProfile AS Company_CanUserEditProfile, \r\n    ");
            viewString.Append("        T.OrganisationId AS Company_OrganisationId, \r\n            T.includeEmail");
            viewString.Append("BrokerArtworkOrderReport AS Company_includeEmailBrokerArtworkOrderReport, \r\n    ");
            viewString.Append("        T.includeEmailBrokerArtworkOrderXML AS Company_includeEmailBrokerArtwork");
            viewString.Append("OrderXML, \r\n            T.includeEmailBrokerArtworkOrderJobCard AS Company_inclu");
            viewString.Append("deEmailBrokerArtworkOrderJobCard, \r\n            T.makeEmailBrokerArtworkOrderPro");
            viewString.Append("ductionReady AS Company_makeEmailBrokerArtworkOrderProductionReady, \r\n          ");
            viewString.Append("  T.SalesAndOrderManagerId1 AS Company_SalesAndOrderManagerId1, \r\n            T.");
            viewString.Append("SalesAndOrderManagerId2 AS Company_SalesAndOrderManagerId2, \r\n            T.Prod");
            viewString.Append("uctionManagerId1 AS Company_ProductionManagerId1, \r\n            T.ProductionMana");
            viewString.Append("gerId2 AS Company_ProductionManagerId2, \r\n            T.StockNotificationManager");
            viewString.Append("Id1 AS Company_StockNotificationManagerId1, \r\n            T.StockNotificationMan");
            viewString.Append("agerId2 AS Company_StockNotificationManagerId2, \r\n            T.IsDeliveryTaxAbl");
            viewString.Append("e AS Company_IsDeliveryTaxAble, \r\n            T.IsDisplayDeliveryOnCheckout AS C");
            viewString.Append("ompany_IsDisplayDeliveryOnCheckout, \r\n            T.DeliveryPickUpAddressId AS C");
            viewString.Append("ompany_DeliveryPickUpAddressId, \r\n            T.FlagId AS Company_FlagId, \r\n    ");
            viewString.Append("        T.TaxPercentageId AS Company_TaxPercentageId, \r\n            True AS _fro");
            viewString.Append("m0\r\n        FROM DomainModelsStoreContainer.Company AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("BaseDbContext.Companies", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for BaseDbContext.CompanyDomains
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("BaseDbContext.CompanyDomains", @"
    SELECT VALUE -- Constructing CompanyDomains
        [DomainModels.CompanyDomain](T1.CompanyDomain_CompanyDomainId, T1.CompanyDomain_Domain, T1.CompanyDomain_CompanyId)
    FROM (
        SELECT 
            T.CompanyDomainId AS CompanyDomain_CompanyDomainId, 
            T.Domain AS CompanyDomain_Domain, 
            T.CompanyId AS CompanyDomain_CompanyId, 
            True AS _from0
        FROM DomainModelsStoreContainer.CompanyDomain AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for BaseDbContext.CmsSkinPageWidgets
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("BaseDbContext.CmsSkinPageWidgets", @"
    SELECT VALUE -- Constructing CmsSkinPageWidgets
        [DomainModels.CmsSkinPageWidget](T1.CmsSkinPageWidget_PageWidgetId, T1.CmsSkinPageWidget_PageId, T1.CmsSkinPageWidget_WidgetId, T1.CmsSkinPageWidget_SkinId, T1.CmsSkinPageWidget_Sequence, T1.CmsSkinPageWidget_CompanyId, T1.CmsSkinPageWidget_OrganisationId)
    FROM (
        SELECT 
            T.PageWidgetId AS CmsSkinPageWidget_PageWidgetId, 
            T.PageId AS CmsSkinPageWidget_PageId, 
            T.WidgetId AS CmsSkinPageWidget_WidgetId, 
            T.SkinId AS CmsSkinPageWidget_SkinId, 
            T.Sequence AS CmsSkinPageWidget_Sequence, 
            T.CompanyId AS CmsSkinPageWidget_CompanyId, 
            T.OrganisationId AS CmsSkinPageWidget_OrganisationId, 
            True AS _from0
        FROM DomainModelsStoreContainer.CmsSkinPageWidget AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for BaseDbContext.CmsSkinPageWidgetParams
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("BaseDbContext.CmsSkinPageWidgetParams", @"
    SELECT VALUE -- Constructing CmsSkinPageWidgetParams
        [DomainModels.CmsSkinPageWidgetParam](T1.CmsSkinPageWidgetParam_PageWidgetParamId, T1.CmsSkinPageWidgetParam_PageWidgetId, T1.CmsSkinPageWidgetParam_ParamName, T1.CmsSkinPageWidgetParam_ParamValue)
    FROM (
        SELECT 
            T.PageWidgetParamId AS CmsSkinPageWidgetParam_PageWidgetParamId, 
            T.PageWidgetId AS CmsSkinPageWidgetParam_PageWidgetId, 
            T.ParamName AS CmsSkinPageWidgetParam_ParamName, 
            T.ParamValue AS CmsSkinPageWidgetParam_ParamValue, 
            True AS _from0
        FROM DomainModelsStoreContainer.CmsSkinPageWidgetParam AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for BaseDbContext.Widgets
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("BaseDbContext.Widgets", @"
    SELECT VALUE -- Constructing Widgets
        [DomainModels.Widget](T1.Widget_WidgetId, T1.Widget_WidgetCode, T1.Widget_WidgetName, T1.Widget_WidgetControlName)
    FROM (
        SELECT 
            T.WidgetId AS Widget_WidgetId, 
            T.WidgetCode AS Widget_WidgetCode, 
            T.WidgetName AS Widget_WidgetName, 
            T.WidgetControlName AS Widget_WidgetControlName, 
            True AS _from0
        FROM DomainModelsStoreContainer.Widgets AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for BaseDbContext.ProductCategories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(3705);
            viewString.Append("\r\n    SELECT VALUE -- Constructing ProductCategories\r\n        [DomainModels.Prod");
            viewString.Append("uctCategory](T1.ProductCategory_ProductCategoryId, T1.ProductCategory_CategoryNa");
            viewString.Append("me, T1.ProductCategory_ContentType, T1.ProductCategory_Description1, T1.ProductC");
            viewString.Append("ategory_Description2, T1.ProductCategory_LockedBy, T1.ProductCategory_CompanyId,");
            viewString.Append(" T1.ProductCategory_ParentCategoryId, T1.ProductCategory_DisplayOrder, T1.Produc");
            viewString.Append("tCategory_ImagePath, T1.ProductCategory_ThumbnailPath, T1.ProductCategory_isEnab");
            viewString.Append("led, T1.ProductCategory_isMarketPlace, T1.ProductCategory_TemplateDesignerMapped");
            viewString.Append("CategoryName, T1.ProductCategory_isArchived, T1.ProductCategory_isPublished, T1.");
            viewString.Append("ProductCategory_TrimmedWidth, T1.ProductCategory_TrimmedHeight, T1.ProductCatego");
            viewString.Append("ry_isColorImposition, T1.ProductCategory_isOrderImposition, T1.ProductCategory_i");
            viewString.Append("sLinkToTemplates, T1.ProductCategory_Sides, T1.ProductCategory_ApplySizeRestrict");
            viewString.Append("ions, T1.ProductCategory_ApplyFoldLines, T1.ProductCategory_WidthRestriction, T1");
            viewString.Append(".ProductCategory_HeightRestriction, T1.ProductCategory_CategoryTypeId, T1.Produc");
            viewString.Append("tCategory_RegionId, T1.ProductCategory_ZoomFactor, T1.ProductCategory_ScaleFacto");
            viewString.Append("r, T1.ProductCategory_isShelfProductCategory, T1.ProductCategory_MetaKeywords, T");
            viewString.Append("1.ProductCategory_MetaDescription, T1.ProductCategory_MetaTitle, T1.ProductCateg");
            viewString.Append("ory_OrganisationId)\r\n    FROM (\r\n        SELECT \r\n            T.ProductCategoryI");
            viewString.Append("d AS ProductCategory_ProductCategoryId, \r\n            T.CategoryName AS ProductC");
            viewString.Append("ategory_CategoryName, \r\n            T.ContentType AS ProductCategory_ContentType");
            viewString.Append(", \r\n            T.Description1 AS ProductCategory_Description1, \r\n            T.");
            viewString.Append("Description2 AS ProductCategory_Description2, \r\n            T.LockedBy AS Produc");
            viewString.Append("tCategory_LockedBy, \r\n            T.CompanyId AS ProductCategory_CompanyId, \r\n  ");
            viewString.Append("          T.ParentCategoryId AS ProductCategory_ParentCategoryId, \r\n            ");
            viewString.Append("T.DisplayOrder AS ProductCategory_DisplayOrder, \r\n            T.ImagePath AS Pro");
            viewString.Append("ductCategory_ImagePath, \r\n            T.ThumbnailPath AS ProductCategory_Thumbna");
            viewString.Append("ilPath, \r\n            T.isEnabled AS ProductCategory_isEnabled, \r\n            T.");
            viewString.Append("isMarketPlace AS ProductCategory_isMarketPlace, \r\n            T.TemplateDesigner");
            viewString.Append("MappedCategoryName AS ProductCategory_TemplateDesignerMappedCategoryName, \r\n    ");
            viewString.Append("        T.isArchived AS ProductCategory_isArchived, \r\n            T.isPublished ");
            viewString.Append("AS ProductCategory_isPublished, \r\n            T.TrimmedWidth AS ProductCategory_");
            viewString.Append("TrimmedWidth, \r\n            T.TrimmedHeight AS ProductCategory_TrimmedHeight, \r\n");
            viewString.Append("            T.isColorImposition AS ProductCategory_isColorImposition, \r\n        ");
            viewString.Append("    T.isOrderImposition AS ProductCategory_isOrderImposition, \r\n            T.is");
            viewString.Append("LinkToTemplates AS ProductCategory_isLinkToTemplates, \r\n            T.Sides AS P");
            viewString.Append("roductCategory_Sides, \r\n            T.ApplySizeRestrictions AS ProductCategory_A");
            viewString.Append("pplySizeRestrictions, \r\n            T.ApplyFoldLines AS ProductCategory_ApplyFol");
            viewString.Append("dLines, \r\n            T.WidthRestriction AS ProductCategory_WidthRestriction, \r\n");
            viewString.Append("            T.HeightRestriction AS ProductCategory_HeightRestriction, \r\n        ");
            viewString.Append("    T.CategoryTypeId AS ProductCategory_CategoryTypeId, \r\n            T.RegionId");
            viewString.Append(" AS ProductCategory_RegionId, \r\n            T.ZoomFactor AS ProductCategory_Zoom");
            viewString.Append("Factor, \r\n            T.ScaleFactor AS ProductCategory_ScaleFactor, \r\n          ");
            viewString.Append("  T.isShelfProductCategory AS ProductCategory_isShelfProductCategory, \r\n        ");
            viewString.Append("    T.MetaKeywords AS ProductCategory_MetaKeywords, \r\n            T.MetaDescript");
            viewString.Append("ion AS ProductCategory_MetaDescription, \r\n            T.MetaTitle AS ProductCate");
            viewString.Append("gory_MetaTitle, \r\n            T.OrganisationId AS ProductCategory_OrganisationId");
            viewString.Append(", \r\n            True AS _from0\r\n        FROM DomainModelsStoreContainer.ProductC");
            viewString.Append("ategory AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("BaseDbContext.ProductCategories", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for DomainModelsStoreContainer.Markup
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DomainModelsStoreContainer.Markup", @"
    SELECT VALUE -- Constructing Markup
        [DomainModels.Store.Markup](T1.Markup_MarkUpId, T1.Markup_MarkUpName, T1.Markup_MarkUpRate, T1.Markup_IsFixed, T1.Markup_IsDefault, T1.Markup_UserDomainKey)
    FROM (
        SELECT 
            T.MarkUpId AS Markup_MarkUpId, 
            T.MarkUpName AS Markup_MarkUpName, 
            T.MarkUpRate AS Markup_MarkUpRate, 
            T.IsFixed AS Markup_IsFixed, 
            T.IsDefault AS Markup_IsDefault, 
            T.UserDomainKey AS Markup_UserDomainKey, 
            True AS _from0
        FROM BaseDbContext.Markups AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for BaseDbContext.Markups
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("BaseDbContext.Markups", @"
    SELECT VALUE -- Constructing Markups
        [DomainModels.Markup](T1.Markup_MarkUpId, T1.Markup_MarkUpName, T1.Markup_MarkUpRate, T1.Markup_IsFixed, T1.Markup_IsDefault, T1.Markup_UserDomainKey)
    FROM (
        SELECT 
            T.MarkUpId AS Markup_MarkUpId, 
            T.MarkUpName AS Markup_MarkUpName, 
            T.MarkUpRate AS Markup_MarkUpRate, 
            T.IsFixed AS Markup_IsFixed, 
            T.IsDefault AS Markup_IsDefault, 
            T.UserDomainKey AS Markup_UserDomainKey, 
            True AS _from0
        FROM DomainModelsStoreContainer.Markup AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DomainModelsStoreContainer.CmsPage
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2770);
            viewString.Append("\r\n    SELECT VALUE -- Constructing CmsPage\r\n        [DomainModels.Store.CmsPage]");
            viewString.Append("(T1.CmsPage_PageId, T1.CmsPage_PageName, T1.CmsPage_PageTitle, T1.CmsPage_MenuTi");
            viewString.Append("tle, T1.CmsPage_description, T1.CmsPage_PageRelativePath, T1.CmsPage_SortOrder, ");
            viewString.Append("T1.[CmsPage.Meta_KeywordContent], T1.[CmsPage.Meta_DescriptionContent], T1.[CmsP");
            viewString.Append("age.Meta_HiddenDescriptionContent], T1.[CmsPage.Meta_CategoryContent], T1.[CmsPa");
            viewString.Append("ge.Meta_RobotsContent], T1.[CmsPage.Meta_AuthorContent], T1.[CmsPage.Meta_DateCo");
            viewString.Append("ntent], T1.[CmsPage.Meta_LanguageContent], T1.[CmsPage.Meta_RevisitAfterContent]");
            viewString.Append(", T1.[CmsPage.Meta_Title], T1.CmsPage_PageHTML, T1.CmsPage_isUserDefined, T1.Cms");
            viewString.Append("Page_CategoryId, T1.CmsPage_isPromotionalOffer, T1.CmsPage_isSepecialOffer, T1.C");
            viewString.Append("msPage_isMPCAdd, T1.CmsPage_LastModifiedDate, T1.CmsPage_PageBanner, T1.CmsPage_");
            viewString.Append("PageKeywords, T1.CmsPage_isEnabled, T1.CmsPage_isDisplay, T1.CmsPage_CompanyId, ");
            viewString.Append("T1.CmsPage_OrganisationId)\r\n    FROM (\r\n        SELECT \r\n            T.PageId AS");
            viewString.Append(" CmsPage_PageId, \r\n            T.PageName AS CmsPage_PageName, \r\n            T.P");
            viewString.Append("ageTitle AS CmsPage_PageTitle, \r\n            T.MenuTitle AS CmsPage_MenuTitle, \r");
            viewString.Append("\n            T.description AS CmsPage_description, \r\n            T.PageRelativeP");
            viewString.Append("ath AS CmsPage_PageRelativePath, \r\n            T.SortOrder AS CmsPage_SortOrder,");
            viewString.Append(" \r\n            T.Meta_KeywordContent AS [CmsPage.Meta_KeywordContent], \r\n       ");
            viewString.Append("     T.Meta_DescriptionContent AS [CmsPage.Meta_DescriptionContent], \r\n         ");
            viewString.Append("   T.Meta_HiddenDescriptionContent AS [CmsPage.Meta_HiddenDescriptionContent], \r");
            viewString.Append("\n            T.Meta_CategoryContent AS [CmsPage.Meta_CategoryContent], \r\n       ");
            viewString.Append("     T.Meta_RobotsContent AS [CmsPage.Meta_RobotsContent], \r\n            T.Meta_");
            viewString.Append("AuthorContent AS [CmsPage.Meta_AuthorContent], \r\n            T.Meta_DateContent ");
            viewString.Append("AS [CmsPage.Meta_DateContent], \r\n            T.Meta_LanguageContent AS [CmsPage.");
            viewString.Append("Meta_LanguageContent], \r\n            T.Meta_RevisitAfterContent AS [CmsPage.Meta");
            viewString.Append("_RevisitAfterContent], \r\n            T.Meta_Title AS [CmsPage.Meta_Title], \r\n   ");
            viewString.Append("         T.PageHTML AS CmsPage_PageHTML, \r\n            T.isUserDefined AS CmsPag");
            viewString.Append("e_isUserDefined, \r\n            T.CategoryId AS CmsPage_CategoryId, \r\n           ");
            viewString.Append(" T.isPromotionalOffer AS CmsPage_isPromotionalOffer, \r\n            T.isSepecialO");
            viewString.Append("ffer AS CmsPage_isSepecialOffer, \r\n            T.isMPCAdd AS CmsPage_isMPCAdd, \r");
            viewString.Append("\n            T.LastModifiedDate AS CmsPage_LastModifiedDate, \r\n            T.Pag");
            viewString.Append("eBanner AS CmsPage_PageBanner, \r\n            T.PageKeywords AS CmsPage_PageKeywo");
            viewString.Append("rds, \r\n            T.isEnabled AS CmsPage_isEnabled, \r\n            T.isDisplay A");
            viewString.Append("S CmsPage_isDisplay, \r\n            T.CompanyId AS CmsPage_CompanyId, \r\n         ");
            viewString.Append("   T.OrganisationId AS CmsPage_OrganisationId, \r\n            True AS _from0\r\n   ");
            viewString.Append("     FROM BaseDbContext.CmsPages AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("DomainModelsStoreContainer.CmsPage", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for BaseDbContext.CmsPages
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2777);
            viewString.Append("\r\n    SELECT VALUE -- Constructing CmsPages\r\n        [DomainModels.CmsPage](T1.C");
            viewString.Append("msPage_PageId, T1.CmsPage_PageName, T1.CmsPage_PageTitle, T1.CmsPage_MenuTitle, ");
            viewString.Append("T1.CmsPage_description, T1.CmsPage_PageRelativePath, T1.CmsPage_SortOrder, T1.[C");
            viewString.Append("msPage.Meta_KeywordContent], T1.[CmsPage.Meta_DescriptionContent], T1.[CmsPage.M");
            viewString.Append("eta_HiddenDescriptionContent], T1.[CmsPage.Meta_CategoryContent], T1.[CmsPage.Me");
            viewString.Append("ta_RobotsContent], T1.[CmsPage.Meta_AuthorContent], T1.[CmsPage.Meta_DateContent");
            viewString.Append("], T1.[CmsPage.Meta_LanguageContent], T1.[CmsPage.Meta_RevisitAfterContent], T1.");
            viewString.Append("[CmsPage.Meta_Title], T1.CmsPage_PageHTML, T1.CmsPage_isUserDefined, T1.CmsPage_");
            viewString.Append("CategoryId, T1.CmsPage_isPromotionalOffer, T1.CmsPage_isSepecialOffer, T1.CmsPag");
            viewString.Append("e_isMPCAdd, T1.CmsPage_LastModifiedDate, T1.CmsPage_PageBanner, T1.CmsPage_PageK");
            viewString.Append("eywords, T1.CmsPage_isEnabled, T1.CmsPage_isDisplay, T1.CmsPage_CompanyId, T1.Cm");
            viewString.Append("sPage_OrganisationId)\r\n    FROM (\r\n        SELECT \r\n            T.PageId AS CmsP");
            viewString.Append("age_PageId, \r\n            T.PageName AS CmsPage_PageName, \r\n            T.PageTi");
            viewString.Append("tle AS CmsPage_PageTitle, \r\n            T.MenuTitle AS CmsPage_MenuTitle, \r\n    ");
            viewString.Append("        T.description AS CmsPage_description, \r\n            T.PageRelativePath A");
            viewString.Append("S CmsPage_PageRelativePath, \r\n            T.SortOrder AS CmsPage_SortOrder, \r\n  ");
            viewString.Append("          T.Meta_KeywordContent AS [CmsPage.Meta_KeywordContent], \r\n            ");
            viewString.Append("T.Meta_DescriptionContent AS [CmsPage.Meta_DescriptionContent], \r\n            T.");
            viewString.Append("Meta_HiddenDescriptionContent AS [CmsPage.Meta_HiddenDescriptionContent], \r\n    ");
            viewString.Append("        T.Meta_CategoryContent AS [CmsPage.Meta_CategoryContent], \r\n            ");
            viewString.Append("T.Meta_RobotsContent AS [CmsPage.Meta_RobotsContent], \r\n            T.Meta_Autho");
            viewString.Append("rContent AS [CmsPage.Meta_AuthorContent], \r\n            T.Meta_DateContent AS [C");
            viewString.Append("msPage.Meta_DateContent], \r\n            T.Meta_LanguageContent AS [CmsPage.Meta_");
            viewString.Append("LanguageContent], \r\n            T.Meta_RevisitAfterContent AS [CmsPage.Meta_Revi");
            viewString.Append("sitAfterContent], \r\n            T.Meta_Title AS [CmsPage.Meta_Title], \r\n        ");
            viewString.Append("    T.PageHTML AS CmsPage_PageHTML, \r\n            T.isUserDefined AS CmsPage_isU");
            viewString.Append("serDefined, \r\n            T.CategoryId AS CmsPage_CategoryId, \r\n            T.is");
            viewString.Append("PromotionalOffer AS CmsPage_isPromotionalOffer, \r\n            T.isSepecialOffer ");
            viewString.Append("AS CmsPage_isSepecialOffer, \r\n            T.isMPCAdd AS CmsPage_isMPCAdd, \r\n    ");
            viewString.Append("        T.LastModifiedDate AS CmsPage_LastModifiedDate, \r\n            T.PageBann");
            viewString.Append("er AS CmsPage_PageBanner, \r\n            T.PageKeywords AS CmsPage_PageKeywords, ");
            viewString.Append("\r\n            T.isEnabled AS CmsPage_isEnabled, \r\n            T.isDisplay AS Cms");
            viewString.Append("Page_isDisplay, \r\n            T.CompanyId AS CmsPage_CompanyId, \r\n            T.");
            viewString.Append("OrganisationId AS CmsPage_OrganisationId, \r\n            True AS _from0\r\n        ");
            viewString.Append("FROM DomainModelsStoreContainer.CmsPage AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("BaseDbContext.CmsPages", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for DomainModelsStoreContainer.ChartOfAccount
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DomainModelsStoreContainer.ChartOfAccount", "\r\n    SELECT VALUE -- Constructing ChartOfAccount\r\n        [DomainModels.Store.Ch" +
                    "artOfAccount](T1.ChartOfAccount_Id, T1.ChartOfAccount_AccountNo, T1.ChartOfAccou" +
                    "nt_Name, T1.ChartOfAccount_OpeningBalance, T1.ChartOfAccount_OpeningBalanceType," +
                    " T1.ChartOfAccount_TypeId, T1.ChartOfAccount_SubTypeId, T1.ChartOfAccount_Descri" +
                    "ption, T1.ChartOfAccount_Nature, T1.ChartOfAccount_IsActive, T1.ChartOfAccount_I" +
                    "sFixed, T1.ChartOfAccount_LastActivityDate, T1.ChartOfAccount_IsForReconciliatio" +
                    "n, T1.ChartOfAccount_Balance, T1.ChartOfAccount_IsRead, T1.ChartOfAccount_System" +
                    "SiteId, T1.ChartOfAccount_UserDomainKey)\r\n    FROM (\r\n        SELECT \r\n         " +
                    "   T.Id AS ChartOfAccount_Id, \r\n            T.AccountNo AS ChartOfAccount_Accoun" +
                    "tNo, \r\n            T.Name AS ChartOfAccount_Name, \r\n            T.OpeningBalance" +
                    " AS ChartOfAccount_OpeningBalance, \r\n            T.OpeningBalanceType AS ChartOf" +
                    "Account_OpeningBalanceType, \r\n            T.TypeId AS ChartOfAccount_TypeId, \r\n " +
                    "           T.SubTypeId AS ChartOfAccount_SubTypeId, \r\n            T.Description " +
                    "AS ChartOfAccount_Description, \r\n            T.Nature AS ChartOfAccount_Nature, " +
                    "\r\n            T.IsActive AS ChartOfAccount_IsActive, \r\n            T.IsFixed AS " +
                    "ChartOfAccount_IsFixed, \r\n            T.LastActivityDate AS ChartOfAccount_LastA" +
                    "ctivityDate, \r\n            T.IsForReconciliation AS ChartOfAccount_IsForReconcil" +
                    "iation, \r\n            T.Balance AS ChartOfAccount_Balance, \r\n            T.IsRea" +
                    "d AS ChartOfAccount_IsRead, \r\n            T.SystemSiteId AS ChartOfAccount_Syste" +
                    "mSiteId, \r\n            T.UserDomainKey AS ChartOfAccount_UserDomainKey, \r\n      " +
                    "      True AS _from0\r\n        FROM BaseDbContext.ChartOfAccounts AS T\r\n    ) AS " +
                    "T1");
        }
        
        /// <Summary>
        /// return view for BaseDbContext.ChartOfAccounts
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("BaseDbContext.ChartOfAccounts", "\r\n    SELECT VALUE -- Constructing ChartOfAccounts\r\n        [DomainModels.ChartOf" +
                    "Account](T1.ChartOfAccount_Id, T1.ChartOfAccount_AccountNo, T1.ChartOfAccount_Na" +
                    "me, T1.ChartOfAccount_OpeningBalance, T1.ChartOfAccount_OpeningBalanceType, T1.C" +
                    "hartOfAccount_TypeId, T1.ChartOfAccount_SubTypeId, T1.ChartOfAccount_Description" +
                    ", T1.ChartOfAccount_Nature, T1.ChartOfAccount_IsActive, T1.ChartOfAccount_IsFixe" +
                    "d, T1.ChartOfAccount_LastActivityDate, T1.ChartOfAccount_IsForReconciliation, T1" +
                    ".ChartOfAccount_Balance, T1.ChartOfAccount_IsRead, T1.ChartOfAccount_SystemSiteI" +
                    "d, T1.ChartOfAccount_UserDomainKey)\r\n    FROM (\r\n        SELECT \r\n            T." +
                    "Id AS ChartOfAccount_Id, \r\n            T.AccountNo AS ChartOfAccount_AccountNo, " +
                    "\r\n            T.Name AS ChartOfAccount_Name, \r\n            T.OpeningBalance AS C" +
                    "hartOfAccount_OpeningBalance, \r\n            T.OpeningBalanceType AS ChartOfAccou" +
                    "nt_OpeningBalanceType, \r\n            T.TypeId AS ChartOfAccount_TypeId, \r\n      " +
                    "      T.SubTypeId AS ChartOfAccount_SubTypeId, \r\n            T.Description AS Ch" +
                    "artOfAccount_Description, \r\n            T.Nature AS ChartOfAccount_Nature, \r\n   " +
                    "         T.IsActive AS ChartOfAccount_IsActive, \r\n            T.IsFixed AS Chart" +
                    "OfAccount_IsFixed, \r\n            T.LastActivityDate AS ChartOfAccount_LastActivi" +
                    "tyDate, \r\n            T.IsForReconciliation AS ChartOfAccount_IsForReconciliatio" +
                    "n, \r\n            T.Balance AS ChartOfAccount_Balance, \r\n            T.IsRead AS " +
                    "ChartOfAccount_IsRead, \r\n            T.SystemSiteId AS ChartOfAccount_SystemSite" +
                    "Id, \r\n            T.UserDomainKey AS ChartOfAccount_UserDomainKey, \r\n           " +
                    " True AS _from0\r\n        FROM DomainModelsStoreContainer.ChartOfAccount AS T\r\n  " +
                    "  ) AS T1");
        }
        
        /// <Summary>
        /// return view for DomainModelsStoreContainer.PaperSize
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DomainModelsStoreContainer.PaperSize", @"
    SELECT VALUE -- Constructing PaperSize
        [DomainModels.Store.PaperSize](T1.PaperSize_PaperSizeId, T1.PaperSize_Name, T1.PaperSize_Height, T1.PaperSize_Width, T1.PaperSize_SizeMeasure, T1.PaperSize_Area, T1.PaperSize_IsFixed, T1.PaperSize_Region, T1.PaperSize_isArchived)
    FROM (
        SELECT 
            T.PaperSizeId AS PaperSize_PaperSizeId, 
            T.Name AS PaperSize_Name, 
            T.Height AS PaperSize_Height, 
            T.Width AS PaperSize_Width, 
            T.SizeMeasure AS PaperSize_SizeMeasure, 
            T.Area AS PaperSize_Area, 
            T.IsFixed AS PaperSize_IsFixed, 
            T.Region AS PaperSize_Region, 
            T.isArchived AS PaperSize_isArchived, 
            True AS _from0
        FROM BaseDbContext.PaperSizes AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for BaseDbContext.PaperSizes
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("BaseDbContext.PaperSizes", @"
    SELECT VALUE -- Constructing PaperSizes
        [DomainModels.PaperSize](T1.PaperSize_PaperSizeId, T1.PaperSize_Name, T1.PaperSize_Height, T1.PaperSize_Width, T1.PaperSize_SizeMeasure, T1.PaperSize_Area, T1.PaperSize_IsFixed, T1.PaperSize_Region, T1.PaperSize_isArchived)
    FROM (
        SELECT 
            T.PaperSizeId AS PaperSize_PaperSizeId, 
            T.Name AS PaperSize_Name, 
            T.Height AS PaperSize_Height, 
            T.Width AS PaperSize_Width, 
            T.SizeMeasure AS PaperSize_SizeMeasure, 
            T.Area AS PaperSize_Area, 
            T.IsFixed AS PaperSize_IsFixed, 
            T.Region AS PaperSize_Region, 
            T.isArchived AS PaperSize_isArchived, 
            True AS _from0
        FROM DomainModelsStoreContainer.PaperSize AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DomainModelsStoreContainer.CategoryTerritory
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DomainModelsStoreContainer.CategoryTerritory", @"
    SELECT VALUE -- Constructing CategoryTerritory
        [DomainModels.Store.CategoryTerritory](T1.CategoryTerritory_CategoryTerritoryId, T1.CategoryTerritory_ContactCompanyId, T1.CategoryTerritory_ProductCategoryId, T1.CategoryTerritory_TerritoryId, T1.CategoryTerritory_OrganisationId)
    FROM (
        SELECT 
            T.CategoryTerritoryId AS CategoryTerritory_CategoryTerritoryId, 
            T.ContactCompanyId AS CategoryTerritory_ContactCompanyId, 
            T.ProductCategoryId AS CategoryTerritory_ProductCategoryId, 
            T.TerritoryId AS CategoryTerritory_TerritoryId, 
            T.OrganisationId AS CategoryTerritory_OrganisationId, 
            True AS _from0
        FROM BaseDbContext.CategoryTerritories AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for BaseDbContext.CategoryTerritories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("BaseDbContext.CategoryTerritories", @"
    SELECT VALUE -- Constructing CategoryTerritories
        [DomainModels.CategoryTerritory](T1.CategoryTerritory_CategoryTerritoryId, T1.CategoryTerritory_ContactCompanyId, T1.CategoryTerritory_ProductCategoryId, T1.CategoryTerritory_TerritoryId, T1.CategoryTerritory_OrganisationId)
    FROM (
        SELECT 
            T.CategoryTerritoryId AS CategoryTerritory_CategoryTerritoryId, 
            T.ContactCompanyId AS CategoryTerritory_ContactCompanyId, 
            T.ProductCategoryId AS CategoryTerritory_ProductCategoryId, 
            T.TerritoryId AS CategoryTerritory_TerritoryId, 
            T.OrganisationId AS CategoryTerritory_OrganisationId, 
            True AS _from0
        FROM DomainModelsStoreContainer.CategoryTerritory AS T
    ) AS T1");
        }
    }
}


