//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPC.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRate
    {
        public int TaxId { get; set; }
        public string TaxCode { get; set; }
        public string TaxName { get; set; }
        public Nullable<int> SourceStateId { get; set; }
        public Nullable<int> DestinationStateId { get; set; }
        public Nullable<double> Tax1 { get; set; }
        public Nullable<double> Tax2 { get; set; }
        public Nullable<double> Tax3 { get; set; }
        public Nullable<bool> IsFixed { get; set; }
        public int UserDomainKey { get; set; }
    }
}
