CREATE PROCEDURE dbo.StoredProcedure14
	@CampaignID int
AS
	Select 
CampaignID,
UID,
Private,
CampaignName,
Description,
EnableWriteBackTab,
EnableClickThruTab,
EnableUnsubscribeEmail ,
EnableBouncedEmail,
EnableSubscribeEmail,
EnableOpenedEmail,
DataSourceType,
SQLQuery,
IncludeCustomers,
IncludeSuppliers,
IncludeProspects,
IncludeKeyword,
SearchKeyword,
IncludeType,
IncludeFlag,
SendEmailTo ,
SendToAll ,
MessageType,
FromAddress,
ReturnPathAddress,
ReplyToAddress,
SubjectA,
HTMLMessageA,
SubjectB,
HTMLMessageB ,
PlainTextMessageA,
PlainTextMessageB,

SendingFeatureSetSelector,
SMTPServer,
SMTPUserName,
SMTPPassword,
EnableSchedule,
StartDateTime,
LastRunOn     , 
SMTPDelaySeconds,
EnableBadEmailFormat,
DisableEmailFilter,
WrappingCharacters,

EmailLogFileAddress,
EmailLogFileAddress2,
EmailLogFileAddress3,
EmailLogFile
from tbl_campaigns
Where tbl_campaigns.CampaignID=@CampaignID
	RETURN