

CREATE PROCEDURE [dbo].[proc_ObjectsInsert]
(
	@ObjectID int = NULL output,
	@ObjectType int = NULL,
	@Name varchar(200) = NULL,
	@IsEditable bit = NULL,
	@IsHidden bit = NULL,
	@IsMandatory bit = NULL,
	@PageNo int = NULL,
	@PositionX float = NULL,
	@PositionY float = NULL,
	@MaxHeight float = NULL,
	@MaxWidth float = NULL,
	@MaxCharacters float = NULL,
	@RotationAngle float = NULL,
	@IsFontCustom bit = NULL,
	@IsFontNamePrivate bit = NULL,
	@FontName varchar(200) = NULL,
	@FontSize float = NULL,
	@FontStyleID int = NULL,
	@IsBold bit = NULL,
	@IsItalic bit = NULL,
	@Allignment int = NULL,
	@VAlignment int = NULL,
	@Indent float = NULL,
	@IsUnderlinedText bit = NULL,
	@ColorType int = NULL,
	@ColorStyleID int = NULL,
	@PalleteID int = NULL,
	@ColorName varchar(50) = NULL,
	@ColorC int = NULL,
	@ColorM int = NULL,
	@ColorY int = NULL,
	@ColorK int = NULL,
	@Tint int = NULL,
	@IsSpotColor bit = NULL,
	@SpotColorName varchar(150) = NULL,
	@ContentString varchar(2000) = NULL,
	@ContentCaseType int = NULL,
	@ProductID int = NULL,
	@DisplayOrderPdf int = NULL,
	@DisplayOrderTxtControl int = NULL,
	@IsRequireNumericValue bit = NULL,
	@RColor int = NULL,
	@GColor int = NULL,
	@BColor int = NULL,
	@isSide2Object bit = NULL,
	@LineSpacing float = NULL,
	@ProductPageId int = NULL,
	@ParentId int = NULL,
	@OffsetX float = NULL,
	@OffsetY float = NULL,
	@IsNewLine bit = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	INSERT
	INTO [Objects]
	(
		[ObjectType],
		[Name],
		[IsEditable],
		[IsHidden],
		[IsMandatory],
		[PageNo],
		[PositionX],
		[PositionY],
		[MaxHeight],
		[MaxWidth],
		[MaxCharacters],
		[RotationAngle],
		[IsFontCustom],
		[IsFontNamePrivate],
		[FontName],
		[FontSize],
		[FontStyleID],
		[IsBold],
		[IsItalic],
		[Allignment],
		[VAlignment],
		[Indent],
		[IsUnderlinedText],
		[ColorType],
		[ColorStyleID],
		[PalleteID],
		[ColorName],
		[ColorC],
		[ColorM],
		[ColorY],
		[ColorK],
		[Tint],
		[IsSpotColor],
		[SpotColorName],
		[ContentString],
		[ContentCaseType],
		[ProductID],
		[DisplayOrderPdf],
		[DisplayOrderTxtControl],
		[IsRequireNumericValue],
		[RColor],
		[GColor],
		[BColor],
		[isSide2Object],
		[LineSpacing],
		[ProductPageId],
		[ParentId],
		[OffsetX],
		[OffsetY],
		[IsNewLine]
	)
	VALUES
	(
		@ObjectType,
		@Name,
		@IsEditable,
		@IsHidden,
		@IsMandatory,
		@PageNo,
		@PositionX,
		@PositionY,
		@MaxHeight,
		@MaxWidth,
		@MaxCharacters,
		@RotationAngle,
		@IsFontCustom,
		@IsFontNamePrivate,
		@FontName,
		@FontSize,
		@FontStyleID,
		@IsBold,
		@IsItalic,
		@Allignment,
		@VAlignment,
		@Indent,
		@IsUnderlinedText,
		@ColorType,
		@ColorStyleID,
		@PalleteID,
		@ColorName,
		@ColorC,
		@ColorM,
		@ColorY,
		@ColorK,
		@Tint,
		@IsSpotColor,
		@SpotColorName,
		@ContentString,
		@ContentCaseType,
		@ProductID,
		@DisplayOrderPdf,
		@DisplayOrderTxtControl,
		@IsRequireNumericValue,
		@RColor,
		@GColor,
		@BColor,
		@isSide2Object,
		@LineSpacing,
		@ProductPageId,
		@ParentId,
		@OffsetX,
		@OffsetY,
		@IsNewLine
	)

	SET @Err = @@Error

	SELECT @ObjectID = SCOPE_IDENTITY()

	RETURN @Err
END