CREATE PROCEDURE dbo.sp_Activity_Get_AllActivityTypes
	
AS
	SELECT tbl_activitytype.ActivityTypeID,tbl_activitytype.ActivityName,tbl_activitytype.ActivityDescription,tbl_activitytype.ActivityColor From tbl_activitytype
	RETURN