
CREATE PROCEDURE [dbo].[sp_costcentre_update_userdefine]
(@IsPrintOnJobCard bit,
@IsScheduleable bit,
@QuantityQuestionDefaultValue varchar(150),
@TimeRunSpeed float,
@TimeNoOfPasses int,
@TimeQuestionDefaultValue float,
@ItemDescription text,
@ID int,
@Name varchar(100),
@Description text,
@Type int,

@LastModifiedBy int,
@MinimumCost float,
@SetupCost float,
@SetupTime float,
@DefaultVA float,
@CodeFileName varchar(100),
@NominalCode int,
@CompletionTime int,
@HeaderCode text,
@MiddleCode text,
@FooterCode text,
@StrCostPlantParsed text,
@strCostPlantUnParsed text,
@strCostLabourParsed text,
@strCostLabourUnParsed text,
@strCostMaterialParsed text,
@strCostMaterialUnParsed text,
@strPricePlantParsed text,
@strPricePlantUnParsed text,
@strPriceLabourParsed text,
@strPriceLabourUnParsed text,
@strPriceMaterialParsed text,
@strPriceMaterialUnParsed text,
@HourlyCharge float,
@OverHeadRate float,
@CostPerThousand float,
@PreferredSupplier int,
@strActualCostPlantParsed text,
@strActualCostPlantUnParsed text,
@strActualCostLabourParsed text,
@strActualCostLabourUnParsed text,
@strActualCostMaterialParsed text,
@strActualCostMaterialUnParsed text,
@strTimeParsed text,
@strTimeUnParsed text,
@IsDisabled bit,
@IsDirectCost bit,
@SetupSpoilage float,
@RunningSpoilage float,
@CalculationMethodType int,
@NoOfHours int,
@PerHourCost float,
@PerHourPrice float,
@UnitQuantity int,
@QuantitySourceType int,
@QuantityVariableID int,
@QuantityQuestionString text,
@QuantityCalculationString text,
@CostPerUnitQuantity float,
@PricePerUnitQuantity float,
@TimePerUnitQuantity float,
@TimeSourceType int,
@TimeVariableID int,
@TimeQuestionString text,
@TimeCalculationString text,
@Priority float,
@CostQuestionString varchar(150),
@CostDefaultValue float,
@PriceQuestionString varchar(150),
@PriceDefaultValue float,
@EstimatedTimeQuestionString text,
@EstimatedTimeDefaultValue float,
@Sequence int,
@CompleteCode text)
AS
update tbl_costcentres set IsPrintOnJobCard=@IsPrintOnJobCard,IsScheduleable=@IsScheduleable,QuantityQuestionDefaultValue=@QuantityQuestionDefaultValue,
TimeRunSpeed=@TimeRunSpeed,TimeNoOfPasses=@TimeNoOfPasses,TimeQuestionDefaultValue=@TimeQuestionDefaultValue,
ItemDescription=@ItemDescription,CompleteCode=@CompleteCode,Name=@Name,Description=@Description,Type=@Type,LastModifiedBy=@LastModifiedBy,
MinimumCost=@MinimumCost,SetupCost=@SetupCost,SetupTime=@SetupTime,DefaultVAID=@DefaultVA,CodeFileName=@CodeFileName,
nominalCode=@NominalCode,CompletionTime=@CompletionTime,HeaderCode=@HeaderCode,MiddleCode=@MiddleCode,FooterCode=@FooterCode,
strCostPlantParsed=@strCostPlantParsed,strCostPlantUnParsed=@strCostPlantUnParsed,strCostLabourParsed=@strCostLabourParsed,
strCostLabourUnParsed=@strCostLabourUnParsed,strCostMaterialParsed=@strCostMaterialParsed,strCostMaterialUnParsed=@strCostMaterialUnParsed,
strPricePlantParsed=@strPricePlantParsed,strPricePlantUnParsed=@strPricePlantUnParsed,strPriceLabourParsed=@strPriceLabourParsed,
strPriceLabourUnParsed=@strPriceLabourUnParsed,strPriceMaterialParsed=@strPriceMaterialParsed,strPriceMaterialUnParsed=@strPriceMaterialUnParsed,
HourlyCharge=@HourlyCharge,OverHeadRate=@OverHeadRate,CostPerThousand=@CostPerThousand,PreferredSupplierID=@PreferredSupplier,
strActualCostPlantParsed=@strActualCostPlantParsed,strActualCostPlantUnParsed=@strActualCostPlantUnParsed,
strActualCostLabourParsed=@strActualCostLabourParsed,strActualCostLabourUnParsed=@strActualCostLabourUnParsed,
strActualCostMaterialParsed=@strActualCostMaterialParsed,strActualCostMaterialUnParsed=@strActualCostMaterialUnParsed,
strTimeParsed=@strTimeParsed,strTimeUnParsed=@strTimeUnParsed,IsDisabled=@IsDisabled,IsDirectCost=@IsDirectCost,SetupSpoilage=@SetupSpoilage,
RunningSpoilage=@RunningSpoilage,CalculationMethodType=@CalculationMethodType,NoOfHours=@NoOfHours,PerHourCost=@PerHourCost,
PerHourPrice=@PerHourPrice,UnitQuantity=@UnitQuantity,QuantitySourceType=@QuantitySourceType,QuantityVariableID=@QuantityVariableID,
QuantityQuestionString=@QuantityQuestionString,QuantityCalculationString=@QuantityCalculationString,CostPerUnitQuantity=@CostPerUnitQuantity,
PricePerUnitQuantity=@PricePerUnitQuantity,TimePerUnitQuantity=@TimePerUnitQuantity,TimeSourceType=@TimeSourceType,TimeVariableID=@TimeVariableID,
TimeQuestionString=@TimeQuestionString,TimeCalculationString=@TimeCalculationString,Priority=@Priority,CostQuestionString=@CostQuestionString,
CostDefaultValue=@CostDefaultValue,PriceQuestionString=@PriceQuestionString,PriceDefaultValue=@PriceDefaultValue,
EstimatedTimeQuestionString=@EstimatedTimeQuestionString,EstimatedTimeDefaultValue=@EstimatedTimeDefaultValue,Sequence=@Sequence,
isFromMIS = 0
where CostCentreID=@ID
         RETURN