
CREATE PROCEDURE [dbo].[sp_costcentre_insert_userdefine]
(@IsPrintOnJobCard bit,
@IsScheduleable bit,
@QuantityQuestionDefaultValue varchar(150),
@TimeRunSpeed float,
@TimeNoOfPasses int,
@TimeQuestionDefaultValue float,
@SystemTypeID int,
@SystemSiteID int,
@ItemDescription text,
@ID int,
@Name varchar(50),
@Description text,
@Type int,
@CreatedBy varchar(50),
@LastModifiedBy varchar(50),
@MinimumCost float,
@SetupCost float,
@SetupTime float,
@DefaultVA float,
@CodeFileName varchar(50),
@NominalCode int,
@CompletionTime int,
@HeaderCode text,
@MiddleCode text,
@FooterCode text,
@StrCostPlantParsed text,
@strCostPlantUnParsed text,
@strCostLabourParsed text,
@strCostLabourUnParsed text,
@strCostMaterialParsed text,
@strCostMaterialUnParsed text,
@strPricePlantParsed text,
@strPricePlantUnParsed text,
@strPriceLabourParsed text,
@strPriceLabourUnParsed text,
@strPriceMaterialParsed text,
@strPriceMaterialUnParsed text,
@HourlyCharge float,
@OverHeadRate float,
@CostPerThousand float,
@CreationDate datetime,
@PreferredSupplier int,
@strActualCostPlantParsed text,
@strActualCostPlantUnParsed text,
@strActualCostLabourParsed text,
@strActualCostLabourUnParsed text,
@strActualCostMaterialParsed text,
@strActualCostMaterialUnParsed text,
@strTimeParsed text,
@strTimeUnParsed text,
@IsDisabled bit,
@IsDirectCost bit,
@SetupSpoilage float,
@RunningSpoilage float,
@CalculationMethodType int,
@NoOfHours int,
@PerHourCost float,
@PerHourPrice float,
@UnitQuantity int,
@QuantitySourceType int,
@QuantityVariableID int,
@QuantityQuestionString text,
@QuantityCalculationString text,
@CostPerUnitQuantity float,
@PricePerUnitQuantity float,
@TimePerUnitQuantity float,
@TimeSourceType int,
@TimeVariableID int,
@TimeQuestionString text,
@TimeCalculationString text,
@Priority float,
@CostQuestionString varchar(150),
@CostDefaultValue float,
@PriceQuestionString varchar(150),
@PriceDefaultValue float,
@EstimatedTimeQuestionString text,
@EstimatedTimeDefaultValue float,
@Sequence int,
@CompleteCode text
)
AS
insert into tbl_costcentres (IsPrintOnJobCard,IsScheduleable,QuantityQuestionDefaultValue,TimeRunSpeed,TimeNoOfPasses,
TimeQuestionDefaultValue,SystemTypeID,SystemSiteID,ItemDescription,Name,Description,Type,CreatedBy,
LastModifiedBy,MinimumCost,SetupCost,SetupTime,DefaultVAID,CodeFileName,nominalCode,CompletionTime,
HeaderCode,MiddleCode,FooterCode,strCostPlantParsed,strCostPlantUnParsed,strCostLabourParsed,strCostLabourUnParsed,
strCostMaterialParsed,strCostMaterialUnParsed,strPricePlantParsed,strPricePlantUnParsed,strPriceLabourParsed,
strPriceLabourUnParsed,strPriceMaterialParsed,strPriceMaterialUnParsed,HourlyCharge,OverHeadRate,
CostPerThousand,CreationDate,PreferredSupplierID,strActualCostPlantParsed,strActualCostPlantUnParsed,
strActualCostLabourParsed,strActualCostLabourUnParsed,strActualCostMaterialParsed,strActualCostMaterialUnParsed,
strTimeParsed,strTimeUnParsed,IsDisabled,IsDirectCost,SetupSpoilage,RunningSpoilage,CalculationMethodType,
NoOfHours,PerhourCost,PerHourPrice,UnitQuantity,QuantitySourceType,QuantityVariableID,QuantityQuestionString,
QuantityCalculationString,CostPerUnitQuantity,PricePerUnitQuantity,TimePerUnitQuantity,TimeSourceType,
TimeVariableID,TimeQuestionString,TimeCalculationString,Priority,CostQuestionString,CostDefaultValue,
PriceQuestionString,PriceDefaultValue,EstimatedTimeQuestionString,EstimatedTimeDefaultValue,Sequence,
CompleteCode,FlagID, CompanyID,isFromMIS) values
(@IsPrintOnJobCard,@IsScheduleable,@QuantityQuestionDefaultValue,@TimeRunSpeed,
@TimeNoOfPasses,@TimeQuestionDefaultValue,@SystemTypeID,@SystemSiteID,@ItemDescription,
@Name,@Description,@Type,@CreatedBy, @LastModifiedBy, @MinimumCost, @SetupCost,@SetupTime,
@DefaultVA,@CodeFileName,@NominalCode,@CompletionTime,@HeaderCode,@MiddleCode,@FooterCode,
@StrCostPlantParsed,@strCostPlantUnParsed,@strCostLabourParsed,@strCostLabourUnParsed,
@strCostMaterialParsed,@strCostMaterialUnParsed,@strPricePlantParsed,@strPricePlantUnParsed,
@strPriceLabourParsed,@strPriceLabourUnParsed,@strPriceMaterialParsed,@strPriceMaterialUnParsed,
@HourlyCharge,@OverHeadRate,@CostPerThousand,@CreationDate,@PreferredSupplier,
@strActualCostPlantParsed,@strActualCostPlantUnParsed,@strActualCostLabourParsed,
@strActualCostLabourUnParsed,@strActualCostMaterialParsed,@strActualCostMaterialUnParsed,
@strTimeParsed,@strTimeUnParsed,@IsDisabled,@IsDirectCost,@SetupSpoilage,@RunningSpoilage,
@CalculationMethodType,@NoOfHours,@PerHourCost,@PerHourPrice,@UnitQuantity,@QuantitySourceType,
@QuantityVariableID,@QuantityQuestionString,@QuantityCalculationString,@CostPerUnitQuantity,
@PricePerUnitQuantity,@TimePerUnitQuantity,@TimeSourceType,@TimeVariableID,@TimeQuestionString,
@TimeCalculationString,@Priority,@CostQuestionString,@CostDefaultValue,@PriceQuestionString,
@PriceDefaultValue,@EstimatedTimeQuestionString,@EstimatedTimeDefaultValue,@Sequence,
@CompleteCode,1,2,0);
                                                           
         RETURN select SCOPE_IDENTITY() --@ID