CREATE PROCEDURE dbo.sp_clickchargeZone_insert
(
         @MethodID int,
         @From1 int,
         @To1 int,
         @Sheets1 int,
         @SheetCost1 float,
         @From2 int,
         @To2 int,
         @Sheets2 int,
         @SheetCost2 float,
         @From3 int,
         @To3 int,
         @Sheets3 int,
         @SheetCost3 float,
         @From4 int,
         @To4 int,
         @Sheets4 int,
         @SheetCost4 float,
         @From5 int,
         @To5 int,
         @Sheets5 int,
         @SheetCost5 float,
         @From6 int,
         @To6 int,
         @Sheets6 int,
         @SheetCost6 float,
         @From7 int,
         @To7 int,
         @Sheets7 int,
         @SheetCost7 float,
         @From8 int,
         @To8 int,
         @Sheets8 int,
         @SheetCost8 float,
         @From9 int,
         @To9 int,
         @Sheets9 int,
         @SheetCost9 float,
         @From10 int,
         @To10 int,
         @Sheets10 int,
         @SheetCost10 float,
         @From11 int,
         @To11 int,
         @Sheets11 int,
         @SheetCost11 float,
         @From12 int,
         @To12 int,
         @Sheets12 int,
         @SheetCost12 float,
         @From13 int,
         @To13 int,
         @Sheets13 int,
         @SheetCost13 float,
         @From14 int,
         @To14 int,
         @Sheets14 int,
         @SheetCost14 float,
         @From15 int,
         @To15 int,
         @Sheets15 int,
         @SheetCost15 float,
         @isaccumulativecharge bit,
         @IsRoundUp bit,
         @SheetPrice1 float,
         @SheetPrice2 float,
         @SheetPrice3 float,
         @SheetPrice4 float,
         @SheetPrice5 float,
         @SheetPrice6 float,
         @SheetPrice7 float,
         @SheetPrice8 float,
         @SheetPrice9 float,
         @SheetPrice10 float,
         @SheetPrice11 float,
         @SheetPrice12 float,
         @SheetPrice13 float,
         @SheetPrice14 float,
         @SheetPrice15 float,
         @TimePerHour float
         )
AS
insert into tbl_machine_clickchargezone (MethodID,From1,To1,Sheets1,SheetCost1,
         From2,To2,Sheets2,SheetCost2,From3,To3,Sheets3,SheetCost3,From4,To4,Sheets4,SheetCost4,From5,To5,
         Sheets5,SheetCost5,From6,To6,Sheets6,SheetCost6,From7,To7,Sheets7,SheetCost7,From8,To8,Sheets8,
         SheetCost8,From9,To9,Sheets9,SheetCost9,From10,To10,Sheets10,SheetCost10,From11,To11,Sheets11,
         SheetCost11,From12,To12,Sheets12,SheetCost12,From13,To13,Sheets13,SheetCost13,From14,To14,Sheets14,
         SheetCost14,From15,To15,Sheets15,SheetCost15,isaccumulativecharge,IsRoundUp,SheetPrice1,SheetPrice2,SheetPrice3,SheetPrice4,SheetPrice5,SheetPrice6,SheetPrice7,SheetPrice8,SheetPrice9,SheetPrice10,SheetPrice11,SheetPrice12,SheetPrice13,SheetPrice14,SheetPrice15,
         TimePerHour ) VALUES (
         @MethodID,@From1,@To1,@Sheets1,@SheetCost1,@From2,@To2,@Sheets2,@SheetCost2,@From3,@To3,@Sheets3,@SheetCost3,
         @From4,@To4,@Sheets4,@SheetCost4,@From5,@To5,@Sheets5,@SheetCost5,@From6,@To6,@Sheets6,@SheetCost6,
         @From7,@To7,@Sheets7,@SheetCost7,@From8,@To8,@Sheets8,@SheetCost8,@From9,@To9,@Sheets9,@SheetCost9,
         @From10,@To10,@Sheets10,@SheetCost10,@From11,@To11,@Sheets11,@SheetCost11,@From12,@To12,@Sheets12,@SheetCost12,
         @From13,@To13,@Sheets13,@SheetCost13,@From14,@To14,@Sheets14,@SheetCost14,@From15,@To15,@Sheets15,@SheetCost15,@isaccumulativecharge,@IsRoundUp,@SheetPrice1,@SheetPrice2,@SheetPrice3,@SheetPrice4,@SheetPrice5,@SheetPrice6,@SheetPrice7,@SheetPrice8,@SheetPrice9,@SheetPrice10,@SheetPrice11,@SheetPrice12,@SheetPrice13,@SheetPrice14,@SheetPrice15,
         @TimePerHour);
        Select @@Identity as LookUpID	RETURN