CREATE PROCEDURE dbo.sp_FinishedGoods_Insert_FinishedGood

	(
		@ItemID int,
		@Description1 ntext,
		@Description2 ntext,
		@Description3 ntext,
		@Thumbnail image,
		@Image image,
		@IsForWeb smallint,
		@InStock int,
		@ContentType varchar(50),
		@Allocated int,
		@IsShowStockOnWeb smallint,
		@ThresholdLevel int,
		@ThresholdProductionQuantity int,
		@Location varchar(50),
		@SupplierID int,
		@SupplierCode varchar(50),
		@ProductCode varchar(50),
		@NominalCode varchar(50),
		@BarCode varchar(50),
		@FinishedGoodCode varchar(50),
		@TaxID int,
		@RangeThresholdLevel int,
		@FromThresholdDate datetime,
		@ToThresholdDate datetime,
		@Cost float,
		@UnitQuantity int,
		@PackQuantity int,
		@RangeThresholdLevel1 int,
		@FromThresholdDate1 datetime,
		@ToThresholdDate1 datetime,
		@RangeThresholdLevel2 int,
		@FromThresholdDate2 datetime,
		@ToThresholdDate2 datetime,
		@LockedBy int,
		@FinishedGoodType smallint,
		@FinishedGoodStockItemId int,
		@SystemSiteID int,
		@File1 image,
		@File2 image,
		@IsShowAllocatedStockOnWeb smallint,
		@IsShowPriceOnWeb smallint,
		@IsShowFreeStockOnWeb smallint,
@IsDisabled smallint,
@CreatedBy int
	)

AS
	/* SET NOCOUNT ON */
	
	Insert into tbl_finishedgoods(ItemID,Thumbnail,[Image],ContentType,Description1,
	Description2,Description3,LockedBy,IsForWeb,InStock,Allocated,IsShowStockOnWeb,
	ThresholdLevel,ThresholdProductionQuantity,Location,FinishedGoodType,
	FinishedGoodStockItemId,SupplierID,SupplierCode,ProductCode,NominalCode,BarCode,
	FinishedGoodCode,TaxID,RangeThresholdLevel,FromThresholdDate,ToThresholdDate,Cost,
	UnitQuantity,PackQuantity,RangeThresholdLevel1,FromThresholdDate1,ToThresholdDate1,
	RangeThresholdLevel2,FromThresholdDate2,ToThresholdDate2,SystemSiteID,File1,File2,
	IsShowAllocatedStockOnWeb,IsShowPriceOnWeb,IsShowFreeStockOnWeb,IsDisabled,CreatedBy ) 
	Values(@ItemID,@Thumbnail,@Image,@ContentType,@Description1,@Description2,
	@Description3,@LockedBy,@IsForWeb,@InStock,@Allocated,@IsShowStockOnWeb,
	@ThresholdLevel,@ThresholdProductionQuantity,@Location,@FinishedGoodType,
	@FinishedGoodStockItemId,@SupplierID,@SupplierCode,@ProductCode,@NominalCode,
	@BarCode,@FinishedGoodCode,@TaxID,@RangeThresholdLevel,@FromThresholdDate,
	@ToThresholdDate,@Cost,@UnitQuantity,@PackQuantity,@RangeThresholdLevel1,
	@FromThresholdDate1,@ToThresholdDate1,@RangeThresholdLevel2,@FromThresholdDate2,
	@ToThresholdDate2,@SystemSiteID,@File1,@File2,@IsShowAllocatedStockOnWeb,@IsShowPriceOnWeb,
	@IsShowFreeStockOnWeb,@IsDisabled, @CreatedBy);select @@Identity as FGID
	
	RETURN