
create PROCEDURE [dbo].[sp_ItemSection_Update_Section]
(
	@PressSpeed1 int,
	@PressSpeed2 int,
	@PressSpeed3 int,
	@PrintSheetQty1 int,
	@PrintSheetQty2 int,
	@PrintSheetQty3 int,
	@PressHourlyCharge float,
	@PrintChargeExMakeReady1 float,
	@PrintChargeExMakeReady2 float,
	@PrintChargeExMakeReady3 float,
	@PaperGsm float,
	@PaperPackPrice float,
	@PTVRows int,
	@PTVColoumns int,
	@PaperWeight1 float,
	@PaperWeight2 float,
	@PaperWeight3 float,
	@FinishedItemQty1 int,
	@FinishedItemQty2 int,
	@FinishedItemQty3 int,
	@isWorknTurn smallint,
	@isWorkntumble smallint,
	@IsMakeReadyUsed smallint,
	@SectionType smallint,
	@ItemSectionID int,
	@SectionNo int,
	@ItemSectionName varchar(50),
	@IsMainSection smallint,
	@ItemID int,
	@Qty1 int,
	@Qty2 int,
	@Qty3 int,
	@BaseCharge1 float,
	@BaseCharge2 float,
	@Basecharge3 float,
	@RunOnQty int,
	@SectionSizeID int,
	@IsSectionSizeCustom smallint,
	@SectionSizeHeight float,
	@SectionSizeWidth float,
	@ItemSizeID int,
	@IsItemSizeCustom smallint,
	@ItemSizeHeight float,
	@ItemSizeWidth float,
	@GuillotineID int,
	@IncludeGutter smallint,
	@PressID int,
	@FilmID int,
	@PlateID int,
	@ItemGutterHorizontal float,
	@ItemGutterVertical float,
	@IsPressrestrictionApplied smallint,
	@IsDoubleSided smallint,
	@IsWashup smallint,
	@PrintViewLayoutLandScape int,
	@PrintViewLayoutPortrait int,
	@PrintViewLayout int,
	@EstimateForWholePacks smallint,
	@IsFirstTrim smallint,
	@IsSecondTrim smallint,
	@PaperQty int,
	@ImpressionQty1 int,
	@ImpressionQty2 int,
	@ImpressionQty3 int,
	@FilmQty int,
	@IsFilmSupplied smallint,
	@IsPlateSupplied smallint,
	@PlateQty int,
	@WashupQty int,
	@MakeReadyQty int,
	@IsPaperCoated smallint,
	@GuillotineFirstCut int,
	@GuillotineSecondCut int,
	@AdditionalFilmUsed int,
	@AdditionalPlateUsed int,
	@IsFilmUsed smallint,
	@IsPlateUsed smallint,
	@NoofUniqueInks int,
	@WizardRunMode smallint,
	@Qty1Profit float,
	@Qty2Profit float,
	@Qty3Profit float,
	@RunOnBaseCharge float,
	@RunOnProfit float,
	@IsMultipleQty smallint,
	@IsRunOnQty smallint,
	@OverAllPtv int,
	@ItemPTV int,
	@PaperID int,
	@RunningSpoilage int,
	@RunningSpoilageValue int,
	@SetUpSpoilage float,
	@IsPaperSupplied smallint,
	@ProfileID int,
	@SelectedPressCalculationMethodID int,
	@QuestionQueue image,
	@StockQueue image,
	@InputQueue image,
	@CostCentreQueue image,
	@SectionNotes text,
	@Side1Inks int,
	@Side2Inks int,
	@ImageType int,
	@GuillotineQty1BundlesFirstTrim int,
	@GuillotineQty2BundlesFirstTrim int,
	@GuillotineQty3BundlesFirstTrim int,
	@GuillotineQty1BundlesSecondTrim int,
	@GuillotineQty2BundlesSecondTrim int,
	@GuillotineQty3BundlesSecondTrim int,


	@GuillotineQty1FirstTrimCuts int,
	@GuillotineQty2FirstTrimCuts int,
	@GuillotineQty3FirstTrimCuts int,
 	@GuillotineQty1SecondTrimCuts int,
	@GuillotineQty2SecondTrimCuts int,
	@GuillotineQty3SecondTrimCuts int,
	@GuillotineQty1TotalsCuts int,
	@GuillotineQty2TotalsCuts int,
	@GuillotineQty3TotalsCuts  int,
	
	@WebClylinderHeight float ,
	@WebCylinderWidth float,
	@WebCylinderId int,
	@WebPaperLengthWithSp float,
	@WebPaperLengthWoSp float,
	@WebReelMakereadyQty int,
	@WebStockPaperCost float,
	@WebSpoilageType smallint,
	@PressPassesQty int,
	@PrintingType int,
	@PadsLeafQty	int,
	@PadsQuantity	int	


)
AS
	update tbl_item_sections set PressSpeed1=@PressSpeed1,PressSpeed2=@PressSpeed2,PressSpeed3=@PressSpeed3,PrintSheetQty1=@PrintSheetQty1,PrintSheetQty2=@PrintSheetQty2,PrintSheetQty3=@PrintSheetQty3,PressHourlyCharge=@PressHourlyCharge,PrintChargeExMakeReady1=@PrintChargeExMakeReady1,PrintChargeExMakeReady2=@PrintChargeExMakeReady2,PrintChargeExMakeReady3=@PrintChargeExMakeReady3,PaperGsm=@PaperGsm,PaperPackPrice=@PaperPackPrice,PTVRows=@PTVRows,PTVColoumns=@PTVColoumns,PaperWeight1=@PaperWeight1,PaperWeight2=@PaperWeight2,PaperWeight3=@PaperWeight3,FinishedItemQty1=@FinishedItemQty1,FinishedItemQty2=@FinishedItemQty2,FinishedItemQty3=@FinishedItemQty3,isWorkntumble=@isWorkntumble,isWorknTurn=@isWorknTurn,IsMakeReadyUsed=@IsMakeReadyUsed,SectionType=@SectionType,SectionNo=@SectionNo,SectionName=@ItemSectionName,IsMainSection=@IsMainSection,ItemID=@ItemID,Qty1=@Qty1,Qty2=@Qty2,Qty3=@Qty3,BaseCharge1=@BaseCharge1,BaseCharge2=@BaseCharge2,Basecharge3=@Basecharge3,RunOnQty=@RunOnQty,SectionSizeID=@SectionSizeID,IsSectionSizeCustom=@IsSectionSizeCustom,SectionSizeHeight=@SectionSizeHeight,SectionSizeWidth=@SectionSizeWidth,ItemSizeID=@ItemSizeID,IsItemSizeCustom=@IsItemSizeCustom,ItemSizeHeight=@ItemSizeHeight,ItemSizeWidth=@ItemSizeWidth,GuillotineID=@GuillotineID,IncludeGutter=@IncludeGutter,PressID=@PressID,FilmID=@FilmID,PlateID=@PlateID,ItemGutterHorizontal=@ItemGutterHorizontal,ItemGutterVertical=@ItemGutterVertical,IsPressrestrictionApplied=@IsPressrestrictionApplied,IsDoubleSided=@IsDoubleSided,IsWashup=@IsWashup,PrintViewLayoutLandScape=@PrintViewLayoutLandScape,PrintViewLayoutPortrait=@PrintViewLayoutPortrait,PrintViewLayout=@PrintViewLayout,QuestionQueue=@QuestionQueue,StockQueue=@StockQueue,InputQueue=@InputQueue,CostCentreQueue=@CostCentreQueue ,SectionNotes=@SectionNotes,
            EstimateForWholePacks=@EstimateForWholePacks,IsFirstTrim=@IsFirstTrim,IsSecondTrim=@IsSecondTrim,PaperQty=@PaperQty,ImpressionQty1=@ImpressionQty1,ImpressionQty2=@ImpressionQty2,ImpressionQty3=@ImpressionQty3,FilmQty=@FilmQty,IsFilmSupplied=@IsFilmSupplied,IsPlateSupplied=@IsPlateSupplied,Side1PlateQty=@PlateQty,WashupQty=@WashupQty,MakeReadyQty=@MakeReadyQty,IsPaperCoated=@IsPaperCoated,GuillotineFirstCut=@GuillotineFirstCut,GuillotineSecondCut=@GuillotineSecondCut,AdditionalFilmUsed=@AdditionalFilmUsed,AdditionalPlateUsed=@AdditionalPlateUsed,IsFilmUsed=@IsFilmUsed,IsPlateUsed=@IsPlateUsed,NoofUniqueInks=@NoofUniqueInks,WizardRunMode=@WizardRunMode,Qty1Profit=@Qty1Profit,Qty2Profit=@Qty2Profit,Qty3Profit=@Qty3Profit,RunOnBaseCharge=@RunOnBaseCharge,RunOnProfit=@RunOnProfit,IsMultipleQty=@IsMultipleQty,IsRunOnQty=@IsRunOnQty,OverAllPTV=@OverAllPtv,ItemPTV=@ItemPTV,STockItemID1=@PaperID,RunningSpoilage=@RunningSpoilage,RunningSpoilageValue=@RunningSpoilageValue,SetUpSpoilage=@SetUpSpoilage,IsPaperSupplied=@IsPaperSupplied,Side1Inks=@Side1Inks,Side2Inks=@Side2Inks,ProfileID=@ProfileID,SelectedPressCalculationMethodID=@SelectedPressCalculationMethodID ,ImageType=@ImageType ,
	GuillotineQty1BundlesFirstTrim  = @GuillotineQty1BundlesFirstTrim ,GuillotineQty2BundlesFirstTrim  = @GuillotineQty2BundlesFirstTrim ,GuillotineQty3BundlesFirstTrim  = @GuillotineQty3BundlesFirstTrim ,GuillotineQty1BundlesSecondTrim  = @GuillotineQty1BundlesSecondTrim , GuillotineQty2BundlesSecondTrim  = @GuillotineQty2BundlesSecondTrim,GuillotineQty3BundlesSecondTrim  = @GuillotineQty3BundlesSecondTrim ,
	GuillotineQty1FirstTrimCuts=@GuillotineQty1FirstTrimCuts, GuillotineQty2FirstTrimCuts=@GuillotineQty2FirstTrimCuts, GuillotineQty3FirstTrimCuts=@GuillotineQty3FirstTrimCuts, GuillotineQty1SecondTrimCuts=@GuillotineQty1SecondTrimCuts, GuillotineQty2SecondTrimCuts=@GuillotineQty2SecondTrimCuts, GuillotineQty3SecondTrimCuts=@GuillotineQty3SecondTrimCuts,  GuillotineQty1TotalsCuts=@GuillotineQty1TotalsCuts, GuillotineQty2TotalsCuts=@GuillotineQty2TotalsCuts, GuillotineQty3TotalsCuts =@GuillotineQty3TotalsCuts ,
	WebClylinderHeight = @WebClylinderHeight,WebCylinderWidth =@WebCylinderWidth ,	WebCylinderId = @WebCylinderId ,WebPaperLengthWithSp =@WebPaperLengthWithSp ,WebPaperLengthWoSp =@WebPaperLengthWoSp ,	WebReelMakereadyQty =@WebReelMakereadyQty ,WebStockPaperCost =	@WebStockPaperCost ,WebSpoilageType=@WebSpoilageType,
	PressPassesQty=@PressPassesQty,PrintingType =@PrintingType ,PadsLeafQty=@PadsLeafQty,PadsQuantity=@PadsQuantity
	
	 where ItemSectionID=@ItemSectionId
	RETURN