
CREATE PROCEDURE [dbo].[sp_Item_Update_Item]
(
@Tax2 int,
@Tax3 int,
@Qty1Tax2Value float,
@Qty1Tax3Value float,
@Qty2Tax2Value float,
@Qty2Tax3Value float,
@Qty3Tax2Value float,
@Qty3Tax3Value float,
@ItemLastUpdateDateTime datetime,
@IsItemLibraray smallint,
@ItemLibrarayGroupID int,
@IsParagraphDescription smallint,
@EstimateID int,
@Title varchar (50),
@Tax1 int,
@CreatedBy int,
@Status smallint,
@ItemCreationDateTime datetime,
@IsMultipleQty smallint,
@RunOnQty int,
@RunonBaseCharge float,
@RunOnMarkUpID float,
@RunOnMarkUpValue float,
@RunOnNetTotal float,
@Qty1 int,
@Qty2 int,
@Qty3 int,
@Qty1BaseCharge1 float,
@Qty2BaseCharge2 float,
@Qty3BaseCharge3 float, 
@Qty1MarkUpID1 int,
@Qty2MarkUpID2 int,
@Qty3MarkUpID3 int,
@Qty1MarkUp1Value float,
@Qty2MarkUp2Value float,
@Qty3MarkUp3Value float, 
@Qty1NetTotal float,
@Qty2NetTotal float,
@Qty3NetTotal float,
@Qty1Tax1Value float, 
@Qty1MarkUpPercentageValue float,
@Qty2MarkUpPercentageValue float,
@Qty3MarkUpPercentageValue float,
@Qty1GrossTotal float,
@Qty2Tax1Value float,
@Qty2grossTotal float,
@Qty3Tax1Value float,
@Qty3GrossTotal float,
@IsDescriptionLocked smallint,
@EstimateDescriptionTitle1 text,
@EstimateDescriptionTitle2 text,
@EstimateDescriptionTitle3 text,
@EstimateDescriptionTitle4 text,
@EstimateDescriptionTitle5 text,
@EstimateDescriptionTitle6 text,
@EstimateDescriptionTitle7 text,
@EstimateDescriptionTitle8 text,
@EstimateDescriptionTitle9 text,
@EstimateDescriptionTitle10 text,
@EstimateDescription1 text,
@EstimateDescription2 text,
@EstimateDescription3 text,
@EstimateDescription4 text, 
@EstimateDescription5 text,
@EstimateDescription6 text,
@EstimateDescription7 text,
@EstimateDescription8 text,
@EstimateDescription9 text,
@EstimateDescription10 text,
@EstimateDescription text, 
@Qty1Title varchar (50),
@Qty2Title varchar (50),
@Qty3Title varchar (50),
@RunonTitle varchar(50) ,
@AdditionalInformation text,
@Qty2Description text,
@Qty3Description text,
@RunonDescription text,
@RunonPercentageValue float,
@RunonCostCentreProfit float,
@Qty1CostCentreProfit float,
@Qty2CostCentreProfit float,
@Qty3CostCentreProfit  float,
@IsIncludedInPipeLine smallint,
@IsRunOnQty smallint,
@ItemType int,
@NominalCode int,
@ItemID int,
@CostCenterDescriptions image = null,
@DepartmentID int,
@ItemNotes text,
@UpdatedBy	int	,
@LastUpdate	datetime	,
@JobActualStartDateTime	datetime,
@JobActualCompletionDateTime	datetime,
@IsJobCostingDone bit

)
AS

	update tbl_items set Tax2=@Tax2,Tax3=@Tax3,Qty1Tax2Value=@Qty1Tax2Value,Qty1Tax3Value=@Qty1Tax3Value,Qty2Tax2Value=@Qty2Tax2Value,Qty2Tax3Value=@Qty2Tax3Value,Qty3Tax2Value=@Qty3Tax2Value,Qty3Tax3Value=@Qty3Tax3Value,ItemLastUpdateDateTime=@ItemLastUpdateDateTime,IsItemLibraray=@IsItemLibraray,ItemLibrarayGroupID=@ItemLibrarayGroupID,IsParagraphDescription=@IsParagraphDescription,EstimateID=@EstimateID,Title=@Title,Tax1=@Tax1,CreatedBy=@CreatedBy,Status=@Status,ItemCreationDateTime=@ItemCreationDateTime,IsMultipleQty=@IsMultipleQty, 
        RunOnQty=@RunOnQty,RunonBaseCharge=@RunonBaseCharge,RunOnMarkUpID=@RunOnMarkUpID,RunOnMarkUpValue=@RunOnMarkUpValue,RunOnNetTotal=@RunOnNetTotal,Qty1=@Qty1,Qty2=@Qty2,Qty3=@Qty3,Qty1BaseCharge1=@Qty1BaseCharge1,Qty2BaseCharge2=@Qty2BaseCharge2,Qty3BaseCharge3=@Qty3BaseCharge3, 
        Qty1MarkUpID1=@Qty1MarkUpID1,Qty2MarkUpID2=@Qty2MarkUpID2,Qty3MarkUpID3=@Qty3MarkUpID3,Qty1MarkUp1Value=@Qty1MarkUp1Value,Qty2MarkUp2Value=@Qty2MarkUp2Value,Qty3MarkUp3Value=@Qty3MarkUp3Value, 
        Qty1NetTotal=@Qty1NetTotal,Qty2NetTotal=@Qty2NetTotal,Qty3NetTotal=@Qty3NetTotal,Qty1Tax1Value=@Qty1Tax1Value, 
        Qty1MarkUpPercentageValue=@Qty1MarkUpPercentageValue,Qty2MarkUpPercentageValue=@Qty2MarkUpPercentageValue,Qty3MarkUpPercentageValue=@Qty3MarkUpPercentageValue,Qty1GrossTotal=@Qty1GrossTotal,Qty2Tax1Value=@Qty2Tax1Value,Qty2grossTotal=@Qty2grossTotal,Qty3Tax1Value=@Qty3Tax1Value,Qty3GrossTotal=@Qty3GrossTotal,
        IsDescriptionLocked=@IsDescriptionLocked,EstimateDescriptionTitle1=@EstimateDescriptionTitle1,EstimateDescriptionTitle2=@EstimateDescriptionTitle2,EstimateDescriptionTitle3=@EstimateDescriptionTitle3,EstimateDescriptionTitle4=@EstimateDescriptionTitle4,EstimateDescriptionTitle5=@EstimateDescriptionTitle5,EstimateDescriptionTitle6=@EstimateDescriptionTitle6,EstimateDescriptionTitle7=@EstimateDescriptionTitle7,
        EstimateDescriptionTitle8=@EstimateDescriptionTitle8,EstimateDescriptionTitle9=@EstimateDescriptionTitle9,EstimateDescriptionTitle10=@EstimateDescriptionTitle10,EstimateDescription1=@EstimateDescription1,EstimateDescription2=@EstimateDescription2,EstimateDescription3=@EstimateDescription3,EstimateDescription4=@EstimateDescription4, 
        EstimateDescription5=@EstimateDescription5,EstimateDescription6=@EstimateDescription6,EstimateDescription7=@EstimateDescription7,EstimateDescription8=@EstimateDescription8,EstimateDescription9=@EstimateDescription9,EstimateDescription10=@EstimateDescription10,EstimateDescription=@EstimateDescription, 
        Qty1Title=@Qty1Title,Qty2Title=@Qty2Title,Qty3Title=@Qty3Title,RunonTitle=@RunonTitle,
        AdditionalInformation=@AdditionalInformation,Qty2Description=@Qty2Description,Qty3Description=@Qty3Description,RunonDescription=@RunonDescription,RunonPercentageValue=@RunonPercentageValue,RunonCostCentreProfit=@RunonCostCentreProfit,Qty1CostCentreProfit=@Qty1CostCentreProfit,Qty2CostCentreProfit=@Qty2CostCentreProfit,Qty3CostCentreProfit=@Qty3CostCentreProfit ,IsIncludedInPipeLine=@IsIncludedInPipeLine,IsRunOnQty=@IsRunOnQty,
        ItemType = @ItemType,NominalCodeID= @NominalCode ,CostCenterDescriptions = @CostCenterDescriptions,DepartmentID = @DepartmentID,ItemNotes= @ItemNotes,UpdatedBy=@UpdatedBy,LastUpdate=@LastUpdate,JobActualStartDateTime	=@JobActualStartDateTime,JobActualCompletionDateTime=@JobActualCompletionDateTime,
        IsJobCostingDone=@IsJobCostingDone
        where ItemID=@ItemID

	RETURN