CREATE PROCEDURE [dbo].[sp_ItemSection_GET_AllSectionFieldsByItemID]
(
	@ItemID int
)
AS
	SELECT ItemSectionID, 
IsNull(SectionNo,0) as SectionNo, 
IsNull(SectionName,'') as SectionName, 
IsNull(IsMainSection,0) as IsMainSection, 
IsNull(IsMultipleQty,0) as IsMultipleQty, 
IsNull(IsRunOnQty,0) as IsRunOnQty, 
IsNull(ItemID,0) as ItemID, 
IsNull(Qty1,0) as Qty1, 
IsNull(Qty2,0) as Qty2, 
IsNull(Qty3,0) as Qty3, 
IsNull(Qty4,0) as Qty4, 
IsNull(Qty5,0) as Qty5 , 
IsNull(Qty1Profit,0) as Qty1Profit, 
IsNull(Qty2Profit,0) as Qty2Profit, 
IsNull(Qty3Profit,0) as Qty3Profit, 
IsNull(Qty4Profit,0) as Qty4Profit, 
IsNull(Qty5Profit,0) as Qty5Profit, 
IsNull(BaseCharge1,0) as BaseCharge1, 
IsNull(BaseCharge2,0) as BaseCharge2, 
IsNull(Basecharge3,0) as Basecharge3, 
IsNull(BaseCharge4,0) as BaseCharge4,
IsNull(BaseCharge5,0) as BaseCharge5,
IsNull(RunOnQty, 0) as RunOnQty,
IsNull(RunOnBaseCharge, 0) as RunOnBaseCharge,
IsNull(RunonProfit, 0) as RunonProfit ,
IsNull(SectionSizeID, 0) as SectionSizeID,
IsNull(IsSectionSizeCustom, 0) as IsSectionSizeCustom,
IsNull(SectionSizeHeight, 0) as SectionSizeHeight,
IsNull(SectionSizeWidth, 0) as SectionSizeWidth,
IsNull(ItemSizeID, 0) as ItemSizeID,
IsNull(IsItemSizeCustom, 0) as IsItemSizeCustom,
IsNull(ItemSizeHeight, 0) as ItemSizeHeight,
IsNull(ItemSizeWidth, 0) as ItemSizeWidth,
IsNull(GuillotineID, 0) as GuillotineID,
IsNull(IncludeGutter, 0) as IncludeGutter,
IsNull(PressID, 0) as PressID,
IsNull(FilmID, 0) as FilmID,
IsNull(PlateID, 0) as PlateID,
IsNull(ItemGutterHorizontal, 0) as ItemGutterHorizontal ,
IsNull(ItemGutterVertical, 0) as ItemGutterVertical,
IsNull(IsPressrestrictionApplied, 0) as IsPressrestrictionApplied,
IsNull(IsDoubleSided, 0) as IsDoubleSided,
IsNull(IsWashup, 0) as IsWashup,
IsNull(PrintViewLayoutLandScape, 0) as PrintViewLayoutLandScape,
IsNull(PrintViewLayoutPortrait, 0) as PrintViewLayoutPortrait ,
IsNull(PrintViewLayout, 0) as PrintViewLayout,
IsNull(SetupSpoilage, 0) as SetupSpoilage,
IsNull(RunningSpoilage, 0) as RunningSpoilage,
IsNull(RunningSpoilageValue, 0) as RunningSpoilageValue,
IsNull(EstimateForWholePacks, 0) as EstimateForWholePacks,
IsNull(IsFirstTrim, 0) as IsFirstTrim,
IsNull(IsSecondTrim, 0) as IsSecondTrim,
IsNull(PaperQty, 0) as PaperQty,
IsNull(ImpressionQty1,0) as ImpressionQty1,
IsNull(ImpressionQty2, 0) as ImpressionQty2,
IsNull(ImpressionQty3, 0) as ImpressionQty3,
IsNull(ImpressionQty4, 0) as ImpressionQty4,
IsNull(ImpressionQty5, 0) as ImpressionQty5,
IsNull(FilmQty, 0) as FilmQty,
IsNull(IsFilmSupplied, 0) as IsFilmSupplied,
IsNull(IsPlateSupplied, 0) as IsPlateSupplied,
IsNull(IsPaperSupplied, 0) as IsPaperSupplied,
IsNull(WashupQty, 0) as WashupQty,
IsNull(MakeReadyQty, 0) as MakeReadyQty,
IsNull(IsPaperCoated, 0) as IsPaperCoated,
IsNull(GuillotineFirstCut, 0) as GuillotineFirstCut,
IsNull(GuillotineSecondCut, 0) as GuillotineSecondCut,
IsNull(GuillotineCutTime, 0) as GuillotineCutTime,
IsNull(GuillotineQty1BundlesFirstTrim, 0) as GuillotineQty1BundlesFirstTrim,
IsNull(GuillotineQty2BundlesFirstTrim, 0) as GuillotineQty2BundlesFirstTrim,
IsNull(GuillotineQty3BundlesFirstTrim, 0) as GuillotineQty3BundlesFirstTrim,
IsNull(GuillotineQty1BundlesSecondTrim, 0) as GuillotineQty1BundlesSecondTrim,
IsNull(GuillotineQty2BundlesSecondTrim, 0) as GuillotineQty2BundlesSecondTrim,
IsNull(GuillotineQty3BundlesSecondTrim, 0) as GuillotineQty3BundlesSecondTrim,
IsNull(GuillotineQty1FirstTrimCuts, 0) as GuillotineQty1FirstTrimCuts,
IsNull(GuillotineQty2FirstTrimCuts, 0) as GuillotineQty2FirstTrimCuts,
IsNull(GuillotineQty3FirstTrimCuts, 0) as GuillotineQty3FirstTrimCuts,
IsNull(GuillotineQty1SecondTrimCuts, 0) as GuillotineQty1SecondTrimCuts,
IsNull(GuillotineQty2SecondTrimCuts,0) as GuillotineQty2SecondTrimCuts,
IsNull(GuillotineQty3SecondTrimCuts, 0) as GuillotineQty3SecondTrimCuts,
IsNull(GuillotineQty1TotalsCuts, 0) as GuillotineQty1TotalsCuts,
IsNull(GuillotineQty2TotalsCuts, 0) as GuillotineQty2TotalsCuts,
IsNull(GuillotineQty3TotalsCuts, 0) as GuillotineQty3TotalsCuts,
IsNull(AdditionalFilmUsed, 0) as AdditionalFilmUsed,
IsNull(AdditionalPlateUsed, 0) as AdditionalPlateUsed,
IsNull(IsFilmUsed, 0) as IsFilmUsed,
IsNull(IsPlateUsed, 0) as IsPlateUsed,
IsNull(NoofUniqueInks, 0) as NoofUniqueInks,
IsNull(WizardRunMode, 0) as WizardRunMode,
IsNull(OverAllPTV, 0) as OverAllPTV,
IsNull(ItemPTV, 0) as ItemPTV,
IsNull(Side1Inks, 0) as Side1Inks,
IsNull(Side2Inks, 0) as Side2Inks,
IsNull(IsSwingApplied, 0) as IsSwingApplied,
IsNull(SectionType, 0) as SectionType,
IsNull(IsMakeReadyUsed, 0) as IsMakeReadyUsed,
IsNull(isWorknTurn, 0) as isWorknTurn,
IsNull(isWorkntumble, 0) as isWorkntumble,
IsNull(PressSpeed1, 0) as PressSpeed1,
IsNull(PressSpeed2, 0) as PressSpeed2,
IsNull(PressSpeed3, 0) as PressSpeed3,
IsNull(PressSpeed4, 0) as PressSpeed4,
IsNull(PressSpeed5, 0) as PressSpeed5,
IsNull(PrintSheetQty1, 0) as PrintSheetQty1,
IsNull(PrintSheetQty2,0) as PrintSheetQty2,
IsNull( PrintSheetQty3, 0) as PrintSheetQty3,
IsNull(PrintSheetQty4, 0) as PrintSheetQty4,
IsNull(PrintSheetQty5, 0) as PrintSheetQty5,
IsNull(PressHourlyCharge, 0) as PressHourlyCharge,
IsNull(PrintChargeExMakeReady1, 0) as PrintChargeExMakeReady1,
IsNull(PrintChargeExMakeReady2, 0) as PrintChargeExMakeReady2,
IsNull(PrintChargeExMakeReady3, 0) as PrintChargeExMakeReady3,
IsNull(PrintChargeExMakeReady4, 0) as PrintChargeExMakeReady4,
IsNull(PrintChargeExMakeReady5, 0) as PrintChargeExMakeReady5,
IsNull(PaperGsm, 0) as PaperGsm,
IsNull(PaperPackPrice, 0) as PaperPackPrice,
IsNull(PTVRows, 0) as PTVRows,
IsNull(PTVColoumns, 0) as PTVColoumns,
IsNull(PaperWeight1, 0) as PaperWeight1,
IsNull(PaperWeight2, 0) as PaperWeight2,
IsNull(PaperWeight3, 0) as PaperWeight3,
IsNull(PaperWeight4, 0) as PaperWeight4,
IsNull(PaperWeight5, 0) as PaperWeight5,
IsNull(FinishedItemQty1, 0) as FinishedItemQty1,
IsNull(FinishedItemQty2, 0) as FinishedItemQty2,
IsNull(FinishedItemQty3, 0) as FinishedItemQty3,
IsNull(FinishedItemQty4, 0) as FinishedItemQty4,
IsNull(FinishedItemQty5, 0) as FinishedItemQty5,
IsNull(ProfileID, 0) as ProfileID,
IsNull(SelectedPressCalculationMethodID, 0) as SelectedPressCalculationMethodID,
IsNull(SectionNotes, '') as SectionNotes,
IsNull(IsScheduled, 0) as IsScheduled,
IsNull(ImageType, 0) as ImageType,
IsNull(WebClylinderHeight, 0) as WebClylinderHeight,
IsNull(WebCylinderWidth,0) as WebCylinderWidth ,
IsNull( WebCylinderId, 0) as WebCylinderId,
IsNull(WebPaperLengthWithSp, 0) as WebPaperLengthWithSp,
IsNull(WebPaperLengthWoSp, 0) as WebPaperLengthWoSp,
IsNull(WebReelMakereadyQty, 0) as WebReelMakereadyQty,
IsNull(WebStockPaperCost, 0) as WebStockPaperCost,
IsNull(WebSpoilageType, 0) as WebSpoilageType,
IsNull(PressPassesQty, 0) as PressPassesQty,
IsNull(PrintingType, 0) as PrintingType,
IsNull(PadsLeafQty, 0) as PadsLeafQty,
IsNull(PadsQuantity, 0) as PadsQuantity,
IsNull(LastUpdateDate, 0) as LastUpdateDate,
IsNull(LastUpdatedBy, 0) as LastUpdatedBy,
IsNull(Qty1MarkUpID, 0) as Qty1MarkUpID,
IsNull(Qty2MarkUpID, 0) as Qty2MarkUpID,
IsNull(Qty3MarkUpID, 0) as Qty3MarkUpID,
IsNull(StockItemID1, 0) as StockItemID1,
IsNull(StockItemID2, 0) as StockItemID2,
IsNull(StockItemID3, 0) as StockItemID3,
IsNull(Side1PlateQty, 0) as Side1PlateQty ,
IsNull(IsPortrait, 0) as IsPortrait,
IsNull(Side2PlateQty, 0) as Side2PlateQty,
IsNull(StockItemID1, 0) as PaperID,
IsNull(InkColorType, 0) as InkColorType,
IsNull(BaseCharge1Broker, 0) as BaseCharge1Broker,
IsNull(PlateInkID, 0) as PlateInkID,
IsNull(SimilarSections,0) as SimilarSections,
QuestionQueue,StockQueue,InputQueue,CostCentreQueue
FROM tbl_item_sections   
	  WHERE tbl_item_sections.ItemID = @ItemID order by ItemSectionID
	RETURN