
Create PROCEDURE [dbo].[sp_ItemSection_Insert_Section]
(
	@PressSpeed1 int,
	@PressSpeed2 int,
	@PressSpeed3 int,
	@PrintSheetQty1 int,
	@PrintSheetQty2 int,
	@PrintSheetQty3 int,
	@PressHourlyCharge float,
	@PrintChargeExMakeReady1 float,
	@PrintChargeExMakeReady2 float,
	@PrintChargeExMakeReady3 float,
	@PaperGsm float,
	@PaperPackPrice float,
	@PTVRows int,
	@PTVColoumns int,
	@PaperWeight1 float,
	@PaperWeight2 float,
	@PaperWeight3 float,
	@FinishedItemQty1 int,
	@FinishedItemQty2 int,
	@FinishedItemQty3 int,
	@isWorknTurn smallint,
	@isWorkntumble smallint,
	@IsMakeReadyUsed smallint,
	@SectionType smallint,
	@SectionNo int,
	@ItemSectionName varchar (50),
	@IsMainSection smallint,
	@ItemID int,
	@Qty1 int,
	@Qty2 int,
	@Qty3 int,
	@BaseCharge1 float,
	@BaseCharge2 float,
	@Basecharge3 float,
	@RunOnQty int,
	@SectionSizeID int,
	@IsSectionSizeCustom smallint,
	@SectionSizeHeight float,
	@SectionSizeWidth float,
	@ItemSizeID int,
	@IsItemSizeCustom smallint,
	@ItemSizeHeight float,
	@ItemSizeWidth float,
	@GuillotineID int,
	@IncludeGutter smallint,
	@PressID int,
	@FilmID int,
	@PlateID int,
	@ItemGutterHorizontal float,
	@ItemGutterVertical float,
	@IsPressrestrictionApplied smallint,
	@IsDoubleSided smallint,
	@IsWashup smallint,
	@PrintViewLayoutLandScape int,
	@PrintViewLayoutPortrait int,
	@PrintViewLayout int,
	@EstimateForWholePacks smallint,
	@IsFirstTrim smallint,
	@IsSecondTrim smallint,
	@PaperQty int,
	@ImpressionQty1 int,
	@ImpressionQty2 int,
	@ImpressionQty3 int,
	@FilmQty int,
	@IsFilmSupplied smallint,
	@IsPlateSupplied smallint,
	@PlateQty int,
	@WashupQty int,
	@MakeReadyQty int,
	@IsPaperCoated smallint,
	@GuillotineFirstCut int,
	@GuillotineSecondCut int,
	@AdditionalFilmUsed int,
	@AdditionalPlateUsed int,
	@IsFilmUsed smallint,
	@IsPlateUsed smallint,
	@NoofUniqueInks int,
	@WizardRunMode smallint,
	@Qty1Profit float,
	@Qty2Profit float,
	@Qty3Profit float,
	@RunOnBaseCharge float,
	@RunOnProfit float,
	@IsMultipleQty smallint,
	@IsRunOnQty smallint,
	@OverAllPtv int,
	@ItemPTV int,
	@PaperID int,
	@RunningSpoilage int,
	@RunningSpoilageValue int,
	@SetUpSpoilage float,
	@IsPaperSupplied smallint,
	@IsSwingApplied smallint,
	@ProfileID int,
	@SelectedPressCalculationMethodID int,
	@QuestionQueue image,
	@StockQueue image,
	@InputQueue image,
	@CostCentreQueue image,
	@SectionNotes text,
	@Side1Inks int,
	@Side2Inks int,
	@ImageType int,
	@GuillotineQty1BundlesFirstTrim int,
	@GuillotineQty2BundlesFirstTrim int,
	@GuillotineQty3BundlesFirstTrim int,
	@GuillotineQty1BundlesSecondTrim int,
	@GuillotineQty2BundlesSecondTrim int,
	@GuillotineQty3BundlesSecondTrim int,

	@GuillotineQty1FirstTrimCuts int,
	@GuillotineQty2FirstTrimCuts int,
	@GuillotineQty3FirstTrimCuts int,
 	@GuillotineQty1SecondTrimCuts int,
	@GuillotineQty2SecondTrimCuts int,
	@GuillotineQty3SecondTrimCuts int,
	@GuillotineQty1TotalsCuts int,
	@GuillotineQty2TotalsCuts int,
	@GuillotineQty3TotalsCuts  int,
	@WebClylinderHeight float ,
	@WebCylinderWidth float,
	@WebCylinderId int,
	@WebPaperLengthWithSp float,
	@WebPaperLengthWoSp float,
	@WebReelMakereadyQty int,
	@WebStockPaperCost float,
	@WebSpoilageType smallint,
	@PressPassesQty int,
	@PrintingType int,
	@PadsLeafQty	int,
	@PadsQuantity	int	

	
)
AS
insert into tbl_item_sections (PressSpeed1,PressSpeed2,PressSpeed3,PrintSheetQty1,PrintSheetQty2,PrintSheetQty3,PressHourlyCharge,PrintChargeExMakeReady1,PrintChargeExMakeReady2,PrintChargeExMakeReady3,PaperGsm,PaperPackPrice,PTVRows,PTVColoumns,PaperWeight1,PaperWeight2,PaperWeight3,FinishedItemQty1,FinishedItemQty2,FinishedItemQty3,isWorknTurn,isWorkntumble,IsMakeReadyUsed,SectionType,SectionNo,SectionName,IsMainSection,ItemID,Qty1,Qty2,Qty3,BaseCharge1,BaseCharge2,Basecharge3,RunOnQty,SectionSizeID,IsSectionSizeCustom,SectionSizeHeight,SectionSizeWidth,ItemSizeID,IsItemSizeCustom,ItemSizeHeight,ItemSizeWidth,GuillotineID,IncludeGutter,PressID,FilmID,PlateID,ItemGutterHorizontal,ItemGutterVertical,IsPressrestrictionApplied,IsDoubleSided,IsWashup,PrintViewLayoutLandScape,PrintViewLayoutPortrait,PrintViewLayout,EstimateForWholePacks,IsFirstTrim,IsSecondTrim,PaperQty,ImpressionQty1,ImpressionQty2,ImpressionQty3,FilmQty,IsFilmSupplied,IsPlateSupplied,Side1PlateQty,WashupQty,MakeReadyQty,IsPaperCoated,GuillotineFirstCut,GuillotineSecondCut,AdditionalFilmUsed,AdditionalPlateUsed,IsFilmUsed,IsPlateUsed,NoofUniqueInks,WizardRunMode,Qty1Profit,Qty2Profit,Qty3Profit,RunOnBaseCharge,RunOnProfit,IsMultipleQty,IsRunOnQty,OverAllPTV,ItemPTV,StockItemID1,RunningSpoilage,RunningSpoilagevalue,SetUpSpoilage,IsPaperSupplied,IsSwingApplied,ProfileID,SelectedPressCalculationMethodID,QuestionQueue,StockQueue,InputQueue,CostCentreQueue,SectionNotes,Side1Inks,Side2Inks,ImageType,
GuillotineQty1BundlesFirstTrim ,GuillotineQty2BundlesFirstTrim ,GuillotineQty3BundlesFirstTrim ,GuillotineQty1BundlesSecondTrim, GuillotineQty2BundlesSecondTrim, GuillotineQty3BundlesSecondTrim,
GuillotineQty1FirstTrimCuts, GuillotineQty2FirstTrimCuts, GuillotineQty3FirstTrimCuts, GuillotineQty1SecondTrimCuts, GuillotineQty2SecondTrimCuts, GuillotineQty3SecondTrimCuts, GuillotineQty1TotalsCuts, GuillotineQty2TotalsCuts,GuillotineQty3TotalsCuts ,
WebClylinderHeight ,WebCylinderWidth ,WebCylinderId ,WebPaperLengthWithSp ,WebPaperLengthWoSp ,WebReelMakereadyQty ,WebStockPaperCost,WebSpoilageType,PressPassesQty,PrintingType,PadsLeafQty,PadsQuantity
) VALUES 
(@PressSpeed1,@PressSpeed2,@PressSpeed3,@PrintSheetQty1,@PrintSheetQty2,@PrintSheetQty3,@PressHourlyCharge,@PrintChargeExMakeReady1,@PrintChargeExMakeReady2,@PrintChargeExMakeReady3,@PaperGsm,@PaperPackPrice,@PTVRows,@PTVColoumns,@PaperWeight1,@PaperWeight2,@PaperWeight3,@FinishedItemQty1,@FinishedItemQty2,@FinishedItemQty3,@isWorknTurn,@isWorkntumble,@IsMakeReadyUsed,@SectionType,@SectionNo,@ItemSectionName,@IsMainSection,@ItemID,@Qty1,@Qty2,@Qty3,@BaseCharge1,@BaseCharge2,@Basecharge3,@RunOnQty,@SectionSizeID,@IsSectionSizeCustom,@SectionSizeHeight,@SectionSizeWidth,@ItemSizeID,@IsItemSizeCustom,@ItemSizeHeight,@ItemSizeWidth,@GuillotineID,@IncludeGutter,@PressID,@FilmID,@PlateID,@ItemGutterHorizontal,@ItemGutterVertical,@IsPressrestrictionApplied,@IsDoubleSided,@IsWashup,@PrintViewLayoutLandScape,@PrintViewLayoutPortrait,@PrintViewLayout,@EstimateForWholePacks,@IsFirstTrim,@IsSecondTrim,@PaperQty,@ImpressionQty1,@ImpressionQty2,@ImpressionQty3,@FilmQty,@IsFilmSupplied,@IsPlateSupplied,@PlateQty,@WashupQty,@MakeReadyQty,@IsPaperCoated,@GuillotineFirstCut,@GuillotineSecondCut,@AdditionalFilmUsed,@AdditionalPlateUsed,@IsFilmUsed,@IsPlateUsed,@NoofUniqueInks,@WizardRunMode,@Qty1Profit,@Qty2Profit,@Qty3Profit,@RunOnBaseCharge,@RunOnProfit,@IsMultipleQty,@IsRunOnQty,@OverAllPtv,@ItemPTV,@PaperID,@RunningSpoilage,@RunningSpoilageValue,@SetUpSpoilage,@IsPaperSupplied,
@IsSwingApplied,@ProfileID,@SelectedPressCalculationMethodID,@QuestionQueue,@StockQueue,@InputQueue,@CostCentreQueue,@SectionNotes,@Side1Inks,@Side2Inks,@ImageType,
@GuillotineQty1BundlesFirstTrim ,@GuillotineQty2BundlesFirstTrim ,@GuillotineQty3BundlesFirstTrim ,@GuillotineQty1BundlesSecondTrim,@GuillotineQty1BundlesSecondTrim,@GuillotineQty1BundlesSecondTrim,
@GuillotineQty1FirstTrimCuts, @GuillotineQty2FirstTrimCuts, @GuillotineQty3FirstTrimCuts, @GuillotineQty1SecondTrimCuts, @GuillotineQty2SecondTrimCuts, @GuillotineQty3SecondTrimCuts, @GuillotineQty1TotalsCuts, @GuillotineQty2TotalsCuts, @GuillotineQty3TotalsCuts,
@WebClylinderHeight ,@WebCylinderWidth ,@WebCylinderId ,@WebPaperLengthWithSp ,@WebPaperLengthWoSp ,@WebReelMakereadyQty ,@WebStockPaperCost,@WebSpoilageType,@PressPassesQty,@PrintingType,@PadsLeafQty,@PadsQuantity
);SELECT @@IDENTITY AS ItemSectionID
	RETURN