CREATE PROCEDURE dbo.sp_jobcard_update
(@IsDefaultInkColorUsed bit,
@IsDefaultFilmUsed bit,
@IsdefaultPlateUsed bit, 
@IsDefaultMakereadyUsed bit,
@IsDefaultWashupUsed bit,
@IsDefaultPressInstruction bit,
@IsWorkingSize bit,
@IsItemSize bit,
@IsImpressionCount bit,
@IsNumberOfPasses bit,
@IsPrintSheetQty bit,
@IsDefaultStockDetail bit,
@IsOrderSheetSize bit,
@IsSpoilageAllowed bit,
@IsPaperWeight bit,
@IsPaperSheetQty bit,
@IsDefaultGuilotine bit,
@IsGuilotineWorkingSize bit,
@IsGuilotineItemSize bit,
@IsNoOfTrims bit,
@IsNoOfCuts bit ,
@SystemSiteID int,
@IsInksEstTime int,
@InFilmEstTime int,
@IsPlateEstTime int,
@IsWashupEstTime int,
@IsMakereadyEstTime int,
@IsPressEstTime int,
@IsPaperEstTime int,
@IsGuillotineEstTime int,
@IsReelMakeReady int,
@IsReelMakeReadyTime int
               
)
                  AS
update tbl_job_preferences set IsDefaultInkColorUsed=@IsDefaultInkColorUsed,
IsDefaultFilmUsed=@IsDefaultFilmUsed,
IsdefaultPlateUsed=@IsdefaultPlateUsed,
IsDefaultMakereadyUsed=@IsDefaultMakereadyUsed,
IsDefaultWashupUsed=@IsDefaultWashupUsed,
IsDefaultPressInstruction=@IsDefaultPressInstruction,
IsWorkingSize=@IsWorkingSize,
IsItemSize=@IsItemSize,
IsImpressionCount=@IsImpressionCount,
IsNumberOfPasses=@IsNumberOfPasses,
IsPrintSheetQty=@IsPrintSheetQty,
IsDefaultStockDetail=@IsDefaultStockDetail,
IsOrderSheetSize=@IsOrderSheetSize,
IsSpoilageAllowed=@IsSpoilageAllowed,
IsPaperWeight=@IsPaperWeight,
IsPaperSheetQty=@IsPaperSheetQty,
IsDefaultGuilotine=@IsDefaultGuilotine,
IsGuilotineWorkingSize=@IsGuilotineWorkingSize,
IsGuilotineItemSize=@IsGuilotineItemSize,
IsNoOfTrims=@IsNoOfTrims,
IsNoOfCuts=@IsNoOfCuts,
IsInksEstTime=@IsInksEstTime, InFilmEstTime=@InFilmEstTime, IsPlateEstTime=@IsPlateEstTime, IsWashupEstTime=@IsWashupEstTime, IsMakereadyEstTime=@IsMakereadyEstTime, IsPressEstTime=@IsPressEstTime, IsPaperEstTime=@IsPaperEstTime, IsGuillotineEstTime=@IsGuillotineEstTime,
IsReelMakeReady = @IsReelMakeReady ,
IsReelMakeReadyTime = @IsReelMakeReadyTime 
where SystemSiteID=@SystemSiteID
             RETURN