CREATE PROCEDURE dbo.sp_machines_insert
( 
                 @SpoilageType int,
                 @IsScheduleable bit,
                 @MakereadyPrice float,
                 @WashupPrice float,
                 @PricePerCut float,
                 @SystemSiteID int,
                 @CostPerCut float,
                 @IsAdditionalOption bit,
                 @IsDisabled bit,
                 @MachineName varchar(50),
                 @MachineCatID int,
                 @ColourHeads int,
                 @isPerfecting bit,
                 @SetupCharge float,
                 @WashupCost float,
                 @MinInkDuctqty float,
                 @worknturncharge float, 
                 @MakeReadyCost float,
                 @DefaultFilmid int,
                 @DefaultPlateid int,
                 @DefaultPaperid int,
                 @isfilmused int,
                 @isplateused int,
                 @ismakereadyused int, 
                 @iswashupused int,
                 @maximumsheetweight float,
                 @maximumsheetheight float,
                 @maximumsheetwidth float,
                 @minimumsheetheight float,
                 @minimumsheetwidth float, 
                 @gripdepth float,
                 @gripsideorientaion int,
                 @gutterdepth float,
                 @headdepth float,
                 @Va int,
                 @PressSizeRatio float,
                 @Description text,
                 @Priority float,
                 @MinimumCharge float,
                 @DirectCost float,  
                 @IsMaxColorLimit bit,
                 @PressUtilization float,
                 @InkChargeForUniqueColors float,
                 @CylinderSizeID int,
                 @MaxItemAcrossCylinder int,
                 @Web1MRCost float,
                 @Web2MRCost float,
                 @ReelMRCost float,
                 @Web1MRPrice float,
                 @Web2MRPrice float,
                 @ReelMRPrice float,
                 @SetUpTime float,
                 @WashupTime float,
                 @MakeReadyTime float,
                 @TimePerCut float,
                 @ReelMakereadyTime float
                )
AS
	insert into tbl_machines (SpoilageType,IsScheduleable,MakereadyPrice,WashupPrice,PricePerCut,SystemSiteID,CostPerCut,IsAdditionalOption,IsDisabled,MachineName,MachineCatID,ColourHeads,isPerfecting,
                 SetupCharge,WashupCost,MinInkDuctqty,worknturncharge,MakeReadyCost,DefaultFilmid, 
                 DefaultPlateid,DefaultPaperid,isfilmused,isplateused,ismakereadyused,iswashupused,maximumsheetweight,maximumsheetheight, 
                 maximumsheetwidth,minimumsheetheight,minimumsheetwidth,gripdepth,gripsideorientaion,gutterdepth,
                 headdepth,Va,PressSizeRatio,Description,Priority,MinimumCharge,DirectCost,IsMaxColorLimit,PressUtilization,InkChargeForUniqueColors,CylinderSizeID,MaxItemAcrossCylinder,
                 Web1MRCost,Web2MRCost,ReelMRCost,Web1MRPrice,Web2MRPrice,ReelMRPrice,SetUpTime,WashupTime,MakeReadyTime,TimePerCut,ReelMakereadyTime) VALUES ( 
                 @SpoilageType,@IsScheduleable,@MakereadyPrice,@WashupPrice,@PricePerCut,@SystemSiteID,@CostPerCut,@IsAdditionalOption,@IsDisabled,@MachineName,@MachineCatID,@ColourHeads,@isPerfecting,@SetupCharge,@WashupCost,@MinInkDuctqty,@worknturncharge, 
                 @MakeReadyCost,@DefaultFilmid,@DefaultPlateid,@DefaultPaperid,@isfilmused,@isplateused,@ismakereadyused, 
                 @iswashupused,
                 @maximumsheetweight,@maximumsheetheight,@maximumsheetwidth,@minimumsheetheight,@minimumsheetwidth, 
                 @gripdepth,@gripsideorientaion,@gutterdepth,@headdepth,@Va,@PressSizeRatio,@Description,@Priority,@MinimumCharge,@DirectCost,  
                 @IsMaxColorLimit,@PressUtilization,@InkChargeForUniqueColors,@CylinderSizeID,@MaxItemAcrossCylinder,
                 @Web1MRCost,@Web2MRCost,@ReelMRCost,@Web1MRPrice,@Web2MRPrice,@ReelMRPrice,@SetUpTime,@WashupTime,@MakeReadyTime,@TimePerCut,@ReelMakereadyTime);
                 Select @@Identity as MachineID
        RETURN