CREATE PROCEDURE dbo.sp_machines_update
( 
                 @SpoilageType int,
                 @IsScheduleable bit,
                 @MakereadyPrice float,
                 @WashupPrice float,
                 @PricePerCut float,
                 @CostPerCut float,
                 @IsAdditionalOption bit,
                 @IsDisabled bit,
                 @MachineName varchar(50),
                 @MachineCatID int,
                 @ColourHeads int,
                 @isPerfecting bit,
                 @SetupCharge float,
                 @WashupCost float,
                 @MinInkDuctqty float,
                 @worknturncharge float, 
                 @MakeReadyCost float,
                 @DefaultFilmid int,
                 @DefaultPlateid int,
                 @DefaultPaperid int,
                 @isfilmused int,
                 @isplateused int,
                 @ismakereadyused int, 
                 @iswashupused int,
                 @maximumsheetweight float,
                 @maximumsheetheight float,
                 @maximumsheetwidth float,
                 @minimumsheetheight float,
                 @minimumsheetwidth float, 
                 @gripdepth float,
                 @gripsideorientaion int,
                 @gutterdepth float,
                 @headdepth float,
                 @Va int,
                 @PressSizeRatio float,
                 @Description text,
                 @Priority int,
                 @MinimumCharge float,
                 @DirectCost float,  
                 @IsMaxColorLimit bit,
                 @PressUtilization float,
                 @InkChargeForUniqueColors float,
                 @CylinderSizeID int,
                 @MaxItemAcrossCylinder int,
                 @Web1MRCost float,
                 @Web2MRCost float,
                 @ReelMRCost float,
                 @Web1MRPrice float,
                 @Web2MRPrice float,
                 @ReelMRPrice float,
                 @MachineID int,
                 @SetUpTime float,
                 @WashupTime float,
                 @MakeReadyTime float,
                 @TimePerCut float,
                 @ReelMakereadyTime float
                 )
AS
	Update tbl_machines set SpoilageType=@SpoilageType,IsScheduleable=@IsScheduleable,MakereadyPrice=@MakereadyPrice,WashupPrice=@WashupPrice,PricePerCut=@PricePerCut,CostPerCut=@CostPerCut,IsMaxColorLimit=@IsMaxColorLimit,PressUtilization=@PressUtilization,InkChargeForUniqueColors=@InkChargeForUniqueColors,CylinderSizeID=@CylinderSizeID,MaxItemAcrossCylinder=@MaxItemAcrossCylinder,
                Web1MRPrice=@Web1MRPrice,Web2MRPrice=@Web2MRPrice,ReelMRPrice=@ReelMRPrice,Web1MRCost=@Web1MRCost,Web2MRCost=@Web2MRCost,ReelMRCost=@ReelMRCost, 
                IsAdditionalOption=@IsAdditionalOption,IsDisabled=@IsDisabled,MachineName=@MachineName,MachineCatID=@MachineCatID,ColourHeads=@ColourHeads,isPerfecting=@isPerfecting,
                SetupCharge=@SetupCharge,WashupCost=@WashupCost,MinInkDuctqty=@MinInkDuctqty,worknturncharge=@worknturncharge,MakeReadyCost=@MakeReadyCost,DefaultFilmid=@DefaultFilmid, 
                DefaultPlateid=@DefaultPlateid,DefaultPaperid=@DefaultPaperid,isfilmused=@isfilmused,isplateused=@isplateused,ismakereadyused=@ismakereadyused,iswashupused=@iswashupused,maximumsheetweight=@maximumsheetweight,maximumsheetheight=@maximumsheetheight, 
                maximumsheetwidth=@maximumsheetwidth,minimumsheetheight=@minimumsheetheight,minimumsheetwidth=@minimumsheetwidth,gripdepth=@gripdepth,gripsideorientaion=@gripsideorientaion,gutterdepth=@gutterdepth,
                headdepth=@headdepth,Va=@Va,PressSizeRatio=@PressSizeRatio,Description=@Description,Priority=@Priority,MinimumCharge=@MinimumCharge,DirectCost=@DirectCost,SetUpTime=@SetUpTime,WashupTime=@WashupTime,MakeReadyTime=@MakeReadyTime,TimePerCut=@TimePerCut,ReelMakereadyTime=@ReelMakereadyTime where MachineID=@MachineID
        RETURN