
CREATE PROCEDURE [dbo].[sp_Orders_Update_EstimateToOrder]
(
	@Order_Code varchar (50),
	@Order_Date datetime,
	@IsEstimate smallint,
	@Order_CreationDateTime datetime,
	@Order_DeliveryDate datetime,
	@Order_ConfirmationDate datetime,
	@Order_Status smallint,
				@OrderManagerID int,
                 @ArtworkByDate datetime,
                 @DataByDate datetime,
                 @TargetPrintDate datetime,
                 @StartDeliveryDate datetime,
                 @PaperByDate datetime,
                 @TargetBindDate datetime,
                 @FinishDeliveryDate datetime,
                 @Classification1ID int,
                 @Classification2ID int,
                 @IsOfficialOrder int,
                 @CustomerPO varchar(50),
                 @OfficialOrderSetBy int,
                 @OfficialOrderSetOnDateTime datetime,
                 @IsCreditApproved int,
                 @CreditLimitForJob float,
                 @CreditLimitSetBy int,
                 @CreditLimitSetOnDateTime datetime,
                 @IsJobAllowedWOCreditCheck int,
                 @AllowJobWOCreditCheckSetBy int,
                 @AllowJobWOCreditCheckSetOnDateTime datetime,
                 @OrderNo varchar(50),
	@EstimateID int,@OrderSourceID smallint,@CustomerOrderStatusID int,@ShoppingCartID int
)
AS
	update tbl_Estimates set Order_Code=@Order_Code,Order_Date=@Order_Date,IsEstimate=@IsEstimate,Order_CreationDateTime=@Order_CreationDateTime,
	Order_DeliveryDate=@Order_DeliveryDate,Order_ConfirmationDate=@Order_ConfirmationDate,
	Order_Status=@Order_Status,
				 OrderManagerID=@OrderManagerID,
                 ArtworkByDate=@ArtworkByDate,
                 DataByDate=@DataByDate,
                 TargetPrintDate=@TargetPrintDate,
                 StartDeliveryDate=@StartDeliveryDate,
                 PaperByDate=@PaperByDate,
                 TargetBindDate=@TargetBindDate,
                 FinishDeliveryDate=@FinishDeliveryDate,
                 Classification1ID=@Classification1ID,
                 Classification2ID=@Classification2ID,
                 IsOfficialOrder=@IsOfficialOrder,
                 CustomerPO=@CustomerPO,
                 OfficialOrderSetBy=@OfficialOrderSetBy,
                 OfficialOrderSetOnDateTime=@OfficialOrderSetOnDateTime,
                 IsCreditApproved=@IsCreditApproved,
                 CreditLimitForJob=@CreditLimitForJob,
                 CreditLimitSetBy=@CreditLimitSetBy,
                 CreditLimitSetOnDateTime=@CreditLimitSetOnDateTime,
                 IsJobAllowedWOCreditCheck=@IsJobAllowedWOCreditCheck,
                 AllowJobWOCreditCheckSetBy=@AllowJobWOCreditCheckSetBy,
                 AllowJobWOCreditCheckSetOnDateTime=@AllowJobWOCreditCheckSetOnDateTime,OrderNo=@OrderNo,
                 OrderSourceID=@OrderSourceID ,StatusID=@Order_Status
	 where EstimateID=@EstimateID
	RETURN