CREATE PROCEDURE dbo.sp_products_update_product
(@QtyPrefix varchar(100),
@IsPressrestrictionApplied bit,
@TypeID int,
@ProductName varchar(50),
@PressID int,
@GuilotineID int,
@IsFirstTrim bit,
@IsSecondTrim bit,
@IsPaperSupplied bit,
@IsWholePack bit,
@WorkingSheetSizeID int,
@WorkingSheetSizeIsCustom bit,
@WorkingSheetSizeHeight float,
@WorkingSheetSizeWidth float,
@ItemSheetSizeID int,
@ItemSheetSizeIsCustom bit,
@ItemSheetSizeHeight float,
@ItemSheetSizeWidth float,
@IsItemGutterApplied bit, 
@ItemGutterHorizontal float,
@ItemGutterVertical float,
@IsDoubleSided bit,
@IsWorknTurn bit,
@IsWorknTunble bit,
@IsMultipleQty bit,
@IsRunonQty bit,
@RunonQty int,
@Qty1 int, 
@Qty2 int,
@Qty3 int,
@BookletPages int,
@Side1Inks int,
@Side2Inks int,
@IsInkPrompted bit,
@Description text,
@PadLeafQty int,
@NCRTopPaperID int,
@NCRBottomPaperID int,
@NCRMiddlePaperID int, 
@NCRTotalParts int,
@ProductID int,
@IsFilmSupplied bit,
@IsPlateSupplied bit)
AS
	update tbl_profile set QtyPrefix=@QtyPrefix,TypeID=@TypeID,Name=@ProductName,PressID=@PressID,GuilotineID=@GuilotineID,IsFirstTrim=@IsFirstTrim, 
         IsSecondTrim=@IsSecondTrim,IsPaperSupplied=@IsPaperSupplied,IsWholePack=@IsWholePack,WorkingSheetSizeID=@WorkingSheetSizeID,WorkingSheetSizeIsCustom=@WorkingSheetSizeIsCustom,WorkingSheetSizeHeight=@WorkingSheetSizeHeight, 
         WorkingSheetSizeWidth=@WorkingSheetSizeWidth,ItemSheetSizeID=@ItemSheetSizeID,ItemSheetSizeIsCustom=@ItemSheetSizeIsCustom,ItemSheetSizeHeight=@ItemSheetSizeHeight,ItemSheetSizeWidth=@ItemSheetSizeWidth,IsItemGutterApplied=@IsItemGutterApplied, 
         ItemGutterHorizontal=@ItemGutterHorizontal,ItemGutterVertical=@ItemGutterVertical,IsDoubleSided=@IsDoubleSided,IsWorknTurn=@IsWorknTurn,IsWorknTunble=@IsWorknTunble,IsMultipleQty=@IsMultipleQty,IsRunonQty=@IsRunonQty,RunonQty=@RunonQty,Qty1=@Qty1, 
         Qty2=@Qty2,Qty3=@Qty3,BookletPages=@BookletPages,Side1Inks=@Side1Inks,Side2Inks=@Side2Inks,IsInkPrompted=@IsInkPrompted,Description=@Description,IsPressrestrictionApplied=@IsPressrestrictionApplied, 
         PadLeafQty=@PadLeafQty,NCRTopPaperID=@NCRTopPaperID,NCRBottomPaperID=@NCRBottomPaperID,NCRMiddlePaperID=@NCRMiddlePaperID,NCRTotalParts=@NCRTotalParts,
         IsFilmSupplied=@IsFilmSupplied,IsPlateSupplied=@IsPlateSupplied Where ID=@ProductID
	RETURN