CREATE PROCEDURE dbo.sp_products_insert_product
(@QtyPrefix varchar(100),
@SystemSiteID int,
@IsPressrestrictionApplied bit,
@TypeID int,
@ProductName varchar(50),
@PressID int,
@GuilotineID int,
@IsFirstTrim bit,
@IsSecondTrim bit,
@IsPaperSupplied bit,
@IsWholePack bit,
@WorkingSheetSizeID int,
@WorkingSheetSizeIsCustom bit,
@WorkingSheetSizeHeight float,
@WorkingSheetSizeWidth float,
@ItemSheetSizeID int,
@ItemSheetSizeIsCustom bit,
@ItemSheetSizeHeight float,
@ItemSheetSizeWidth float,
@IsItemGutterApplied bit, 
@ItemGutterHorizontal float,
@ItemGutterVertical float,
@IsDoubleSided bit,
@IsWorknTurn bit,
@IsWorknTunble bit,
@IsMultipleQty bit,
@IsRunonQty bit,
@RunonQty int,
@Qty1 int, 
@Qty2 int,
@Qty3 int,
@BookletPages int,
@Side1Inks int,
@Side2Inks int,
@IsInkPrompted bit,
@Description text,
@PadLeafQty int,
@NCRTopPaperID int,
@NCRBottomPaperID int,
@NCRMiddlePaperID int, 
@NCRTotalParts int,
@IsFilmSupplied bit,
@IsPlateSupplied bit)
AS
	insert into tbl_profile (QtyPrefix,SystemSiteID,IsPressrestrictionApplied,TypeID,Name,PressID,GuilotineID,IsFirstTrim, 
         IsSecondTrim,IsPaperSupplied,IsWholePack,WorkingSheetSizeID,WorkingSheetSizeIsCustom,WorkingSheetSizeHeight, 
         WorkingSheetSizeWidth,ItemSheetSizeID,ItemSheetSizeIsCustom,ItemSheetSizeHeight,ItemSheetSizeWidth,IsItemGutterApplied, 
         ItemGutterHorizontal,ItemGutterVertical,IsDoubleSided,IsWorknTurn,IsWorknTunble,IsMultipleQty,IsRunonQty,RunonQty,Qty1, 
         Qty2,Qty3,BookletPages,Side1Inks,Side2Inks,IsInkPrompted,Description,PadLeafQty,NCRTopPaperID,NCRBottomPaperID,NCRMiddlePaperID,
         NCRTotalParts,IsFilmSupplied,IsPlateSupplied) VALUES 
         (@QtyPrefix,@SystemSiteID,@IsPressrestrictionApplied,@TypeID,@ProductName,@PressID,@GuilotineID,@IsFirstTrim, 
         @IsSecondTrim,@IsPaperSupplied,@IsWholePack,@WorkingSheetSizeID,@WorkingSheetSizeIsCustom,@WorkingSheetSizeHeight, 
         @WorkingSheetSizeWidth,@ItemSheetSizeID,@ItemSheetSizeIsCustom,@ItemSheetSizeHeight,@ItemSheetSizeWidth,@IsItemGutterApplied, 
         @ItemGutterHorizontal,@ItemGutterVertical,@IsDoubleSided,@IsWorknTurn,@IsWorknTunble,@IsMultipleQty,@IsRunonQty,@RunonQty,@Qty1, 
         @Qty2,@Qty3,@BookletPages,@Side1Inks,@Side2Inks,@IsInkPrompted,@Description,@PadLeafQty,@NCRTopPaperID,@NCRBottomPaperID,
         @NCRMiddlePaperID,@NCRTotalParts,@IsFilmSupplied,@IsPlateSupplied);Select @@Identity as ProductID
	RETURN