CREATE PROCEDURE dbo.sp_Scheduling_update_PrintJob

	(
		@ItemSectionID int ,
		@MachineID int,
		@MakeReadyType int,
		@Speed float ,
		@RepeatDays int ,
		@RepeatOccurrencs int ,
		@Notes text ,
		@CustomerId int,
		@JobCode varchar(255),
		@JobID int,
		@Quantity int,
		@NoOfUp int,
		@MachineName varchar(255),
		@Estimate_Code varchar(255),
		@CustomerName varchar(255),
		@GullotineID int,
		@Pagination int ,
		@ItemSectionName varchar(255),
		@Discription text,
		@SelectedQtyIndex int,
		@StartTime datetime,
		@EndTime datetime,
		@MachineType int,
		@ScheduledPrintJobID int,
		@TargetPrintDate datetime ,
		@ArtworkByDate datetime ,
		@DataByDate datetime ,
		@TargetBindDate datetime,
		@GullotineName varchar(255)
	)

AS

Update tbl_scheduled_printjobs set 
                                            tbl_scheduled_printjobs.ItemSectionID= @ItemSectionID,
                                            tbl_scheduled_printjobs.MachineID=@MachineID,
                                            tbl_scheduled_printjobs.MakeReadyType=@MakeReadyType,
                                            tbl_scheduled_printjobs.Speed=@Speed,
                                            tbl_scheduled_printjobs.RepeatDays=@RepeatDays,
                                            tbl_scheduled_printjobs.RepeatOccurrencs=@RepeatOccurrencs,
                                            tbl_scheduled_printjobs.Notes=@Notes,
                                            tbl_scheduled_printjobs.CustomerId=@CustomerId,
                                            tbl_scheduled_printjobs.JobCode=@JobCode, 
                                            tbl_scheduled_printjobs.JobID=@JobID, 
                                            tbl_scheduled_printjobs.Quantity=@Quantity,
                                            tbl_scheduled_printjobs.NoOfUp=@NoOfUp,
                                            tbl_scheduled_printjobs.MachineName=@MachineName,
                                            tbl_scheduled_printjobs.Estimate_Code=@Estimate_Code,
                                            tbl_scheduled_printjobs.CustomerName=@CustomerName,
                                            tbl_scheduled_printjobs.GullotineID=@GullotineID,
                                            tbl_scheduled_printjobs.Pagination=@Pagination,
                                            tbl_scheduled_printjobs.ItemSectionName=@ItemSectionName,
                                            tbl_scheduled_printjobs.Discription=@Discription,
                                            tbl_scheduled_printjobs.SelectedQtyIndex=@SelectedQtyIndex,
                                            tbl_scheduled_printjobs.StartTime=@StartTime,
                                            tbl_scheduled_printjobs.EndTime=@EndTime,
                                            tbl_scheduled_printjobs.MachineType=@MachineType,
											tbl_scheduled_printjobs.TargetPrintDate  = @TargetPrintDate  ,
											tbl_scheduled_printjobs.ArtworkByDate=@ArtworkByDate  ,
											tbl_scheduled_printjobs.DataByDate=@DataByDate  ,
											tbl_scheduled_printjobs.TargetBindDate =@TargetBindDate ,
											tbl_scheduled_printjobs.GullotineName = @GullotineName
                                            where ScheduledPrintJobID= @ScheduledPrintJobID
	RETURN