CREATE PROCEDURE [dbo].[sp_Suppliers_Supplier_UpdateSupplier]
(
       @SupplierID int,
       @SupplierName varchar(100),
	   @AccountNumber varchar(10), 
	   @SupplierTypeID int ,
	   @URL varchar(30),
	   @ISBN varchar(30),
	   @Notes nvarchar(3000),
	   @CreditLimit float,
	   @DefaultMarkUpID int,
	   @DefaultNominalCode int,
	   @CreditReference varchar(50), 
	   @Terms nvarchar(3000),
	   @AccountBalance float =  0,
	   @VATRegNumber varchar(50), 
	   @VATRegReference varchar(50), 
	   @BankName varchar(50), 
	   @BankAddress1 varchar(255),
	   @BankAddress2 varchar(255),
	   @BankCity varchar(30),
	   @BankState varchar(30), 
	   @BankPostCode varchar(30), 
	   @BankCountry varchar(30),
	   @BankPhone varchar(30), 
	   @BankExtension varchar(30),
	   @BankAccountType varchar(30), 
	   @BankSortCode varchar(30),
       @BankBacsRef varchar(255), 
       @BankAccountNo varchar(30),
       @BankAccounName varchar(50),
       @BankFax varchar(30),
       @IsDisabled smallint,
       @IsParaentCompany int,
       @ParaentCompanyID int, 
       @FlagID int,
       @SystemSiteID int=0,
       @NotesLastUpdatedDate datetime,
       @NotesLastUpdatedBy int,
       @DepartmentID int
)
AS

UPDATE tbl_ContactCompanies SET AccountNumber=@BankAccountNo,
        Name=@SupplierName,URL=@URL,CreditReference=@CreditReference,CreditLimit=@CreditLimit,
        Terms=@Terms,TypeID=@SupplierTypeID,DefaultNominalCode=@DefaultNominalCode,
        DefaultMarkUpID=@DefaultMarkUpID,Notes=@Notes,ISBN=@ISBN,NotesLastUpdatedDate=@NotesLastUpdatedDate,
        NotesLastUpdatedBy=@NotesLastUpdatedBy,IsDisabled=@IsDisabled,VATRegNumber=@VATRegNumber,IsParaentCompany=@IsParaentCompany,
        ParaentCompanyID=@ParaentCompanyID,VATRegReference=@VATRegReference,
        
         --BankName=@BankName,BankAddress1=@BankAddress1,BankAddress2=@BankAddress2,BankCity=@BankCity,BankState=@BankState,
         --BankPostCode=@BankPostCode,BankCountry=@BankCountry,BankPhone=@BankPhone,BankExtension=@BankExtension,
         --BankAccountType=@BankAccountType,BankSortCode=@BankSortCode, BankBacsRef=@BankBacsRef,BankAccountNo=@BankAccountNo,
         --BankAccounName=@BankAccounName,BankFax=@BankFax,
         FlagID=@FlagID,DepartmentID=@DepartmentID WHERE ContactCompanyID=@SupplierID
     
	RETURN