
Create PROCEDURE [dbo].[sp_StockInventory_UPDATE_STOCK]

	(
		@ItemCode varchar(50),
		@ItemName varchar(255),
		@categoryID integer,
		@SubCategory integer,
		@status integer,
		@StockLocation varchar(50),
		@LastModifiedDateTime datetime,
		@LastModifiedBy integer,
		@StockCreated datetime,
		@SupplierID integer,
		@ItemWeight integer,
		@ItemColour varchar(50),
		@ItemSizeCustom smallint,
		@ItemSizeID integer,
		@ItemSizeHeight float,
		@ItemSizeWidth float,
		@ItemSizeDim integer,
		@ItemUnitSize integer,
		@CostPrice float,
		@StockLevel integer,
		@PackageQty float,
		@ReOrderLevel float,
		@ItemCoatedType smallint,
		@ItemCoated smallint,
		@ItemExposure smallint,
		@ItemExposureTime integer,
		@ItemProcessingCharge float,
		@PerQtyRate float,
		@PerQtyQty float,
		@ItemDescription varchar(255),
		@LockedBy integer,
		@ReorderQty integer,
		@UnitRate float,
		@Tax integer,
		@ItemSizeSelectedUnit smallint,
		@ItemWeightSelectedUnit smallint,
		@flagID integer,
		@InkAbsorption float,
		@WashupCounter integer,
		@InkYield float,		
		@PaperBasicAreaID integer,
		@PaperType integer,
		@PerQtyType integer,
		@RollWidth float,
		@RollLength float,
		@RollStandards integer,
		@DepartmentID integer,
		@InkYieldStandards integer,
		@PerQtyPrice float,
		@PackPrice float,
		@Region varchar(10),
		@isDisabled smallint,
		@AlternateName varchar(255),
		@InkStandards integer,	
		@BarCode varchar(100),
		@Image1 image,
		@Thumbnail image,
		@ItemID integer		
		--@parameter2 datatype OUTPUT
	)

AS
	 UPDATE tbl_stockitems set ItemCode=@ItemCode,ItemName=@ItemName,categoryID=@categoryID,
	 SubCategoryID=@SubCategory,status=@status,StockLocation=@StockLocation,
	 LastModifiedDateTime=@LastModifiedDateTime,LastModifiedBy=@LastModifiedBy,
	 StockCreated=@StockCreated,SupplierID=@SupplierID,ItemWeight=@ItemWeight,
	 ItemColour=@ItemColour,ItemSizeCustom=@ItemSizeCustom,ItemSizeID=@ItemSizeID,
	 ItemSizeHeight=@ItemSizeHeight,ItemSizeWidth=@ItemSizeWidth,ItemSizeDim=@ItemSizeDim,
	 ItemUnitSize=@ItemUnitSize,CostPrice=@CostPrice,StockLevel=@StockLevel, PackageQty=@PackageQty,
	 ReOrderLevel=@ReOrderLevel,ItemCoatedType=@ItemCoatedType,ItemCoated=@ItemCoated,
	 ItemExposure=@ItemExposure,ItemExposureTime=@ItemExposureTime,ItemProcessingCharge=@ItemProcessingCharge,
     PerQtyRate=@PerQtyRate,PerQtyQty=@PerQtyQty,ItemDescription=@ItemDescription,
     LockedBy=@LockedBy,ReorderQty=@ReorderQty,UnitRate=@UnitRate,TaxID=@Tax, 
     ItemSizeSelectedUnit=@ItemSizeSelectedUnit, ItemWeightSelectedUnit=@ItemWeightSelectedUnit,
     flagID=@flagID, InkAbsorption=@InkAbsorption,WashupCounter=@WashupCounter,
     InkYield=@InkYield,PaperBasicAreaID=@PaperBasicAreaID,PaperType=@PaperType,
     PerQtyType=@PerQtyType,RollWidth=@RollWidth,RollLength=@RollLength, 
     RollStandards=@RollStandards,DepartmentID=@DepartmentID, InkYieldStandards=@InkYieldStandards,
     PerQtyPrice=@PerQtyPrice, PackPrice=@PackPrice, Region=@Region ,isDisabled=@isDisabled,
     AlternateName=@AlternateName, InkStandards=@InkStandards, BarCode=@BarCode
     --,tbl_stockitems.Image=@Image1,tbl_stockitems.Thumbnail = @Thumbnail
     where Stockitemid=@ItemID
	RETURN