CREATE TABLE [dbo].[Campaign] (
    [CampaignId]                    BIGINT        IDENTITY (1, 1) NOT NULL,
    [CampaignName]                  VARCHAR (255) NULL,
    [Description]                   VARCHAR (255) NULL,
    [DataSourceType]                INT           CONSTRAINT [DF_tbl_campaigns_DataSourceType] DEFAULT ((0)) NULL,
    [RunCampaignFor]                SMALLINT      CONSTRAINT [DF_tbl_campaigns_RunCampaignFor] DEFAULT ((1)) NULL,
    [IncludeCustomers]              BIT           CONSTRAINT [DF_tbl_campaigns_IncludeCustomers] DEFAULT ((0)) NULL,
    [IncludeSuppliers]              BIT           CONSTRAINT [DF_tbl_campaigns_IncludeSuppliers] DEFAULT ((0)) NULL,
    [IncludeNewsLetterSubscribers]  BIT           NULL,
    [IncludeProspects]              BIT           CONSTRAINT [DF_tbl_campaigns_IncludeProspects] DEFAULT ((0)) NULL,
    [IncludeKeyword]                BIT           CONSTRAINT [DF_tbl_campaigns_IncludeKeyword] DEFAULT ((0)) NULL,
    [SearchKeyword]                 VARCHAR (200) NULL,
    [IncludeType]                   BIT           CONSTRAINT [DF_tbl_campaigns_IncludeType] DEFAULT ((0)) NULL,
    [IncludeFlag]                   BIT           CONSTRAINT [DF_tbl_campaigns_IncludeFlag] DEFAULT ((0)) NULL,
    [IncludeName]                   BIT           CONSTRAINT [DF_tbl_campaigns_IncludeName] DEFAULT ((0)) NULL,
    [IncludeAddress]                BIT           CONSTRAINT [DF_tbl_campaigns_IncluldeAddress] DEFAULT ((0)) NULL,
    [IncludeContactName]            BIT           CONSTRAINT [DF_tbl_campaigns_IncludeContactName] DEFAULT ((0)) NULL,
    [SubjectA]                      VARCHAR (255) NULL,
    [HTMLMessageA]                  NTEXT         NULL,
    [AttachmentFileNameFieldName]   VARCHAR (255) NULL,
    [AttachmentType]                VARCHAR (20)  NULL,
    [EmailField]                    VARCHAR (255) NULL,
    [CCEmailField]                  VARCHAR (255) NULL,
    [SMTPServer]                    VARCHAR (255) NULL,
    [FromAddress]                   VARCHAR (255) NULL,
    [ReturnPathAddress]             VARCHAR (255) NULL,
    [ReplyToAddress]                VARCHAR (255) NULL,
    [ErrorsToAddress]               VARCHAR (255) NULL,
    [SMTPServerType]                VARCHAR (255) NULL,
    [EnableSchedule]                BIT           CONSTRAINT [DF_tbl_campaigns_EnableSchedule] DEFAULT ((0)) NULL,
    [StartDateTime]                 DATETIME      NULL,
    [RepeatEvery]                   INT           NULL,
    [RepeatInterval]                VARCHAR (20)  NULL,
    [LastRunOn]                     DATETIME      NULL,
    [MessageType]                   SMALLINT      CONSTRAINT [DF_tbl_campaigns_MessageType] DEFAULT ((0)) NULL,
    [ABMessaging]                   BIT           CONSTRAINT [DF_tbl_campaigns_ABMessaging] DEFAULT ((0)) NULL,
    [SubjectB]                      VARCHAR (255) NULL,
    [HTMLMessageB]                  NTEXT         NULL,
    [IncludePlainText]              BIT           CONSTRAINT [DF_tbl_campaigns_IncludePlainText] DEFAULT ((0)) NULL,
    [SMTPDelaySeconds]              INT           CONSTRAINT [DF_tbl_campaigns_SMTPDelaySeconds] DEFAULT ((0)) NULL,
    [EmailAddressLogFiles]          BIT           CONSTRAINT [DF_tbl_campaigns_EmailAddressLogFiles] DEFAULT ((0)) NULL,
    [PlainTextMessageA]             NTEXT         NULL,
    [PlainTextMessageB]             NTEXT         NULL,
    [UId]                           INT           CONSTRAINT [DF_tbl_campaigns_UID] DEFAULT ((0)) NULL,
    [Private]                       BIT           CONSTRAINT [DF_tbl_campaigns_Private] DEFAULT ((1)) NULL,
    [SubscribeEmailUpdateField]     VARCHAR (255) NULL,
    [UnsubscribeEmailHyperlinkText] VARCHAR (255) NULL,
    [SubscribeEmailAddress]         VARCHAR (255) NULL,
    [SubscribeEmailHyperlinkText]   VARCHAR (255) NULL,
    [UnSubscribeCount]              BIGINT        CONSTRAINT [DF_tbl_campaigns_UnSubscribeCount] DEFAULT ((0)) NULL,
    [SubscribeCount]                BIGINT        CONSTRAINT [DF_tbl_campaigns_SubscribeCount] DEFAULT ((0)) NULL,
    [BounceCount]                   BIGINT        CONSTRAINT [DF_tbl_campaigns_BounceCount] DEFAULT ((0)) NULL,
    [LastRunEndDateTime]            DATETIME      NULL,
    [MessageCount]                  BIGINT        CONSTRAINT [DF_tbl_campaigns_MessageCount] DEFAULT ((0)) NULL,
    [SuccessCount]                  BIGINT        CONSTRAINT [DF_tbl_campaigns_SuccessCount] DEFAULT ((0)) NULL,
    [FailedCount]                   BIGINT        CONSTRAINT [DF_tbl_campaigns_FailedCount] DEFAULT ((0)) NULL,
    [EnableLogFiles]                BIT           CONSTRAINT [DF_tbl_campaigns_EnableLogFiles] DEFAULT ((0)) NULL,
    [ContinueIfWritebackError]      BIT           CONSTRAINT [DF_tbl_campaigns_ContinueIfWritebackError] DEFAULT ((0)) NULL,
    [EmailFieldPreviewColumn2]      VARCHAR (200) NULL,
    [EmailFieldPreviewColumn3]      VARCHAR (200) NULL,
    [AttachmentFileName]            VARCHAR (255) NULL,
    [ClearCounters]                 BIT           CONSTRAINT [DF_tbl_campaigns_ClearCounters] DEFAULT ((0)) NULL,
    [SMTPServer2]                   VARCHAR (255) NULL,
    [LockedByUID]                   INT           CONSTRAINT [DF_tbl_campaigns_LockedByUID] DEFAULT ((0)) NULL,
    [UnSubscribeCountTotal]         INT           CONSTRAINT [DF_tbl_campaigns_UnSubscribeCountTotal] DEFAULT ((0)) NULL,
    [SubscribeCountTotal]           INT           CONSTRAINT [DF_tbl_campaigns_SubscribeCountTotal] DEFAULT ((0)) NULL,
    [BounceCountTotal]              INT           CONSTRAINT [DF_tbl_campaigns_BounceCountTotal] DEFAULT ((0)) NULL,
    [EnableEmailAddressCache]       BIT           CONSTRAINT [DF_tbl_campaigns_EnableEmailAddressCache] DEFAULT ((0)) NULL,
    [OpenedCount]                   INT           CONSTRAINT [DF_tbl_campaigns_OpenedCount] DEFAULT ((0)) NULL,
    [OpenedCountTotal]              INT           NULL,
    [OpenedEmailUpdateField]        VARCHAR (255) NULL,
    [EnableOpenedEmail]             INT           CONSTRAINT [DF_tbl_campaigns_EnableOpenedEmail] DEFAULT ((0)) NULL,
    [ABMessagingUpdateField]        VARCHAR (255) NULL,
    [EmailLogFileAddress2]          VARCHAR (255) NULL,
    [EmailLogFileAddress3]          VARCHAR (255) NULL,
    [CampaignCategory]              VARCHAR (255) NULL,
    [SoftBounceCountTotal]          INT           CONSTRAINT [DF_tbl_campaigns_SoftBounceCountTotal] DEFAULT ((0)) NULL,
    [SMTPUsername]                  VARCHAR (255) NULL,
    [SMTPPassword]                  VARCHAR (255) NULL,
    [EnableWriteBackTab]            BIT           CONSTRAINT [DF_tbl_campaigns_EnableWriteBackTab] DEFAULT ((0)) NULL,
    [EnableClickThruTab]            BIT           CONSTRAINT [DF_tbl_campaigns_EnableClickThruTab] DEFAULT ((0)) NULL,
    [UnsubscribeMethod]             VARCHAR (20)  NULL,
    [UseWYSWYG]                     BIT           CONSTRAINT [DF_tbl_campaigns_UseWYSWYG] DEFAULT ((0)) NULL,
    [CreationDate]                  DATETIME      NULL,
    [Status]                        INT           CONSTRAINT [DF_tbl_campaigns_Status] DEFAULT ((0)) NULL,
    [ValidateEmail]                 BIT           CONSTRAINT [DF_tbl_campaigns_ValidateEmail] DEFAULT ((1)) NOT NULL,
    [CampaignType]                  SMALLINT      CONSTRAINT [DF_tbl_campaigns_CampaignType] DEFAULT ((0)) NULL,
    [SystemSiteId]                  INT           NULL,
    [IncludeCorporateCustomers]     BIT           NULL,
    [IsEnabled]                     BIT           NULL,
    [SendEmailAfterDays]            INT           NULL,
    [EmailEvent]                    INT           NULL,
    [isSystemEmail]                 BIT           NULL,
    [FlagIDs]                       VARCHAR (500) NULL,
    [CustomerTypeIDs]               VARCHAR (500) NULL,
    [GroupIDs]                      VARCHAR (500) NULL,
    [FromName]                      VARCHAR (500) NULL,
    [CampaignReportId]              INT           NULL,
    [OrganisationId]                BIGINT        NULL,
    [CompanyId]                     BIGINT        NULL,
    [UnsubscribeEmailAddress]       VARCHAR (255) NULL,
    CONSTRAINT [PK_tbl_campaigns] PRIMARY KEY CLUSTERED ([CampaignId] ASC),
    CONSTRAINT [FK_Company_Campaign] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Company] ([CompanyId]),
    CONSTRAINT [FK_EventEmail_Campaign] FOREIGN KEY ([EmailEvent]) REFERENCES [dbo].[EmailEvent] ([EmailEventId])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Flag Used to hold Campaign Type i.e Fax or Email ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Campaign', @level2type = N'COLUMN', @level2name = N'CampaignType';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'1 For Contact,Address - 2 for Groups', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Campaign', @level2type = N'COLUMN', @level2name = N'RunCampaignFor';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Enumeration will be used to distinguish that is it an internal contact search or any external database.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Campaign', @level2type = N'COLUMN', @level2name = N'DataSourceType';

