CREATE TABLE [dbo].[CmsPage] (
    [PageId]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [PageName]                      NVARCHAR (200)  NULL,
    [PageTitle]                     NVARCHAR (100)  NULL,
    [MenuTitle]                     NVARCHAR (100)  NULL,
    [description]                   NVARCHAR (500)  NULL,
    [PageRelativePath]              NVARCHAR (200)  NULL,
    [SortOrder]                     INT             NULL,
    [Meta_KeywordContent]           NTEXT           NULL,
    [Meta_DescriptionContent]       NVARCHAR (500)  NULL,
    [Meta_HiddenDescriptionContent] NVARCHAR (500)  NULL,
    [Meta_CategoryContent]          NVARCHAR (500)  NULL,
    [Meta_RobotsContent]            NVARCHAR (500)  NULL,
    [Meta_AuthorContent]            VARCHAR (100)   NULL,
    [Meta_DateContent]              VARCHAR (50)    NULL,
    [Meta_LanguageContent]          VARCHAR (50)    NULL,
    [Meta_RevisitAfterContent]      VARCHAR (50)    NULL,
    [Meta_Title]                    VARCHAR (150)   NULL,
    [PageHTML]                      VARCHAR (MAX)   NULL,
    [isUserDefined]                 BIT             CONSTRAINT [DF_webcmsPages_isUserDefined] DEFAULT ((0)) NULL,
    [CategoryId]                    BIGINT          NULL,
    [isPromotionalOffer]            BIT             CONSTRAINT [DF__webcmsPag__isPro__7B67D5F1] DEFAULT ((1)) NULL,
    [isSepecialOffer]               BIT             CONSTRAINT [DF__webcmsPag__isSep__7C5BFA2A] DEFAULT ((1)) NULL,
    [isMPCAdd]                      BIT             CONSTRAINT [DF__webcmsPag__isMPC__7D501E63] DEFAULT ((1)) NULL,
    [LastModifiedDate]              DATETIME        NULL,
    [PageBanner]                    NVARCHAR (200)  NULL,
    [PageKeywords]                  NVARCHAR (1000) NULL,
    [isEnabled]                     BIT             NULL,
    [isDisplay]                     BIT             NULL,
    [CompanyId]                     BIGINT          NULL,
    [OrganisationId]                BIGINT          NULL,
    CONSTRAINT [PK_webcmsPages] PRIMARY KEY CLUSTERED ([PageId] ASC),
    CONSTRAINT [FK_PageCategory_CmsPage] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[PageCategory] ([CategoryId]),
    CONSTRAINT [FK_webcmsPages_tbl_cmsPageCategory] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Company] ([CompanyId])
);

