CREATE TABLE [dbo].[CompanyContact] (
    [ContactId]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [AddressId]                        BIGINT          CONSTRAINT [DF__tbl_custo__Addre__2739D489] DEFAULT ((0)) NOT NULL,
    [CompanyId]                        BIGINT          NOT NULL,
    [FirstName]                        VARCHAR (50)    NULL,
    [MiddleName]                       VARCHAR (50)    NULL,
    [LastName]                         VARCHAR (50)    NULL,
    [Title]                            VARCHAR (20)    NULL,
    [HomeTel1]                         VARCHAR (30)    NULL,
    [HomeTel2]                         VARCHAR (30)    NULL,
    [HomeExtension1]                   VARCHAR (7)     NULL,
    [HomeExtension2]                   VARCHAR (7)     NULL,
    [Mobile]                           VARCHAR (30)    NULL,
    [Email]                            VARCHAR (100)   NULL,
    [FAX]                              VARCHAR (30)    NULL,
    [JobTitle]                         VARCHAR (50)    NULL,
    [DOB]                              DATETIME        NULL,
    [Notes]                            NVARCHAR (3000) NULL,
    [IsDefaultContact]                 INT             CONSTRAINT [DF__tbl_custo__IsDef__29221CFB] DEFAULT ((1)) NULL,
    [HomeAddress1]                     VARCHAR (255)   NULL,
    [HomeAddress2]                     VARCHAR (255)   NULL,
    [HomeCity]                         VARCHAR (30)    NULL,
    [HomeState]                        VARCHAR (30)    NULL,
    [HomePostCode]                     VARCHAR (30)    NULL,
    [HomeCountry]                      VARCHAR (50)    NULL,
    [SecretQuestion]                   VARCHAR (200)   NULL,
    [SecretAnswer]                     VARCHAR (200)   NULL,
    [Password]                         VARCHAR (200)   NULL,
    [URL]                              VARCHAR (100)   NULL,
    [IsEmailSubscription]              BIT             NULL,
    [IsNewsLetterSubscription]         BIT             NULL,
    [image]                            VARCHAR (200)   NULL,
    [quickFullName]                    VARCHAR (200)   NULL,
    [quickTitle]                       VARCHAR (50)    NULL,
    [quickCompanyName]                 VARCHAR (200)   NULL,
    [quickAddress1]                    VARCHAR (255)   NULL,
    [quickAddress2]                    VARCHAR (255)   NULL,
    [quickAddress3]                    VARCHAR (255)   NULL,
    [quickPhone]                       VARCHAR (20)    NULL,
    [quickFax]                         VARCHAR (20)    NULL,
    [quickEmail]                       VARCHAR (200)   NULL,
    [quickWebsite]                     VARCHAR (200)   NULL,
    [quickCompMessage]                 VARCHAR (1000)  NULL,
    [QuestionId]                       INT             NULL,
    [IsApprover]                       BIT             CONSTRAINT [DF_tbl_contacts_IsApprover] DEFAULT ((0)) NULL,
    [isWebAccess]                      BIT             NULL,
    [isPlaceOrder]                     BIT             NULL,
    [CreditLimit]                      DECIMAL (16)    NULL,
    [isArchived]                       BIT             NULL,
    [ContactRoleId]                    INT             NULL,
    [TerritoryId]                      BIGINT          NULL,
    [ClaimIdentifer]                   VARCHAR (100)   NULL,
    [AuthentifiedBy]                   VARCHAR (50)    NULL,
    [IsPayByPersonalCreditCard]        BIT             NULL,
    [IsPricingshown]                   BIT             NULL,
    [SkypeId]                          VARCHAR (100)   NULL,
    [LinkedinURL]                      VARCHAR (200)   NULL,
    [FacebookURL]                      VARCHAR (255)   NULL,
    [TwitterURL]                       VARCHAR (255)   NULL,
    [authenticationToken]              VARCHAR (200)   NULL,
    [twitterScreenName]                VARCHAR (200)   NULL,
    [ShippingAddressId]                BIGINT          NULL,
    [isUserLoginFirstTime]             BIT             NULL,
    [quickMobileNumber]                VARCHAR (30)    NULL,
    [quickTwitterId]                   VARCHAR (150)   NULL,
    [quickFacebookId]                  VARCHAR (150)   NULL,
    [quickLinkedInId]                  VARCHAR (150)   NULL,
    [quickOtherId]                     VARCHAR (150)   NULL,
    [POBoxAddress]                     NVARCHAR (500)  NULL,
    [CorporateUnit]                    NVARCHAR (500)  NULL,
    [OfficeTradingName]                NVARCHAR (500)  NULL,
    [ContractorName]                   NVARCHAR (500)  NULL,
    [BPayCRN]                          NVARCHAR (500)  NULL,
    [ABN]                              NVARCHAR (500)  NULL,
    [ACN]                              NVARCHAR (500)  NULL,
    [AdditionalField1]                 NVARCHAR (500)  NULL,
    [AdditionalField2]                 NVARCHAR (500)  NULL,
    [AdditionalField3]                 NVARCHAR (500)  NULL,
    [AdditionalField4]                 NVARCHAR (500)  NULL,
    [AdditionalField5]                 NVARCHAR (500)  NULL,
    [canUserPlaceOrderWithoutApproval] BIT             NULL,
    [CanUserEditProfile]               BIT             NULL,
    [canPlaceDirectOrder]              BIT             NULL,
    [OrganisationId]                   BIGINT          NULL,
    CONSTRAINT [PK_tbl_customercontacts] PRIMARY KEY CLUSTERED ([ContactId] ASC),
    CONSTRAINT [FK_CompanyContact_ShippingAddress] FOREIGN KEY ([ShippingAddressId]) REFERENCES [dbo].[Address] ([AddressId]),
    CONSTRAINT [FK_tbl_contacts_tbl_addresses] FOREIGN KEY ([AddressId]) REFERENCES [dbo].[Address] ([AddressId]),
    CONSTRAINT [FK_tbl_contacts_tbl_contactcompanies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Company] ([CompanyId]),
    CONSTRAINT [FK_tbl_contacts_tbl_ContactCompanyTerritories] FOREIGN KEY ([TerritoryId]) REFERENCES [dbo].[CompanyTerritory] ([TerritoryId]),
    CONSTRAINT [FK_tbl_contacts_tbl_contactcompanyuserroles] FOREIGN KEY ([ContactRoleId]) REFERENCES [dbo].[CompanyContactRole] ([ContactRoleId]),
    CONSTRAINT [FK_tbl_contacts_tbl_Registration_Questions] FOREIGN KEY ([QuestionId]) REFERENCES [dbo].[RegistrationQuestion] ([QuestionId])
);


GO
CREATE NONCLUSTERED INDEX [CustomerID]
    ON [dbo].[CompanyContact]([CompanyId] ASC);

