CREATE TABLE [dbo].[Company] (
    [CompanyId]                                  BIGINT           IDENTITY (1, 1) NOT NULL,
    [StoreId]                                    BIGINT           NULL,
    [AccountNumber]                              VARCHAR (10)     NULL,
    [Name]                                       VARCHAR (100)    NULL,
    [URL]                                        VARCHAR (150)    NULL,
    [CreditReference]                            VARCHAR (50)     NULL,
    [CreditLimit]                                FLOAT (53)       CONSTRAINT [DF__tbl_custo__Credi__2BFE89A6] DEFAULT ((0)) NULL,
    [Terms]                                      NVARCHAR (3000)  NULL,
    [TypeId]                                     BIGINT           CONSTRAINT [DF__tbl_custo__Custo__2CF2ADDF] DEFAULT ((0)) NOT NULL,
    [DefaultNominalCode]                         INT              CONSTRAINT [DF__tbl_custo__Defau__2DE6D218] DEFAULT ((0)) NOT NULL,
    [DefaultMarkUpId]                            INT              CONSTRAINT [DF__tbl_custo__Defau__2FCF1A8A] DEFAULT ((0)) NOT NULL,
    [AccountOpenDate]                            DATETIME         NULL,
    [AccountManagerId]                           INT              CONSTRAINT [DF__tbl_custo__Accou__30C33EC3] DEFAULT ((0)) NOT NULL,
    [Status]                                     SMALLINT         CONSTRAINT [DF__tbl_custo__Custo__31B762FC] DEFAULT ((0)) NOT NULL,
    [IsCustomer]                                 SMALLINT         CONSTRAINT [DF__tbl_custo__IsCus__32AB8735] DEFAULT ((0)) NOT NULL,
    [Notes]                                      NVARCHAR (3000)  NULL,
    [NotesLastUpdatedDate]                       DATETIME         NULL,
    [NotesLastUpdatedBy]                         INT              NULL,
    [AccountStatusId]                            SMALLINT         CONSTRAINT [DF__tbl_custo__Accou__339FAB6E] DEFAULT ((0)) NOT NULL,
    [IsDisabled]                                 SMALLINT         CONSTRAINT [DF__tbl_custo__IsDis__3493CFA7] DEFAULT ((0)) NOT NULL,
    [LockedBy]                                   INT              CONSTRAINT [DF__tbl_custo__Locke__3587F3E0] DEFAULT ((0)) NOT NULL,
    [AccountBalance]                             FLOAT (53)       CONSTRAINT [DF__tbl_custo__Accou__367C1819] DEFAULT ((0)) NOT NULL,
    [CreationDate]                               DATETIME         NULL,
    [VATRegNumber]                               VARCHAR (50)     NULL,
    [VATRegReference]                            VARCHAR (50)     NULL,
    [FlagId]                                     INT              CONSTRAINT [DF__tbl_custo__FlagI__3A4CA8FD] DEFAULT ((0)) NOT NULL,
    [PhoneNo]                                    NVARCHAR (3000)  NULL,
    [IsGeneral]                                  SMALLINT         CONSTRAINT [DF__tbl_custo__IsGen__3F115E1A] DEFAULT ((0)) NULL,
    [SalesPerson]                                INT              NULL,
    [Image]                                      VARCHAR (200)    NULL,
    [WebAccessCode]                              VARCHAR (50)     NULL,
    [isArchived]                                 BIT              NULL,
    [PayByPersonalCredeitCard]                   BIT              NULL,
    [PONumberRequired]                           BIT              NULL,
    [ShowPrices]                                 BIT              NULL,
    [CarrierWebPath]                             VARCHAR (200)    NULL,
    [CarrierTrackingPath]                        VARCHAR (200)    NULL,
    [CorporateOrderingPolicy]                    NVARCHAR (MAX)   NULL,
    [isDisplaySiteHeader]                        BIT              NULL,
    [isDisplayMenuBar]                           BIT              NULL,
    [isDisplayBanners]                           BIT              NULL,
    [isDisplayFeaturedProducts]                  BIT              NULL,
    [isDisplayPromotionalProducts]               BIT              NULL,
    [isDisplayChooseUsIcons]                     BIT              NULL,
    [isDisplaySecondaryPages]                    BIT              NULL,
    [isDisplaySiteFooter]                        BIT              NULL,
    [RedirectWebstoreURL]                        VARCHAR (500)    NULL,
    [defaultPalleteId]                           INT              NULL,
    [isDisplaylBrokerBanners]                    BIT              NULL,
    [isBrokerCanLaminate]                        BIT              NULL,
    [isBrokerCanRoundCorner]                     BIT              NULL,
    [isBrokerCanDeliverSameDay]                  BIT              NULL,
    [isBrokerCanAcceptPaymentOnline]             BIT              NULL,
    [isBrokerOrderApprovalRequired]              BIT              NULL,
    [isBrokerPaymentRequired]                    BIT              NULL,
    [isWhiteLabel]                               BIT              NULL,
    [TwitterURL]                                 VARCHAR (100)    NULL,
    [FacebookURL]                                VARCHAR (200)    NULL,
    [LinkedinURL]                                VARCHAR (200)    NULL,
    [WebMasterTag]                               NVARCHAR (MAX)   NULL,
    [WebAnalyticCode]                            NVARCHAR (MAX)   NULL,
    [isShowGoogleMap]                            INT              NULL,
    [isTextWatermark]                            BIT              NULL,
    [WatermarkText]                              VARCHAR (100)    NULL,
    [CoreCustomerId]                             INT              NULL,
    [StoreBackgroundImage]                       VARCHAR (200)    NULL,
    [isDisplayBrokerSecondaryPages]              BIT              NULL,
    [PriceFlagId]                                INT              NULL,
    [isIncludeVAT]                               BIT              NULL,
    [isAllowRegistrationFromWeb]                 BIT              NULL,
    [MarketingBriefRecipient]                    VARCHAR (100)    NULL,
    [isLoginFirstTime]                           BIT              NULL,
    [facebookAppId]                              VARCHAR (200)    NULL,
    [facebookAppKey]                             VARCHAR (200)    NULL,
    [twitterAppId]                               VARCHAR (200)    NULL,
    [twitterAppKey]                              VARCHAR (200)    NULL,
    [isStoreModePrivate]                         BIT              NULL,
    [CustomCSS]                                  VARCHAR (MAX)    NULL,
    [TaxPercentageId]                            INT              NULL,
    [XeroAccessCode]                             VARCHAR (50)     NULL,
    [canUserPlaceOrderWithoutApproval]           BIT              NULL,
    [CanUserEditProfile]                         BIT              NULL,
    [OrganisationId]                             BIGINT           NULL,
    [includeEmailBrokerArtworkOrderReport]       BIT              NULL,
    [includeEmailBrokerArtworkOrderXML]          BIT              NULL,
    [includeEmailBrokerArtworkOrderJobCard]      BIT              NULL,
    [makeEmailBrokerArtworkOrderProductionReady] BIT              NULL,
    [SalesAndOrderManagerId1]                    UNIQUEIDENTIFIER NULL,
    [SalesAndOrderManagerId2]                    UNIQUEIDENTIFIER NULL,
    [ProductionManagerId1]                       UNIQUEIDENTIFIER NULL,
    [ProductionManagerId2]                       UNIQUEIDENTIFIER NULL,
    [StockNotificationManagerId1]                UNIQUEIDENTIFIER NULL,
    [StockNotificationManagerId2]                UNIQUEIDENTIFIER NULL,
    [IsDeliveryTaxAble]                          BIT              NULL,
    [IsDisplayDeliveryOnCheckout]                BIT              NULL,
    [DeliveryPickUpAddressId]                    BIGINT           NULL,
    [TaxRate]                                    FLOAT (53)       NULL,
    [IsDisplayDiscountVoucherCode]               BIT              NULL,
    [IsDisplayCorporateBinding]                  BIT              NULL,
    [MapImageURL]                                VARCHAR (200)    NULL,
    [PickupAddressId]                            BIGINT           NULL,
    [TaxLabel]                                   VARCHAR (30)     NULL,
    [isAddCropMarks]                             BIT              NULL,
    [isCalculateTaxByService]                    BIT              NULL,
    CONSTRAINT [PK_tbl_contactcompanies] PRIMARY KEY CLUSTERED ([CompanyId] ASC),
    CONSTRAINT [FK_tbl_contactcompanies_tbl_contactcompanytypes] FOREIGN KEY ([TypeId]) REFERENCES [dbo].[CompanyType] ([TypeId])
);

