CREATE TABLE [dbo].[CostCentre] (
    [CostCentreId]                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [Name]                          VARCHAR (100)  NOT NULL,
    [Description]                   VARCHAR (250)  NULL,
    [Type]                          INT            NOT NULL,
    [CreatedBy]                     INT            NULL,
    [LockedBy]                      VARCHAR (30)   NULL,
    [LastModifiedBy]                VARCHAR (30)   NULL,
    [MinimumCost]                   FLOAT (53)     NULL,
    [SetupCost]                     FLOAT (53)     NULL,
    [SetupTime]                     INT            NULL,
    [DefaultVA]                     FLOAT (53)     NULL,
    [DefaultVAId]                   INT            NOT NULL,
    [OverHeadRate]                  FLOAT (53)     NULL,
    [HourlyCharge]                  FLOAT (53)     NULL,
    [CostPerThousand]               FLOAT (53)     NULL,
    [CreationDate]                  DATETIME       NULL,
    [LastModifiedDate]              DATETIME       NULL,
    [PreferredSupplierId]           INT            NULL,
    [CodeFileName]                  VARCHAR (50)   NULL,
    [nominalCode]                   INT            NULL,
    [CompletionTime]                INT            NULL,
    [HeaderCode]                    TEXT           NULL,
    [MiddleCode]                    TEXT           NULL,
    [FooterCode]                    TEXT           NULL,
    [strCostPlantParsed]            TEXT           NULL,
    [strCostPlantUnParsed]          TEXT           NULL,
    [strCostLabourParsed]           TEXT           NULL,
    [strCostLabourUnParsed]         TEXT           NULL,
    [strCostMaterialParsed]         TEXT           NULL,
    [strCostMaterialUnParsed]       TEXT           NULL,
    [strPricePlantParsed]           TEXT           NULL,
    [strPricePlantUnParsed]         TEXT           NULL,
    [strPriceLabourParsed]          TEXT           NULL,
    [strPriceLabourUnParsed]        TEXT           NULL,
    [strPriceMaterialParsed]        TEXT           NULL,
    [strPriceMaterialUnParsed]      TEXT           NULL,
    [strActualCostPlantParsed]      TEXT           NULL,
    [strActualCostPlantUnParsed]    TEXT           NULL,
    [strActualCostLabourParsed]     TEXT           NULL,
    [strActualCostLabourUnParsed]   TEXT           NULL,
    [strActualCostMaterialParsed]   TEXT           NULL,
    [strActualCostMaterialUnParsed] TEXT           NULL,
    [strTimeParsed]                 TEXT           NULL,
    [strTimeUnParsed]               TEXT           NULL,
    [IsDisabled]                    SMALLINT       NOT NULL,
    [IsDirectCost]                  SMALLINT       NOT NULL,
    [SetupSpoilage]                 INT            NOT NULL,
    [RunningSpoilage]               FLOAT (53)     NOT NULL,
    [CalculationMethodType]         INT            NOT NULL,
    [NoOfHours]                     INT            NULL,
    [PerHourCost]                   FLOAT (53)     NULL,
    [PerHourPrice]                  FLOAT (53)     NULL,
    [UnitQuantity]                  INT            NULL,
    [QuantitySourceType]            INT            NULL,
    [QuantityVariableId]            INT            NULL,
    [QuantityQuestionString]        VARCHAR (150)  NULL,
    [QuantityQuestionDefaultValue]  FLOAT (53)     NOT NULL,
    [QuantityCalculationString]     TEXT           NULL,
    [CostPerUnitQuantity]           FLOAT (53)     NULL,
    [PricePerUnitQuantity]          FLOAT (53)     NULL,
    [TimePerUnitQuantity]           FLOAT (53)     NULL,
    [TimeRunSpeed]                  INT            NOT NULL,
    [TimeNoOfPasses]                INT            NOT NULL,
    [TimeSourceType]                INT            NULL,
    [TimeVariableId]                INT            NULL,
    [TimeQuestionString]            VARCHAR (150)  NULL,
    [TimeQuestionDefaultValue]      FLOAT (53)     NOT NULL,
    [TimeCalculationString]         TEXT           NULL,
    [Priority]                      INT            NULL,
    [CostQuestionString]            VARCHAR (150)  NULL,
    [CostDefaultValue]              FLOAT (53)     NULL,
    [PriceQuestionString]           VARCHAR (150)  NULL,
    [PriceDefaultValue]             FLOAT (53)     NULL,
    [EstimatedTimeQuestionString]   VARCHAR (150)  NULL,
    [EstimatedTimeDefaultValue]     INT            NULL,
    [Sequence]                      INT            NOT NULL,
    [CompleteCode]                  TEXT           NULL,
    [ItemDescription]               TEXT           NULL,
    [SystemTypeId]                  INT            NULL,
    [FlagId]                        INT            NULL,
    [IsScheduleable]                SMALLINT       NOT NULL,
    [SystemSiteId]                  INT            NOT NULL,
    [IsPrintOnJobCard]              SMALLINT       NOT NULL,
    [WebStoreDesc]                  VARCHAR (250)  NULL,
    [isPublished]                   BIT            CONSTRAINT [DF__tbl_costc__isPub__5EB688AA] DEFAULT ((0)) NULL,
    [EstimateProductionTime]        DECIMAL (8, 2) NULL,
    [MainImageURL]                  VARCHAR (200)  NULL,
    [ThumbnailImageURL]             VARCHAR (200)  NULL,
    [isOption1]                     BIT            NULL,
    [isOption2]                     BIT            NULL,
    [isOption3]                     BIT            NULL,
    [TextOption1]                   VARCHAR (255)  NULL,
    [TextOption2]                   VARCHAR (255)  NULL,
    [TextOption3]                   VARCHAR (255)  NULL,
    [CCIDOption1]                   INT            NULL,
    [CCIDOption2]                   INT            NULL,
    [CCIDOption3]                   INT            NULL,
    [SetupCharge2]                  FLOAT (53)     NULL,
    [SetupCharge3]                  FLOAT (53)     NULL,
    [MinimumCost2]                  FLOAT (53)     NULL,
    [MinimumCost3]                  FLOAT (53)     NULL,
    [PricePerUnitQuantity2]         FLOAT (53)     NULL,
    [PricePerUnitQuantity3]         FLOAT (53)     NULL,
    [QuantityVariableID2]           INT            NULL,
    [QuantityVariableID3]           INT            NULL,
    [QuantitySourceType2]           INT            NULL,
    [QuantitySourceType3]           INT            NULL,
    [QuantityQuestionString2]       VARCHAR (150)  NULL,
    [QuantityQuestionString3]       VARCHAR (150)  NULL,
    [QuantityQuestionDefaultValue2] FLOAT (53)     NULL,
    [QuantityQuestionDefaultValue3] FLOAT (53)     NULL,
    [DefaultVAId2]                  INT            NULL,
    [DefaultVAId3]                  INT            NULL,
    [IsPrintOnJobCard2]             BIT            NULL,
    [IsPrintOnJobCard3]             BIT            NULL,
    [IsDirectCost2]                 BIT            NULL,
    [IsDirectCost3]                 BIT            NULL,
    [PreferredSupplierID2]          INT            NULL,
    [PreferredSupplierID3]          INT            NULL,
    [EstimateProductionTime2]       DECIMAL (8, 2) NULL,
    [EstimateProductionTime3]       DECIMAL (8, 2) NULL,
    [DeliveryCharges]               FLOAT (53)     NULL,
    [isFromMIS]                     BIT            NULL,
    [XeroAccessCode]                VARCHAR (50)   NULL,
    [OrganisationId]                BIGINT         NULL,
    [DeliveryType]                  INT            NULL,
    [DeliveryServiceType]           VARCHAR (150)  NULL,
    CONSTRAINT [PK_tbl_costcentres] PRIMARY KEY CLUSTERED ([CostCentreId] ASC),
    CONSTRAINT [FK_tbl_costcentres_tbl_costcentretypes] FOREIGN KEY ([Type]) REFERENCES [dbo].[CostCentreType] ([TypeId])
);

