CREATE TABLE [dbo].[DeliveryNote] (
    [DeliveryNoteId]       INT           IDENTITY (1, 1) NOT NULL,
    [Code]                 VARCHAR (20)  NULL,
    [DeliveryDate]         DATETIME      NULL,
    [ContactCompanyId]     INT           NULL,
    [OrderReff]            VARCHAR (50)  NULL,
    [footnote]             VARCHAR (255) NULL,
    [Comments]             VARCHAR (255) NULL,
    [LockedBy]             INT           NULL,
    [IsStatus]             SMALLINT      NULL,
    [ContactId]            BIGINT        NULL,
    [ContactCompany]       VARCHAR (50)  NULL,
    [CustomerOrderReff]    VARCHAR (100) NULL,
    [AddressId]            INT           CONSTRAINT [DF__tbl_deliv__Addre__5CA1C101] DEFAULT (0) NULL,
    [CreatedBy]            INT           NULL,
    [CreationDateTime]     DATETIME      NULL,
    [SupplierId]           INT           NULL,
    [SupplierTelNo]        VARCHAR (50)  NULL,
    [CsNo]                 VARCHAR (50)  NULL,
    [SupplierURL]          VARCHAR (50)  NULL,
    [RaisedBy]             INT           CONSTRAINT [DF__tbl_deliv__Raise__5D95E53A] DEFAULT (0) NOT NULL,
    [FlagId]               INT           NULL,
    [EstimateId]           INT           NULL,
    [JobId]                INT           NULL,
    [InvoiceId]            INT           NULL,
    [OrderId]              INT           NULL,
    [UserNotes]            TEXT          NULL,
    [NotesUpdateDateTime]  DATETIME      NULL,
    [NotesUpdatedByUserId] INT           NULL,
    [SystemSiteId]         INT           NULL,
    [IsRead]               BIT           CONSTRAINT [DF_tbl_deliverynotes_IsRead] DEFAULT (0) NULL,
    [IsPrinted]            BIT           NULL,
    CONSTRAINT [PK_tbl_deliverynotes] PRIMARY KEY CLUSTERED ([DeliveryNoteId] ASC)
);

