CREATE TABLE [dbo].[ItemSection] (
    [ItemSectionId]                    BIGINT       IDENTITY (1, 1) NOT NULL,
    [SectionNo]                        INT          CONSTRAINT [DF__tbl_item___Secti__0662F0A3] DEFAULT ((0)) NULL,
    [SectionName]                      VARCHAR (50) NULL,
    [IsMainSection]                    BIT          NULL,
    [IsMultipleQty]                    BIT          NULL,
    [IsRunOnQty]                       BIT          NULL,
    [ItemId]                           BIGINT       CONSTRAINT [DF__tbl_item___ItemI__093F5D4E] DEFAULT ((0)) NULL,
    [Qty1]                             INT          CONSTRAINT [DF__tbl_item_s__Qty1__0A338187] DEFAULT ((0)) NULL,
    [Qty2]                             INT          CONSTRAINT [DF__tbl_item_s__Qty2__0B27A5C0] DEFAULT ((0)) NULL,
    [Qty3]                             INT          CONSTRAINT [DF__tbl_item_s__Qty3__0C1BC9F9] DEFAULT ((0)) NULL,
    [Qty4]                             INT          CONSTRAINT [DF__tbl_item_s__Qty4__0D0FEE32] DEFAULT ((0)) NULL,
    [Qty5]                             INT          CONSTRAINT [DF__tbl_item_s__Qty5__0E04126B] DEFAULT ((0)) NULL,
    [Qty1Profit]                       FLOAT (53)   NULL,
    [Qty2Profit]                       FLOAT (53)   NULL,
    [Qty3Profit]                       FLOAT (53)   NULL,
    [Qty4Profit]                       FLOAT (53)   NULL,
    [Qty5Profit]                       FLOAT (53)   NULL,
    [BaseCharge1]                      FLOAT (53)   CONSTRAINT [DF__tbl_item___BaseC__0EF836A4] DEFAULT ((0)) NULL,
    [BaseCharge2]                      FLOAT (53)   CONSTRAINT [DF__tbl_item___BaseC__0FEC5ADD] DEFAULT ((0)) NULL,
    [Basecharge3]                      FLOAT (53)   CONSTRAINT [DF__tbl_item___Basec__10E07F16] DEFAULT ((0)) NULL,
    [BaseCharge4]                      FLOAT (53)   CONSTRAINT [DF__tbl_item___BaseC__11D4A34F] DEFAULT ((0)) NULL,
    [BaseCharge5]                      FLOAT (53)   CONSTRAINT [DF__tbl_item___BaseC__12C8C788] DEFAULT ((0)) NULL,
    [RunOnQty]                         INT          CONSTRAINT [DF__tbl_item___RunOn__13BCEBC1] DEFAULT ((0)) NULL,
    [RunOnBaseCharge]                  FLOAT (53)   NULL,
    [RunonProfit]                      FLOAT (53)   NULL,
    [SectionSizeId]                    INT          CONSTRAINT [DF__tbl_item___Secti__14B10FFA] DEFAULT ((0)) NULL,
    [IsSectionSizeCustom]              BIT          NULL,
    [SectionSizeHeight]                FLOAT (53)   CONSTRAINT [DF__tbl_item___Secti__1699586C] DEFAULT ((0)) NULL,
    [SectionSizeWidth]                 FLOAT (53)   CONSTRAINT [DF__tbl_item___Secti__178D7CA5] DEFAULT ((0)) NULL,
    [ItemSizeId]                       INT          CONSTRAINT [DF__tbl_item___ItemS__1881A0DE] DEFAULT ((0)) NULL,
    [IsItemSizeCustom]                 BIT          NULL,
    [ItemSizeHeight]                   FLOAT (53)   CONSTRAINT [DF__tbl_item___ItemS__1A69E950] DEFAULT ((0)) NULL,
    [ItemSizeWidth]                    FLOAT (53)   CONSTRAINT [DF__tbl_item___ItemS__1B5E0D89] DEFAULT ((0)) NULL,
    [GuillotineId]                     INT          CONSTRAINT [DF__tbl_item___Guill__1C5231C2] DEFAULT ((0)) NULL,
    [IncludeGutter]                    BIT          NULL,
    [PressId]                          INT          CONSTRAINT [DF__tbl_item___Press__1E3A7A34] DEFAULT ((0)) NULL,
    [FilmId]                           INT          CONSTRAINT [DF__tbl_item___FilmI__1F2E9E6D] DEFAULT ((0)) NULL,
    [PlateId]                          INT          CONSTRAINT [DF__tbl_item___Plate__2022C2A6] DEFAULT ((0)) NULL,
    [ItemGutterHorizontal]             FLOAT (53)   CONSTRAINT [DF__tbl_item___ItemG__2116E6DF] DEFAULT ((0)) NULL,
    [ItemGutterVertical]               FLOAT (53)   CONSTRAINT [DF__tbl_item___ItemG__220B0B18] DEFAULT ((0)) NULL,
    [IsPressrestrictionApplied]        BIT          NULL,
    [IsDoubleSided]                    BIT          NULL,
    [IsWashup]                         BIT          NULL,
    [PrintViewLayoutLandScape]         INT          CONSTRAINT [DF__tbl_item___Print__25DB9BFC] DEFAULT ((0)) NULL,
    [PrintViewLayoutPortrait]          INT          CONSTRAINT [DF__tbl_item___Print__26CFC035] DEFAULT ((0)) NULL,
    [PrintViewLayout]                  INT          CONSTRAINT [DF__tbl_item___Print__27C3E46E] DEFAULT ((0)) NULL,
    [SetupSpoilage]                    INT          NULL,
    [RunningSpoilage]                  INT          NULL,
    [RunningSpoilageValue]             INT          NULL,
    [EstimateForWholePacks]            INT          CONSTRAINT [DF__tbl_item___Estim__28B808A7] DEFAULT ((0)) NULL,
    [IsFirstTrim]                      BIT          NULL,
    [IsSecondTrim]                     BIT          NULL,
    [PaperQty]                         INT          CONSTRAINT [DF__tbl_item___Paper__2B947552] DEFAULT ((0)) NULL,
    [ImpressionQty1]                   INT          CONSTRAINT [DF__tbl_item___Impre__2C88998B] DEFAULT ((0)) NULL,
    [ImpressionQty2]                   INT          CONSTRAINT [DF__tbl_item___Impre__2D7CBDC4] DEFAULT ((0)) NULL,
    [ImpressionQty3]                   INT          CONSTRAINT [DF__tbl_item___Impre__2E70E1FD] DEFAULT ((0)) NULL,
    [ImpressionQty4]                   INT          CONSTRAINT [DF__tbl_item___Impre__2F650636] DEFAULT ((0)) NULL,
    [ImpressionQty5]                   INT          CONSTRAINT [DF__tbl_item___Impre__30592A6F] DEFAULT ((0)) NULL,
    [FilmQty]                          INT          CONSTRAINT [DF__tbl_item___FilmQ__314D4EA8] DEFAULT ((0)) NULL,
    [IsFilmSupplied]                   BIT          NULL,
    [IsPlateSupplied]                  BIT          NULL,
    [IsPaperSupplied]                  BIT          NULL,
    [WashupQty]                        INT          CONSTRAINT [DF__tbl_item___Washu__351DDF8C] DEFAULT ((0)) NULL,
    [MakeReadyQty]                     INT          CONSTRAINT [DF__tbl_item___MakeR__361203C5] DEFAULT ((0)) NULL,
    [IsPaperCoated]                    SMALLINT     NULL,
    [GuillotineFirstCut]               INT          CONSTRAINT [DF__tbl_item___Guill__37FA4C37] DEFAULT ((0)) NULL,
    [GuillotineSecondCut]              INT          CONSTRAINT [DF__tbl_item___Guill__38EE7070] DEFAULT ((0)) NULL,
    [GuillotineCutTime]                INT          NULL,
    [GuillotineQty1BundlesFirstTrim]   INT          NULL,
    [GuillotineQty2BundlesFirstTrim]   INT          NULL,
    [GuillotineQty3BundlesFirstTrim]   INT          NULL,
    [GuillotineQty1BundlesSecondTrim]  INT          NULL,
    [GuillotineQty2BundlesSecondTrim]  INT          NULL,
    [GuillotineQty3BundlesSecondTrim]  INT          NULL,
    [GuillotineQty1FirstTrimCuts]      INT          NULL,
    [GuillotineQty2FirstTrimCuts]      INT          NULL,
    [GuillotineQty3FirstTrimCuts]      INT          NULL,
    [GuillotineQty1SecondTrimCuts]     INT          NULL,
    [GuillotineQty2SecondTrimCuts]     INT          NULL,
    [GuillotineQty3SecondTrimCuts]     INT          NULL,
    [GuillotineQty1TotalsCuts]         INT          NULL,
    [GuillotineQty2TotalsCuts]         INT          NULL,
    [GuillotineQty3TotalsCuts]         INT          NULL,
    [AdditionalFilmUsed]               INT          CONSTRAINT [DF__tbl_item___Addit__39E294A9] DEFAULT ((0)) NULL,
    [AdditionalPlateUsed]              INT          CONSTRAINT [DF__tbl_item___Addit__3AD6B8E2] DEFAULT ((0)) NULL,
    [IsFilmUsed]                       BIT          NULL,
    [IsPlateUsed]                      BIT          NULL,
    [NoofUniqueInks]                   INT          CONSTRAINT [DF__tbl_item___NoofU__3DB3258D] DEFAULT ((0)) NULL,
    [WizardRunMode]                    SMALLINT     NULL,
    [OverAllPTV]                       INT          NULL,
    [ItemPTV]                          INT          NULL,
    [Side1Inks]                        INT          CONSTRAINT [DF__tbl_item___Side1__3EA749C6] DEFAULT ((0)) NOT NULL,
    [Side2Inks]                        INT          CONSTRAINT [DF__tbl_item___Side2__3F9B6DFF] DEFAULT ((0)) NOT NULL,
    [IsSwingApplied]                   INT          NULL,
    [SectionType]                      SMALLINT     NULL,
    [IsMakeReadyUsed]                  BIT          NULL,
    [isWorknTurn]                      BIT          NULL,
    [isWorkntumble]                    BIT          NULL,
    [QuestionQueue]                    IMAGE        NULL,
    [StockQueue]                       IMAGE        NULL,
    [InputQueue]                       IMAGE        CONSTRAINT [DF_tbl_item_sections_InputQueue] DEFAULT (NULL) NULL,
    [CostCentreQueue]                  IMAGE        NULL,
    [PressSpeed1]                      INT          CONSTRAINT [DF__tbl_item___Press__4183B671] DEFAULT ((0)) NULL,
    [PressSpeed2]                      INT          CONSTRAINT [DF__tbl_item___Press__4277DAAA] DEFAULT ((0)) NULL,
    [PressSpeed3]                      INT          CONSTRAINT [DF__tbl_item___Press__436BFEE3] DEFAULT ((0)) NULL,
    [PressSpeed4]                      INT          CONSTRAINT [DF__tbl_item___Press__4460231C] DEFAULT ((0)) NOT NULL,
    [PressSpeed5]                      INT          CONSTRAINT [DF__tbl_item___Press__45544755] DEFAULT ((0)) NULL,
    [PrintSheetQty1]                   INT          CONSTRAINT [DF__tbl_item___Print__46486B8E] DEFAULT ((0)) NULL,
    [PrintSheetQty2]                   INT          CONSTRAINT [DF__tbl_item___Print__473C8FC7] DEFAULT ((0)) NULL,
    [PrintSheetQty3]                   INT          CONSTRAINT [DF__tbl_item___Print__4830B400] DEFAULT ((0)) NULL,
    [PrintSheetQty4]                   INT          CONSTRAINT [DF__tbl_item___Print__4924D839] DEFAULT ((0)) NULL,
    [PrintSheetQty5]                   INT          CONSTRAINT [DF__tbl_item___Print__4A18FC72] DEFAULT ((0)) NULL,
    [PressHourlyCharge]                FLOAT (53)   CONSTRAINT [DF__tbl_item___Press__4B0D20AB] DEFAULT ((0)) NULL,
    [PrintChargeExMakeReady1]          FLOAT (53)   CONSTRAINT [DF__tbl_item___Print__4C0144E4] DEFAULT ((0)) NULL,
    [PrintChargeExMakeReady2]          FLOAT (53)   CONSTRAINT [DF__tbl_item___Print__4CF5691D] DEFAULT ((0)) NULL,
    [PrintChargeExMakeReady3]          FLOAT (53)   CONSTRAINT [DF__tbl_item___Print__4DE98D56] DEFAULT ((0)) NULL,
    [PrintChargeExMakeReady4]          FLOAT (53)   CONSTRAINT [DF__tbl_item___Print__4EDDB18F] DEFAULT ((0)) NULL,
    [PrintChargeExMakeReady5]          FLOAT (53)   CONSTRAINT [DF__tbl_item___Print__4FD1D5C8] DEFAULT ((0)) NULL,
    [PaperGsm]                         FLOAT (53)   CONSTRAINT [DF__tbl_item___Paper__50C5FA01] DEFAULT ((0)) NULL,
    [PaperPackPrice]                   FLOAT (53)   CONSTRAINT [DF__tbl_item___Paper__51BA1E3A] DEFAULT ((0)) NULL,
    [PTVRows]                          INT          CONSTRAINT [DF__tbl_item___PTVRo__52AE4273] DEFAULT ((0)) NULL,
    [PTVColoumns]                      INT          CONSTRAINT [DF__tbl_item___PTVCo__53A266AC] DEFAULT ((0)) NULL,
    [PaperWeight1]                     FLOAT (53)   CONSTRAINT [DF__tbl_item___Paper__54968AE5] DEFAULT ((0)) NULL,
    [PaperWeight2]                     FLOAT (53)   CONSTRAINT [DF__tbl_item___Paper__558AAF1E] DEFAULT ((0)) NULL,
    [PaperWeight3]                     FLOAT (53)   CONSTRAINT [DF__tbl_item___Paper__567ED357] DEFAULT ((0)) NULL,
    [PaperWeight4]                     FLOAT (53)   CONSTRAINT [DF__tbl_item___Paper__5772F790] DEFAULT ((0)) NULL,
    [PaperWeight5]                     FLOAT (53)   CONSTRAINT [DF__tbl_item___Paper__58671BC9] DEFAULT ((0)) NULL,
    [FinishedItemQty1]                 INT          CONSTRAINT [DF__tbl_item___Finis__595B4002] DEFAULT ((0)) NULL,
    [FinishedItemQty2]                 INT          CONSTRAINT [DF__tbl_item___Finis__5A4F643B] DEFAULT ((0)) NULL,
    [FinishedItemQty3]                 INT          CONSTRAINT [DF__tbl_item___Finis__5B438874] DEFAULT ((0)) NULL,
    [FinishedItemQty4]                 INT          CONSTRAINT [DF__tbl_item___Finis__5C37ACAD] DEFAULT ((0)) NULL,
    [FinishedItemQty5]                 INT          CONSTRAINT [DF__tbl_item___Finis__5D2BD0E6] DEFAULT ((0)) NULL,
    [ProfileId]                        INT          CONSTRAINT [DF__tbl_item___Profi__5E1FF51F] DEFAULT ((0)) NOT NULL,
    [SelectedPressCalculationMethodId] INT          NULL,
    [SectionNotes]                     TEXT         NULL,
    [IsScheduled]                      BIT          NULL,
    [ImageType]                        INT          CONSTRAINT [DF_tbl_item_sections_ImageType] DEFAULT ((0)) NULL,
    [WebClylinderHeight]               FLOAT (53)   NULL,
    [WebCylinderWidth]                 FLOAT (53)   NULL,
    [WebCylinderId]                    INT          NULL,
    [WebPaperLengthWithSp]             FLOAT (53)   NULL,
    [WebPaperLengthWoSp]               FLOAT (53)   NULL,
    [WebReelMakereadyQty]              INT          NULL,
    [WebStockPaperCost]                FLOAT (53)   NULL,
    [WebSpoilageType]                  SMALLINT     NULL,
    [PressPassesQty]                   INT          NULL,
    [PrintingType]                     INT          NULL,
    [PadsLeafQty]                      INT          NULL,
    [PadsQuantity]                     INT          NULL,
    [LastUpdateDate]                   DATETIME     NULL,
    [LastUpdatedBy]                    INT          NULL,
    [Qty1MarkUpID]                     INT          NULL,
    [Qty2MarkUpID]                     INT          NULL,
    [Qty3MarkUpID]                     INT          NULL,
    [StockItemID1]                     BIGINT       NULL,
    [StockItemID2]                     INT          NULL,
    [StockItemID3]                     INT          NULL,
    [Side1PlateQty]                    INT          CONSTRAINT [DF__tbl_item___Plate__3429BB53] DEFAULT ((0)) NULL,
    [IsPortrait]                       BIT          NULL,
    [Side2PlateQty]                    INT          NULL,
    [InkColorType]                     INT          NULL,
    [PlateInkId]                       INT          NULL,
    [SimilarSections]                  INT          NULL,
    CONSTRAINT [PK_tbl_item_sections] PRIMARY KEY CLUSTERED ([ItemSectionId] ASC),
    CONSTRAINT [FK_ItemSection_Machine] FOREIGN KEY ([PressId]) REFERENCES [dbo].[Machine] ([MachineId]),
    CONSTRAINT [FK_ItemSection_StockItem] FOREIGN KEY ([StockItemID1]) REFERENCES [dbo].[StockItem] ([StockItemId]),
    CONSTRAINT [FK_tbl_item_sections_tbl_items] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[Items] ([ItemId]) ON DELETE CASCADE
);

