CREATE TABLE [dbo].[Items] (
    [ItemId]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [ItemCode]                       VARCHAR (50)    NULL,
    [EstimateId]                     BIGINT          NULL,
    [InvoiceId]                      BIGINT          CONSTRAINT [DF__tbl_items__Invoi__64CCF2AE] DEFAULT ((0)) NULL,
    [Title]                          VARCHAR (50)    NULL,
    [Tax1]                           INT             NULL,
    [Tax2]                           INT             CONSTRAINT [DF__tbl_items__Tax2__65C116E7] DEFAULT ((0)) NULL,
    [Tax3]                           INT             CONSTRAINT [DF__tbl_items__Tax3__66B53B20] DEFAULT ((0)) NULL,
    [CreatedBy]                      INT             NULL,
    [Status]                         SMALLINT        NULL,
    [ItemCreationDateTime]           DATETIME        NULL,
    [ItemLastUpdateDateTime]         DATETIME        NULL,
    [IsMultipleQty]                  SMALLINT        NULL,
    [RunOnQty]                       INT             NULL,
    [RunonCostCentreProfit]          FLOAT (53)      CONSTRAINT [DF__tbl_items__Runon__67A95F59] DEFAULT ((0)) NULL,
    [RunonBaseCharge]                FLOAT (53)      NULL,
    [RunOnMarkUpID]                  INT             NULL,
    [RunonPercentageValue]           INT             NULL,
    [RunOnMarkUpValue]               FLOAT (53)      NULL,
    [RunOnNetTotal]                  FLOAT (53)      NULL,
    [Qty1]                           INT             NULL,
    [Qty2]                           INT             NULL,
    [Qty3]                           INT             NULL,
    [Qty1CostCentreProfit]           FLOAT (53)      NULL,
    [Qty2CostCentreProfit]           FLOAT (53)      NULL,
    [Qty3CostCentreProfit]           FLOAT (53)      NULL,
    [Qty1BaseCharge1]                FLOAT (53)      NULL,
    [Qty2BaseCharge2]                FLOAT (53)      NULL,
    [Qty3BaseCharge3]                FLOAT (53)      NULL,
    [Qty1MarkUpID1]                  INT             NULL,
    [Qty2MarkUpID2]                  INT             NULL,
    [Qty3MarkUpID3]                  INT             NULL,
    [Qty1MarkUpPercentageValue]      FLOAT (53)      CONSTRAINT [DF__tbl_items__Qty1M__689D8392] DEFAULT ((0)) NULL,
    [Qty2MarkUpPercentageValue]      FLOAT (53)      CONSTRAINT [DF__tbl_items__Qty2M__6991A7CB] DEFAULT ((0)) NULL,
    [Qty3MarkUpPercentageValue]      FLOAT (53)      CONSTRAINT [DF__tbl_items__Qty3M__6A85CC04] DEFAULT ((0)) NULL,
    [Qty1MarkUp1Value]               FLOAT (53)      NULL,
    [Qty2MarkUp2Value]               FLOAT (53)      NULL,
    [Qty3MarkUp3Value]               FLOAT (53)      NULL,
    [Qty1NetTotal]                   FLOAT (53)      NULL,
    [Qty2NetTotal]                   FLOAT (53)      NULL,
    [Qty3NetTotal]                   FLOAT (53)      NULL,
    [Qty1Tax1Value]                  FLOAT (53)      NULL,
    [Qty1Tax2Value]                  FLOAT (53)      NULL,
    [Qty1Tax3Value]                  FLOAT (53)      NULL,
    [Qty1GrossTotal]                 FLOAT (53)      NULL,
    [Qty2Tax1Value]                  FLOAT (53)      NULL,
    [Qty2Tax2Value]                  FLOAT (53)      NULL,
    [Qty2Tax3Value]                  FLOAT (53)      NULL,
    [Qty2grossTotal]                 FLOAT (53)      NULL,
    [Qty3Tax1Value]                  FLOAT (53)      NULL,
    [Qty3Tax2Value]                  FLOAT (53)      NULL,
    [Qty3Tax3Value]                  FLOAT (53)      NULL,
    [Qty3GrossTotal]                 FLOAT (53)      NULL,
    [IsDescriptionLocked]            SMALLINT        NULL,
    [qty1title]                      VARCHAR (50)    NULL,
    [qty2title]                      VARCHAR (50)    NULL,
    [qty3Title]                      VARCHAR (50)    NULL,
    [RunonTitle]                     VARCHAR (50)    NULL,
    [AdditionalInformation]          TEXT            NULL,
    [qty2Description]                TEXT            NULL,
    [qty3Description]                TEXT            NULL,
    [RunonDescription]               TEXT            NULL,
    [EstimateDescriptionTitle1]      TEXT            NULL,
    [EstimateDescriptionTitle2]      TEXT            NULL,
    [EstimateDescriptionTitle3]      TEXT            NULL,
    [EstimateDescriptionTitle4]      TEXT            NULL,
    [EstimateDescriptionTitle5]      TEXT            NULL,
    [EstimateDescriptionTitle6]      TEXT            NULL,
    [EstimateDescriptionTitle7]      TEXT            NULL,
    [EstimateDescriptionTitle8]      TEXT            NULL,
    [EstimateDescriptionTitle9]      TEXT            NULL,
    [EstimateDescriptionTitle10]     TEXT            NULL,
    [EstimateDescription1]           TEXT            NULL,
    [EstimateDescription2]           TEXT            NULL,
    [EstimateDescription3]           TEXT            NULL,
    [EstimateDescription4]           TEXT            NULL,
    [EstimateDescription5]           TEXT            NULL,
    [EstimateDescription6]           TEXT            NULL,
    [EstimateDescription7]           TEXT            NULL,
    [EstimateDescription8]           TEXT            NULL,
    [EstimateDescription9]           TEXT            NULL,
    [EstimateDescription10]          TEXT            NULL,
    [JobDescriptionTitle1]           TEXT            NULL,
    [JobDescriptionTitle2]           TEXT            NULL,
    [JobDescriptionTitle3]           TEXT            NULL,
    [JobDescriptionTitle4]           TEXT            NULL,
    [JobDescriptionTitle5]           TEXT            NULL,
    [JobDescriptionTitle6]           TEXT            NULL,
    [JobDescriptionTitle7]           TEXT            NULL,
    [JobDescriptionTitle8]           TEXT            NULL,
    [JobDescriptionTitle9]           TEXT            NULL,
    [JobDescriptionTitle10]          TEXT            NULL,
    [JobDescription1]                TEXT            NULL,
    [JobDescription2]                TEXT            NULL,
    [JobDescription3]                TEXT            NULL,
    [JobDescription4]                TEXT            NULL,
    [JobDescription5]                TEXT            NULL,
    [JobDescription6]                TEXT            NULL,
    [JobDescription7]                TEXT            NULL,
    [JobDescription8]                TEXT            NULL,
    [JobDescription9]                TEXT            NULL,
    [JobDescription10]               TEXT            NULL,
    [IsParagraphDescription]         SMALLINT        NULL,
    [EstimateDescription]            TEXT            NULL,
    [JobDescription]                 TEXT            NULL,
    [InvoiceDescription]             TEXT            NULL,
    [JobCode]                        VARCHAR (50)    NULL,
    [JobManagerId]                   INT             CONSTRAINT [DF__tbl_items__JobMa__6D6238AF] DEFAULT ((0)) NULL,
    [JobEstimatedStartDateTime]      DATETIME        NULL,
    [JobEstimatedCompletionDateTime] DATETIME        NULL,
    [JobCreationDateTime]            DATETIME        NULL,
    [JobProgressedBy]                INT             NULL,
    [jobSelectedQty]                 INT             NULL,
    [JobStatusId]                    INT             NULL,
    [IsJobCardPrinted]               BIT             CONSTRAINT [DF_tbl_items_IsJobCardPrinted] DEFAULT ((0)) NULL,
    [IsItemLibraray]                 SMALLINT        NULL,
    [ItemLibrarayGroupId]            INT             CONSTRAINT [DF__tbl_items__ItemL__6E565CE8] DEFAULT ((0)) NULL,
    [PayInFullInvoiceId]             INT             CONSTRAINT [DF__tbl_items__PayIn__76EBA2E9] DEFAULT ((0)) NULL,
    [IsGroupItem]                    SMALLINT        CONSTRAINT [DF__tbl_items__IsGro__77DFC722] DEFAULT ((0)) NULL,
    [ItemType]                       SMALLINT        CONSTRAINT [DF__tbl_items__ItemT__78D3EB5B] DEFAULT ((0)) NULL,
    [IsIncludedInPipeLine]           SMALLINT        CONSTRAINT [DF__tbl_items__IsInc__79C80F94] DEFAULT ((1)) NULL,
    [IsRunOnQty]                     SMALLINT        CONSTRAINT [DF__tbl_items__IsRun__7ABC33CD] DEFAULT ((0)) NULL,
    [CanCopyToEstimate]              SMALLINT        CONSTRAINT [DF__tbl_items__CanCo__7BB05806] DEFAULT ((0)) NULL,
    [FlagId]                         INT             CONSTRAINT [DF__tbl_items__FlagI__7D98A078] DEFAULT ((1)) NULL,
    [CostCenterDescriptions]         IMAGE           NULL,
    [IsRead]                         BIT             CONSTRAINT [DF_tbl_items_IsRead] DEFAULT ((0)) NULL,
    [IsScheduled]                    TINYINT         CONSTRAINT [DF_tbl_items_IsScheduled] DEFAULT ((1)) NULL,
    [IsPaperStatusChanged]           BIT             CONSTRAINT [DF_tbl_items_IsPaperStatusChanged] DEFAULT ((0)) NULL,
    [IsJobCardCreated]               BIT             CONSTRAINT [DF_tbl_items_IsJobCardCreated] DEFAULT ((0)) NULL,
    [IsAttachmentAdded]              BIT             CONSTRAINT [DF_tbl_items_IsAttachmentAdded] DEFAULT ((0)) NULL,
    [IsItemValueChanged]             BIT             CONSTRAINT [DF_tbl_items_IsItemValueChanged] DEFAULT ((0)) NULL,
    [DepartmentId]                   INT             NULL,
    [ItemNotes]                      TEXT            NULL,
    [UpdatedBy]                      INT             NULL,
    [LastUpdate]                     DATETIME        NULL,
    [JobActualStartDateTime]         DATETIME        NULL,
    [JobActualCompletionDateTime]    DATETIME        NULL,
    [IsJobCostingDone]               BIT             CONSTRAINT [DF_tbl_items_IsJobCostingDone] DEFAULT ((0)) NULL,
    [ProductName]                    NVARCHAR (500)  NULL,
    [ImagePath]                      NVARCHAR (1000) NULL,
    [ThumbnailPath]                  NVARCHAR (1000) NULL,
    [ProductSpecification]           VARCHAR (MAX)   NULL,
    [CompleteSpecification]          VARCHAR (MAX)   NULL,
    [DesignGuideLines]               VARCHAR (MAX)   NULL,
    [ProductCode]                    VARCHAR (50)    NULL,
    [IsPublished]                    BIT             NULL,
    [CompanyId]                      BIGINT          NULL,
    [PriceDiscountPercentage]        INT             NULL,
    [IsEnabled]                      BIT             CONSTRAINT [DF_tbl_items_IsEnabled] DEFAULT ((0)) NULL,
    [IsSpecialItem]                  BIT             CONSTRAINT [DF_tbl_items_IsSpecialItem] DEFAULT ((0)) NULL,
    [IconPath]                       NVARCHAR (100)  CONSTRAINT [DF_tbl_items_IconPath] DEFAULT ((0)) NULL,
    [IsPopular]                      BIT             CONSTRAINT [DF_tbl_items_IsPopular] DEFAULT ((0)) NULL,
    [IsFeatured]                     BIT             CONSTRAINT [DF_tbl_items_IsFeatured] DEFAULT ((0)) NULL,
    [IsPromotional]                  BIT             CONSTRAINT [DF_tbl_items_IsPromotional] DEFAULT ((0)) NULL,
    [TipsAndHints]                   TEXT            NULL,
    [FactSheetFileName]              NVARCHAR (100)  NULL,
    [IsArchived]                     BIT             NULL,
    [NominalCodeId]                  INT             NULL,
    [RefItemId]                      BIGINT          NULL,
    [TemplateId]                     BIGINT          NULL,
    [WebDescription]                 VARCHAR (MAX)   NULL,
    [ItemTypeId]                     INT             NULL,
    [IsOrderedItem]                  BIT             CONSTRAINT [DF_tbl_items_IsOrderedItem] DEFAULT ((0)) NULL,
    [JobCardPrintedBy]               INT             NULL,
    [JobCardLastPrintedDate]         DATETIME        NULL,
    [EstimateProductionTime]         INT             NULL,
    [SortOrder]                      INT             NULL,
    [ProductType]                    INT             NULL,
    [LayoutGridContent]              NTEXT           NULL,
    [HowToVideoContent]              NTEXT           NULL,
    [file1]                          VARCHAR (200)   NULL,
    [file2]                          VARCHAR (200)   NULL,
    [file3]                          VARCHAR (200)   NULL,
    [file4]                          VARCHAR (200)   NULL,
    [file5]                          VARCHAR (200)   NULL,
    [GridImage]                      VARCHAR (200)   NULL,
    [isQtyRanged]                    BIT             NULL,
    [CostCentreProfitBroker]         FLOAT (53)      NULL,
    [BaseChargeBroker]               FLOAT (53)      NULL,
    [MarkUpValueBroker]              FLOAT (53)      NULL,
    [NetTotalBroker]                 FLOAT (53)      NULL,
    [TaxValueBroker]                 FLOAT (53)      NULL,
    [GrossTotalBroker]               FLOAT (53)      NULL,
    [isCMYK]                         BIT             NULL,
    [SupplierId]                     INT             NULL,
    [isStockControl]                 BIT             NULL,
    [isUploadImage]                  BIT             NULL,
    [isMarketingBrief]               BIT             NULL,
    [SupplierID2]                    INT             NULL,
    [FinishedGoodId]                 INT             NULL,
    [IsFinishedGoodPrivate]          SMALLINT        NULL,
    [MetaKeywords]                   NVARCHAR (MAX)  NULL,
    [MetaDescription]                NVARCHAR (500)  NULL,
    [MetaTitle]                      NVARCHAR (100)  NULL,
    [isTemplateDesignMode]           INT             NULL,
    [XeroAccessCode]                 VARCHAR (50)    NULL,
    [DefaultItemTax]                 FLOAT (53)      CONSTRAINT [DF__tbl_items__Defau__7C1CCE5F] DEFAULT ((0)) NULL,
    [OrganisationId]                 BIGINT          NULL,
    [PackagingWeight]                FLOAT (53)      NULL,
    [IsVDPProduct]                   BIT             NULL,
    [TemplateType]                   INT             NULL,
    [DesignerCategoryId]             INT             NULL,
    [Scalar]                         FLOAT (53)      NULL,
    [ZoomFactor]                     FLOAT (53)      NULL,
    [isAddCropMarks]                 BIT             NULL,
    [ItemLength]                     FLOAT (53)      NULL,
    [ItemWidth]                      FLOAT (53)      NULL,
    [ItemHeight]                     FLOAT (53)      NULL,
    [ItemWeight]                     FLOAT (53)      NULL,
    CONSTRAINT [PK_tbl_items] PRIMARY KEY CLUSTERED ([ItemId] ASC),
    CONSTRAINT [FK__Items__TemplateI__5D0415B9] FOREIGN KEY ([TemplateId]) REFERENCES [dbo].[Template] ([ProductId]),
    CONSTRAINT [FK_Items_Company] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Company] ([CompanyId]),
    CONSTRAINT [FK_tbl_items_tbl_estimates] FOREIGN KEY ([EstimateId]) REFERENCES [dbo].[Estimate] ([EstimateId]),
    CONSTRAINT [FK_tbl_items_tbl_invoices] FOREIGN KEY ([InvoiceId]) REFERENCES [dbo].[Invoice] ([InvoiceId]),
    CONSTRAINT [FK_tbl_items_tbl_Statuses] FOREIGN KEY ([Status]) REFERENCES [dbo].[Status] ([StatusId])
);


GO
ALTER TABLE [dbo].[Items] NOCHECK CONSTRAINT [FK_tbl_items_tbl_estimates];


GO
ALTER TABLE [dbo].[Items] NOCHECK CONSTRAINT [FK_tbl_items_tbl_invoices];


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Field will determine that the Item value is changed when it was originally created in the estimation.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Items', @level2type = N'COLUMN', @level2name = N'IsItemValueChanged';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Field will determine that another attacment was added after the estimate was created.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Items', @level2type = N'COLUMN', @level2name = N'IsAttachmentAdded';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Field will determine that the Job card for this item is created.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Items', @level2type = N'COLUMN', @level2name = N'IsJobCardCreated';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Flag will indicate that the item is Scheduled', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Items', @level2type = N'COLUMN', @level2name = N'IsScheduled';

