CREATE TABLE [dbo].[ItemStockControl] (
    [Id]                          BIGINT        IDENTITY (1, 1) NOT NULL,
    [ItemId]                      BIGINT        NULL,
    [ThumbnailURL]                VARCHAR (200) NULL,
    [ImageURL]                    VARCHAR (200) NULL,
    [ContentType]                 VARCHAR (50)  NULL,
    [Description1]                NTEXT         NULL,
    [Description2]                NTEXT         NULL,
    [Description3]                NTEXT         NULL,
    [LockedBy]                    INT           NOT NULL,
    [InStock]                     INT           CONSTRAINT [DF__tbl_finis__InSto__318258D2] DEFAULT ((0)) NOT NULL,
    [Allocated]                   INT           CONSTRAINT [DF__tbl_finis__Alloc__32767D0B] DEFAULT ((0)) NOT NULL,
    [ThresholdLevel]              INT           CONSTRAINT [DF__tbl_finis__Thres__345EC57D] DEFAULT ((0)) NULL,
    [ThresholdProductionQuantity] INT           CONSTRAINT [DF__tbl_finis__Thres__3552E9B6] DEFAULT ((0)) NULL,
    [Location]                    VARCHAR (50)  NULL,
    [FinishedGoodType]            SMALLINT      NULL,
    [FinishedGoodStockItemId]     INT           NULL,
    [SupplierId]                  INT           NULL,
    [SupplierCode]                VARCHAR (50)  NULL,
    [ProductCode]                 VARCHAR (50)  NULL,
    [NominalCode]                 VARCHAR (50)  NULL,
    [BarCode]                     VARCHAR (50)  NULL,
    [FinishedGoodCode]            VARCHAR (50)  NULL,
    [TaxId]                       INT           NULL,
    [RangeThresholdLevel]         INT           CONSTRAINT [DF__tbl_finis__Range__3A179ED3] DEFAULT ((0)) NULL,
    [FromThresholdDate]           DATETIME      NULL,
    [ToThresholdDate]             DATETIME      NULL,
    [Cost]                        FLOAT (53)    CONSTRAINT [DF__tbl_finish__Cost__3B0BC30C] DEFAULT ((0)) NOT NULL,
    [UnitQuantity]                INT           CONSTRAINT [DF__tbl_finis__UnitQ__3BFFE745] DEFAULT ((0)) NOT NULL,
    [PackQuantity]                INT           CONSTRAINT [DF__tbl_finis__PackQ__3CF40B7E] DEFAULT ((0)) NOT NULL,
    [RangeThresholdLevel1]        INT           CONSTRAINT [DF__tbl_finis__Range__3DE82FB7] DEFAULT ((0)) NULL,
    [RangeThresholdLevel2]        INT           CONSTRAINT [DF__tbl_finis__Range__3EDC53F0] DEFAULT ((0)) NULL,
    [FromThresholdDate1]          DATETIME      NULL,
    [FromThresholdDate2]          DATETIME      NULL,
    [ToThresholdDate1]            DATETIME      NULL,
    [ToThresholdDate2]            DATETIME      NULL,
    [SystemSiteId]                INT           NULL,
    [File1URL]                    VARCHAR (200) NULL,
    [File2URL]                    VARCHAR (200) NULL,
    [IsForWeb]                    BIT           CONSTRAINT [DF__tbl_finis__IsFor__308E3499] DEFAULT ((0)) NULL,
    [IsShowStockOnWeb]            BIT           CONSTRAINT [DF__tbl_finis__IsSho__336AA144] DEFAULT ((0)) NULL,
    [IsShowPriceOnWeb]            BIT           CONSTRAINT [DF_tbl_finishedgoods_IsShowPriceOnWeb] DEFAULT ((0)) NULL,
    [IsShowFreeStockOnWeb]        BIT           CONSTRAINT [DF_tbl_finishedgoods_IsShowFreeStockOnWeb] DEFAULT ((0)) NULL,
    [IsShowAllocatedStockOnWeb]   BIT           CONSTRAINT [DF_tbl_finishedgoods_IsShowAllocatedStockOnWeb] DEFAULT ((0)) NULL,
    [IsDisabled]                  BIT           CONSTRAINT [DF_tbl_finishedgoods_IsDisabled] DEFAULT ((0)) NULL,
    [FlagId]                      INT           NULL,
    [IsRead]                      BIT           CONSTRAINT [DF_tbl_finishedgoods_IsRead] DEFAULT ((0)) NULL,
    [CreatedBy]                   INT           NULL,
    [SiteDepartmentId]            INT           NULL,
    [isAllowBackOrder]            BIT           NULL,
    CONSTRAINT [PK_tbl_finishedgoods] PRIMARY KEY CLUSTERED ([Id] ASC)
);

