CREATE TABLE [dbo].[JobPreference] (
    [Id]                        INT IDENTITY (1, 1) NOT NULL,
    [IsDefaultInkColorUsed]     BIT NULL,
    [IsDefaultFilmUsed]         BIT NULL,
    [IsdefaultPlateUsed]        BIT NULL,
    [IsDefaultMakereadyUsed]    BIT NULL,
    [IsDefaultWashupUsed]       BIT NULL,
    [IsDefaultPressInstruction] BIT NULL,
    [IsWorkingSize]             BIT NULL,
    [IsItemSize]                BIT NULL,
    [IsImpressionCount]         BIT NULL,
    [IsNumberOfPasses]          BIT NULL,
    [IsPrintSheetQty]           BIT NULL,
    [IsDefaultStockDetail]      BIT NULL,
    [IsOrderSheetSize]          BIT NULL,
    [IsSpoilageAllowed]         BIT NULL,
    [IsPaperWeight]             BIT NULL,
    [IsPaperSheetQty]           BIT NULL,
    [IsDefaultGuilotine]        BIT NULL,
    [IsGuilotineWorkingSize]    BIT NULL,
    [IsGuilotineItemSize]       BIT NULL,
    [IsNoOfTrims]               BIT NULL,
    [IsNoOfCuts]                BIT NULL,
    [IsInksEstTime]             BIT NULL,
    [InFilmEstTime]             BIT NULL,
    [IsPlateEstTime]            BIT NULL,
    [IsWashupEstTime]           BIT NULL,
    [IsMakereadyEstTime]        BIT NULL,
    [IsPressEstTime]            BIT NULL,
    [IsPaperEstTime]            BIT NULL,
    [IsGuillotineEstTime]       BIT NULL,
    [IsReelMakeReady]           BIT NULL,
    [IsReelMakeReadyTime]       BIT NULL,
    [SystemSiteId]              INT CONSTRAINT [DF__tbl_job_p__Syste__2B5F6B28] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_tbl_job_preferences] PRIMARY KEY CLUSTERED ([Id] ASC)
);

