CREATE TABLE [dbo].[Listing] (
    [ListingId]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [WebID]                   VARCHAR (100)  NULL,
    [WebLink]                 VARCHAR (200)  NULL,
    [AddressDisplay]          VARCHAR (255)  NULL,
    [StreetAddress]           VARCHAR (255)  NULL,
    [LevelNumber]             INT            NULL,
    [LotNumber]               INT            NULL,
    [UnitNumber]              INT            NULL,
    [StreetNumber]            INT            NULL,
    [Street]                  VARCHAR (255)  NULL,
    [Suburb]                  VARCHAR (50)   NULL,
    [State]                   VARCHAR (50)   NULL,
    [PostCode]                VARCHAR (50)   NULL,
    [PropertyName]            VARCHAR (255)  NULL,
    [PropertyType]            VARCHAR (50)   NULL,
    [PropertyCategory]        VARCHAR (100)  NULL,
    [ListingType]             VARCHAR (50)   NULL,
    [ListingDate]             DATETIME       NULL,
    [ListingExpiryDate]       DATETIME       NULL,
    [ListingStatus]           VARCHAR (100)  NULL,
    [ListingMethod]           VARCHAR (100)  NULL,
    [ListingAuthority]        VARCHAR (255)  NULL,
    [InspectionTypye]         VARCHAR (255)  NULL,
    [AuctionDate]             DATETIME       NULL,
    [AutionVenue]             VARCHAR (255)  NULL,
    [EOIClosingDate]          DATETIME       NULL,
    [DisplayPrice]            FLOAT (53)     NULL,
    [SearchPrice]             FLOAT (53)     NULL,
    [RendPeriod]              INT            NULL,
    [AvailableDate]           DATETIME       NULL,
    [SoldDate]                DATETIME       NULL,
    [SoldPrice]               FLOAT (53)     NULL,
    [IsSoldPriceConfidential] BIT            NULL,
    [MainHeadLine]            VARCHAR (255)  NULL,
    [MainDescription]         VARCHAR (2000) NULL,
    [CustomCopy]              VARCHAR (2000) NULL,
    [BedRooms]                INT            NULL,
    [BathRooms]               INT            NULL,
    [LoungeRooms]             INT            NULL,
    [Toilets]                 INT            NULL,
    [Studies]                 INT            NULL,
    [Pools]                   INT            NULL,
    [Garages]                 INT            NULL,
    [Carports]                INT            NULL,
    [CarSpaces]               INT            NULL,
    [TotalParking]            INT            NULL,
    [LandArea]                FLOAT (53)     NULL,
    [LandAreaUnit]            VARCHAR (10)   NULL,
    [BuildingAreaSqm]         INT            NULL,
    [ExternalAreaSqm]         INT            NULL,
    [FrontageM]               INT            NULL,
    [Aspect]                  VARCHAR (10)   NULL,
    [YearBuilt]               VARCHAR (10)   NULL,
    [YearRenovated]           VARCHAR (10)   NULL,
    [Construction]            VARCHAR (50)   NULL,
    [PropertyCondition]       VARCHAR (255)  NULL,
    [EnergyRating]            FLOAT (53)     NULL,
    [Features]                VARCHAR (2000) NULL,
    [WaterRates]              FLOAT (53)     NULL,
    [LandTax]                 FLOAT (53)     NULL,
    [CounsilRates]            FLOAT (53)     NULL,
    [StrataAdmin]             FLOAT (53)     NULL,
    [StrataSinking]           FLOAT (53)     NULL,
    [OtherOutgoings]          FLOAT (53)     NULL,
    [LegalDescription]        VARCHAR (1000) NULL,
    [LegalLot]                VARCHAR (100)  NULL,
    [LegalDP]                 VARCHAR (100)  NULL,
    [LegalVol]                VARCHAR (100)  NULL,
    [LegalFolio]              VARCHAR (100)  NULL,
    [Zoning]                  VARCHAR (100)  NULL,
    [ClientListingId]         VARCHAR (100)  NULL,
    [TotalOutgoings]          FLOAT (53)     NULL,
    [CompanyId]               BIGINT         NULL,
    CONSTRAINT [PK_Listing] PRIMARY KEY CLUSTERED ([ListingId] ASC)
);

