CREATE TABLE [dbo].[MachineClickChargeZone] (
    [Id]                   BIGINT     IDENTITY (1, 1) NOT NULL,
    [MethodId]             BIGINT     NULL,
    [From1]                BIGINT     NULL,
    [To1]                  BIGINT     NULL,
    [Sheets1]              BIGINT     NULL,
    [SheetCost1]           FLOAT (53) NULL,
    [SheetPrice1]          FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__5832119F] DEFAULT (0) NOT NULL,
    [From2]                BIGINT     NULL,
    [To2]                  BIGINT     NULL,
    [Sheets2]              BIGINT     NULL,
    [SheetCost2]           FLOAT (53) NULL,
    [SheetPrice2]          FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__592635D8] DEFAULT (0) NOT NULL,
    [From3]                BIGINT     NULL,
    [To3]                  BIGINT     NULL,
    [Sheets3]              BIGINT     NULL,
    [SheetCost3]           FLOAT (53) NULL,
    [SheetPrice3]          FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__5A1A5A11] DEFAULT (0) NOT NULL,
    [From4]                BIGINT     NULL,
    [To4]                  BIGINT     NULL,
    [Sheets4]              BIGINT     NULL,
    [SheetCost4]           FLOAT (53) NULL,
    [SheetPrice4]          FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__5B0E7E4A] DEFAULT (0) NOT NULL,
    [From5]                BIGINT     NULL,
    [To5]                  BIGINT     NULL,
    [Sheets5]              BIGINT     NULL,
    [SheetCost5]           FLOAT (53) NULL,
    [SheetPrice5]          FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__5C02A283] DEFAULT (0) NOT NULL,
    [From6]                BIGINT     NULL,
    [To6]                  BIGINT     NULL,
    [Sheets6]              BIGINT     NULL,
    [SheetCost6]           FLOAT (53) NULL,
    [SheetPrice6]          FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__5CF6C6BC] DEFAULT (0) NOT NULL,
    [From7]                BIGINT     NULL,
    [To7]                  BIGINT     NULL,
    [Sheets7]              BIGINT     NULL,
    [SheetCost7]           FLOAT (53) NULL,
    [SheetPrice7]          FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__5DEAEAF5] DEFAULT (0) NOT NULL,
    [From8]                BIGINT     NULL,
    [To8]                  BIGINT     NULL,
    [Sheets8]              BIGINT     NULL,
    [SheetCost8]           FLOAT (53) NULL,
    [SheetPrice8]          FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__5EDF0F2E] DEFAULT (0) NOT NULL,
    [From9]                BIGINT     NULL,
    [To9]                  BIGINT     NULL,
    [Sheets9]              BIGINT     NULL,
    [SheetCost9]           FLOAT (53) NULL,
    [SheetPrice9]          FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__5FD33367] DEFAULT (0) NOT NULL,
    [From10]               BIGINT     NULL,
    [To10]                 BIGINT     NULL,
    [Sheets10]             BIGINT     NULL,
    [SheetCost10]          FLOAT (53) NULL,
    [SheetPrice10]         FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__60C757A0] DEFAULT (0) NOT NULL,
    [From11]               BIGINT     NULL,
    [To11]                 BIGINT     NULL,
    [Sheets11]             BIGINT     NULL,
    [SheetCost11]          FLOAT (53) NULL,
    [SheetPrice11]         FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__61BB7BD9] DEFAULT (0) NOT NULL,
    [From12]               BIGINT     NULL,
    [To12]                 BIGINT     NULL,
    [Sheets12]             BIGINT     NULL,
    [SheetCost12]          FLOAT (53) NULL,
    [SheetPrice12]         FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__62AFA012] DEFAULT (0) NOT NULL,
    [From13]               BIGINT     NULL,
    [To13]                 BIGINT     NULL,
    [Sheets13]             BIGINT     NULL,
    [SheetCost13]          FLOAT (53) NULL,
    [SheetPrice13]         FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__63A3C44B] DEFAULT (0) NOT NULL,
    [From14]               BIGINT     NULL,
    [To14]                 BIGINT     NULL,
    [Sheets14]             BIGINT     NULL,
    [SheetCost14]          FLOAT (53) NULL,
    [SheetPrice14]         FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__6497E884] DEFAULT (0) NOT NULL,
    [From15]               BIGINT     NULL,
    [To15]                 BIGINT     NULL,
    [Sheets15]             BIGINT     NULL,
    [SheetCost15]          FLOAT (53) NULL,
    [SheetPrice15]         FLOAT (53) CONSTRAINT [DF__tbl_machi__Sheet__658C0CBD] DEFAULT (0) NOT NULL,
    [isaccumulativecharge] SMALLINT   NULL,
    [IsRoundUp]            SMALLINT   NULL,
    [TimePerHour]          FLOAT (53) NULL,
    CONSTRAINT [PK_tbl_machine_clickchargezone] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_tbl_lookup_methods_tbl_machine_clickchargezone] FOREIGN KEY ([MethodId]) REFERENCES [dbo].[LookupMethod] ([MethodId])
);

