CREATE TABLE [dbo].[Machine] (
    [MachineId]                INT          IDENTITY (1, 1) NOT NULL,
    [MachineName]              VARCHAR (50) NULL,
    [MachineCatId]             INT          NULL,
    [ColourHeads]              INT          NULL,
    [isPerfecting]             BIT          NULL,
    [SetupCharge]              FLOAT (53)   NULL,
    [WashupPrice]              FLOAT (53)   NULL,
    [WashupCost]               FLOAT (53)   NULL,
    [MinInkDuctqty]            FLOAT (53)   NULL,
    [worknturncharge]          FLOAT (53)   NULL,
    [MakeReadyCost]            FLOAT (53)   NULL,
    [DefaultFilmId]            INT          NULL,
    [DefaultPlateId]           INT          NULL,
    [DefaultPaperId]           INT          CONSTRAINT [DF__tbl_machi__Defau__07E124C1] DEFAULT ((0)) NOT NULL,
    [isfilmused]               BIT          NULL,
    [isplateused]              BIT          NULL,
    [ismakereadyused]          BIT          NULL,
    [iswashupused]             BIT          NULL,
    [maximumsheetweight]       FLOAT (53)   CONSTRAINT [DF__tbl_machi__maxim__08D548FA] DEFAULT ((0)) NULL,
    [maximumsheetheight]       FLOAT (53)   CONSTRAINT [DF__tbl_machi__maxim__09C96D33] DEFAULT ((0)) NULL,
    [maximumsheetwidth]        FLOAT (53)   CONSTRAINT [DF__tbl_machi__maxim__0ABD916C] DEFAULT ((0)) NULL,
    [minimumsheetheight]       FLOAT (53)   CONSTRAINT [DF__tbl_machi__minim__0BB1B5A5] DEFAULT ((0)) NULL,
    [minimumsheetwidth]        FLOAT (53)   CONSTRAINT [DF__tbl_machi__minim__0CA5D9DE] DEFAULT ((0)) NULL,
    [gripdepth]                FLOAT (53)   CONSTRAINT [DF__tbl_machi__gripd__0D99FE17] DEFAULT ((0)) NULL,
    [gripsideorientaion]       INT          NULL,
    [gutterdepth]              FLOAT (53)   CONSTRAINT [DF__tbl_machi__gutte__0E8E2250] DEFAULT ((0)) NULL,
    [headdepth]                FLOAT (53)   CONSTRAINT [DF__tbl_machi__headd__0F824689] DEFAULT ((0)) NULL,
    [MarkupId]                 BIGINT       NULL,
    [PressSizeRatio]           FLOAT (53)   NULL,
    [Description]              TEXT         NOT NULL,
    [Priority]                 FLOAT (53)   NULL,
    [DirectCost]               BIT          NULL,
    [MinimumCharge]            FLOAT (53)   NULL,
    [CostPerCut]               FLOAT (53)   NULL,
    [PricePerCut]              FLOAT (53)   CONSTRAINT [DF__tbl_machi__Price__10766AC2] DEFAULT ((0)) NOT NULL,
    [IsAdditionalOption]       BIT          NULL,
    [IsDisabled]               BIT          NULL,
    [LockedBy]                 INT          CONSTRAINT [DF__tbl_machi__Locke__116A8EFB] DEFAULT ((0)) NOT NULL,
    [CylinderSizeId]           INT          NULL,
    [MaxItemAcrossCylinder]    INT          NULL,
    [Web1MRCost]               FLOAT (53)   NULL,
    [Web1MRPrice]              FLOAT (53)   CONSTRAINT [DF__tbl_machi__Web1M__125EB334] DEFAULT ((0)) NULL,
    [Web2MRCost]               FLOAT (53)   NULL,
    [Web2MRPrice]              FLOAT (53)   CONSTRAINT [DF__tbl_machi__Web2M__1352D76D] DEFAULT ((0)) NULL,
    [ReelMRCost]               FLOAT (53)   NULL,
    [ReelMRPrice]              FLOAT (53)   CONSTRAINT [DF__tbl_machi__ReelM__1446FBA6] DEFAULT ((0)) NOT NULL,
    [IsMaxColorLimit]          BIT          NULL,
    [PressUtilization]         INT          NULL,
    [MakeReadyPrice]           FLOAT (53)   NULL,
    [InkChargeForUniqueColors] FLOAT (53)   NULL,
    [CompanyId]                INT          CONSTRAINT [DF__tbl_machi__Compa__153B1FDF] DEFAULT ((0)) NOT NULL,
    [FlagId]                   INT          CONSTRAINT [DF__tbl_machi__FlagI__162F4418] DEFAULT ((0)) NULL,
    [IsScheduleable]           BIT          CONSTRAINT [DF__tbl_machi__IsSch__17236851] DEFAULT ((0)) NOT NULL,
    [SystemSiteId]             INT          CONSTRAINT [DF__tbl_machi__Syste__18178C8A] DEFAULT ((0)) NOT NULL,
    [SpoilageType]             INT          CONSTRAINT [DF__tbl_machi__Spoil__190BB0C3] DEFAULT ((0)) NOT NULL,
    [SetupTime]                FLOAT (53)   NULL,
    [TimePerCut]               FLOAT (53)   NULL,
    [MakeReadyTime]            FLOAT (53)   NULL,
    [WashupTime]               FLOAT (53)   NULL,
    [ReelMakereadyTime]        FLOAT (53)   NULL,
    [LookupMethodId]           BIGINT       NULL,
    [OrganisationId]           BIGINT       NULL,
    CONSTRAINT [PK_tbl_machines] PRIMARY KEY CLUSTERED ([MachineId] ASC)
);

