CREATE TABLE [dbo].[Organisation] (
    [OrganisationId]            BIGINT           NOT NULL,
    [OrganisationName]          VARCHAR (100)    NULL,
    [Address1]                  VARCHAR (255)    NULL,
    [Address2]                  VARCHAR (255)    NULL,
    [Address3]                  VARCHAR (255)    NULL,
    [City]                      VARCHAR (50)     NULL,
    [StateId]                   BIGINT           NULL,
    [CountryId]                 BIGINT           NULL,
    [ZipCode]                   VARCHAR (50)     NULL,
    [Tel]                       VARCHAR (50)     NULL,
    [Fax]                       VARCHAR (50)     NULL,
    [Mobile]                    VARCHAR (50)     NULL,
    [Email]                     VARCHAR (50)     NULL,
    [URL]                       VARCHAR (50)     NULL,
    [WebsiteLogo]               NVARCHAR (200)   NULL,
    [MISLogo]                   NVARCHAR (200)   NULL,
    [TaxRegistrationNo]         VARCHAR (100)    NULL,
    [LicenseLevel]              INT              NULL,
    [CustomerAccountNumber]     VARCHAR (50)     NULL,
    [SmtpServer]                VARCHAR (200)    NULL,
    [SmtpUserName]              VARCHAR (200)    NULL,
    [SmtpPassword]              VARCHAR (200)    NULL,
    [VATRegNumber]              VARCHAR (100)    NULL,
    [SystemLengthUnit]          BIGINT           NULL,
    [SystemWeightUnit]          BIGINT           NULL,
    [CurrencyId]                BIGINT           NULL,
    [LanguageId]                BIGINT           NULL,
    [MISLogoStreamId]           UNIQUEIDENTIFIER NULL,
    [BleedAreaSize]             FLOAT (53)       NULL,
    [ShowBleedArea]             BIT              NULL,
    [isXeroIntegrationRequired] BIT              NULL,
    [XeroApiId]                 NVARCHAR (100)   NULL,
    [XeroApiKey]                NVARCHAR (150)   NULL,
    CONSTRAINT [PK_tbl_company_sites] PRIMARY KEY CLUSTERED ([OrganisationId] ASC),
    CONSTRAINT [FK__Organisat__Count__16719D3F] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([CountryID]),
    CONSTRAINT [FK__Organisat__State__157D7906] FOREIGN KEY ([StateId]) REFERENCES [dbo].[State] ([StateId]),
    CONSTRAINT [FK_Organisation_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([CurrencyId]),
    CONSTRAINT [FK_Organisation_GlobalLanguage] FOREIGN KEY ([LanguageId]) REFERENCES [dbo].[GlobalLanguage] ([LanguageId]),
    CONSTRAINT [FK_Organisation_LengthUnit] FOREIGN KEY ([SystemLengthUnit]) REFERENCES [dbo].[LengthUnit] ([Id]),
    CONSTRAINT [FK_Organisation_WeightUnit] FOREIGN KEY ([SystemWeightUnit]) REFERENCES [dbo].[WeightUnit] ([Id]),
);

