CREATE TABLE [dbo].[ProductCategory] (
    [ProductCategoryId]                  BIGINT           IDENTITY (1, 1) NOT NULL,
    [CategoryName]                       VARCHAR (50)     NULL,
    [ContentType]                        VARCHAR (50)     NULL,
    [Description1]                       VARCHAR (MAX)    NULL,
    [Description2]                       VARCHAR (MAX)    NULL,
    [LockedBy]                           INT              CONSTRAINT [DF__tbl_finis__Locke__477199F1] DEFAULT ((0)) NOT NULL,
    [CompanyId]                          BIGINT           NULL,
    [ParentCategoryId]                   INT              CONSTRAINT [DF__tbl_finis__Paren__4959E263] DEFAULT ((0)) NULL,
    [DisplayOrder]                       INT              CONSTRAINT [DF__tbl_finis__Displ__4A4E069C] DEFAULT ((0)) NOT NULL,
    [ImagePath]                          NVARCHAR (100)   NULL,
    [ThumbnailPath]                      NVARCHAR (100)   NULL,
    [isEnabled]                          BIT              CONSTRAINT [DF__tbl_Produ__isEna__0C9261F3] DEFAULT ((0)) NULL,
    [isMarketPlace]                      BIT              CONSTRAINT [DF__tbl_Produ__isMar__0D86862C] DEFAULT ((1)) NULL,
    [TemplateDesignerMappedCategoryName] NVARCHAR (200)   NULL,
    [isArchived]                         BIT              NULL,
    [isPublished]                        BIT              NULL,
    [TrimmedWidth]                       FLOAT (53)       NULL,
    [TrimmedHeight]                      FLOAT (53)       NULL,
    [isColorImposition]                  BIT              NULL,
    [isOrderImposition]                  BIT              NULL,
    [isLinkToTemplates]                  BIT              NULL,
    [Sides]                              INT              NULL,
    [ApplySizeRestrictions]              BIT              NULL,
    [ApplyFoldLines]                     BIT              NULL,
    [WidthRestriction]                   FLOAT (53)       NULL,
    [HeightRestriction]                  FLOAT (53)       NULL,
    [CategoryTypeId]                     INT              NULL,
    [RegionId]                           INT              NULL,
    [ZoomFactor]                         DECIMAL (18, 2)  NULL,
    [ScaleFactor]                        DECIMAL (18, 2)  NULL,
    [isShelfProductCategory]             BIT              NULL,
    [MetaKeywords]                       NVARCHAR (MAX)   NULL,
    [MetaDescription]                    NVARCHAR (500)   NULL,
    [MetaTitle]                          NVARCHAR (100)   NULL,
    [OrganisationId]                     BIGINT           NULL,
    [SubCategoryDisplayMode1]            INT              NULL,
    [SubCategoryDisplayMode2]            INT              NULL,
    [SubCategoryDisplayColumns]          INT              NULL,
    [CategoryURLText]                    VARCHAR (200)    NULL,
    [MetaOverride]                       VARCHAR (200)    NULL,
    [ShortDescription]                   VARCHAR (1000)   NULL,
    [SecondaryDescription]               VARCHAR (1000)   NULL,
    [DefaultSortBy]                      INT              NULL,
    [ProductsDisplayColumns]             INT              NULL,
    [ProductsDisplayRows]                INT              NULL,
    [IsDisplayFeaturedproducts]          BIT              NULL,
    [IsShowAvailablity]                  BIT              NULL,
    [IsShowRewardPoints]                 BIT              NULL,
    [IsShowListPrice]                    BIT              NULL,
    [IsShowSalePrice]                    BIT              NULL,
    [IsShowStockStatus]                  BIT              NULL,
    [IsShowProductDescription]           BIT              NULL,
    [IsShowProductShortDescription]      BIT              NULL,
    [ImageStreamId]                      UNIQUEIDENTIFIER NULL,
    [ThumbnailStreamId]                  UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_tbl_finishgood_categories] PRIMARY KEY CLUSTERED ([ProductCategoryId] ASC),
    CONSTRAINT [FK_tbl_ProductCategory_tbl_contactcompanies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Company] ([CompanyId])
);

