CREATE TABLE [dbo].[Profile] (
    [Id]                        BIGINT        IDENTITY (1, 1) NOT NULL,
    [TypeId]                    INT           CONSTRAINT [DF__tbl_profi__TypeI__55209ACA] DEFAULT (0) NOT NULL,
    [Name]                      VARCHAR (50)  NULL,
    [PressId]                   INT           NULL,
    [IsPressrestrictionApplied] BIT           NULL,
    [GuilotineId]               INT           NULL,
    [IsFirstTrim]               BIT           CONSTRAINT [DF__tbl_profi__IsFir__5614BF03] DEFAULT (0) NOT NULL,
    [IsSecondTrim]              BIT           CONSTRAINT [DF__tbl_profi__IsSec__5708E33C] DEFAULT (0) NOT NULL,
    [IsPaperSupplied]           BIT           NULL,
    [IsWholePack]               BIT           NULL,
    [WorkingSheetSizeId]        INT           CONSTRAINT [DF__tbl_profi__Worki__57FD0775] DEFAULT (0) NOT NULL,
    [WorkingSheetSizeIsCustom]  BIT           NULL,
    [WorkingSheetSizeHeight]    FLOAT (53)    NULL,
    [WorkingSheetSizeWidth]     FLOAT (53)    NULL,
    [ItemSheetSizeId]           INT           NULL,
    [ItemSheetSizeIsCustom]     BIT           NULL,
    [ItemSheetSizeHeight]       FLOAT (53)    NULL,
    [ItemSheetSizeWidth]        FLOAT (53)    NULL,
    [IsItemGutterApplied]       BIT           NULL,
    [ItemGutterHorizontal]      FLOAT (53)    NULL,
    [ItemGutterVertical]        FLOAT (53)    NULL,
    [IsDoubleSided]             BIT           NULL,
    [IsWorknTurn]               BIT           NULL,
    [IsWorknTunble]             BIT           NULL,
    [IsMultipleQty]             BIT           NULL,
    [IsRunonQty]                BIT           NULL,
    [RunonQty]                  INT           NULL,
    [Qty1]                      INT           NULL,
    [Qty2]                      INT           NULL,
    [Qty3]                      INT           NULL,
    [BookletPagesPerSection]    INT           NULL,
    [BookletNoofSections]       INT           NULL,
    [BookletPages]              INT           NULL,
    [Side1Inks]                 INT           NULL,
    [Side2Inks]                 INT           NULL,
    [IsInkPrompted]             INT           NULL,
    [Description]               TEXT          NULL,
    [PadLeafQty]                INT           NULL,
    [NCRTopPaperId]             INT           NULL,
    [NCRBottomPaperId]          INT           NULL,
    [NCRMiddlePaperId]          INT           NULL,
    [NCRTotalParts]             INT           NULL,
    [LockedBy]                  INT           NULL,
    [DepartmentId]              INT           CONSTRAINT [DF__tbl_profi__Depar__58F12BAE] DEFAULT (0) NOT NULL,
    [FlagID]                    INT           CONSTRAINT [DF__tbl_profi__FlagI__59E54FE7] DEFAULT (0) NULL,
    [SystemSiteId]              INT           CONSTRAINT [DF__tbl_profi__Syste__5AD97420] DEFAULT (0) NOT NULL,
    [QtyPrefix]                 VARCHAR (100) NOT NULL,
    [IsFilmSupplied]            BIT           NULL,
    [IsPlateSupplied]           BIT           NULL,
    CONSTRAINT [PK_tbl_profile] PRIMARY KEY CLUSTERED ([Id] ASC)
);

