CREATE TABLE [dbo].[SalesCommissionRangeBased] (
    [CommissionRangeBasedId] INT          IDENTITY (1, 1) NOT NULL,
    [Description]            VARCHAR (50) NULL,
    [CommissionTypeId]       INT          NULL,
    [From1]                  INT          NULL,
    [To1]                    INT          NULL,
    [Value1]                 FLOAT (53)   NULL,
    [From2]                  INT          NULL,
    [To2]                    INT          NULL,
    [Value2]                 FLOAT (53)   NULL,
    [From3]                  INT          NULL,
    [To3]                    INT          NULL,
    [Value3]                 FLOAT (53)   NULL,
    [From4]                  INT          NULL,
    [To4]                    INT          NULL,
    [Value4]                 FLOAT (53)   NULL,
    [From5]                  INT          NULL,
    [To5]                    INT          NULL,
    [Value5]                 FLOAT (53)   NULL,
    [From6]                  INT          NULL,
    [To6]                    INT          NULL,
    [Value6]                 FLOAT (53)   NULL,
    [From7]                  INT          NULL,
    [To7]                    INT          NULL,
    [Value7]                 FLOAT (53)   NULL,
    [From8]                  INT          NULL,
    [To8]                    INT          NULL,
    [Value8]                 FLOAT (53)   NULL,
    [From9]                  INT          NULL,
    [To9]                    INT          NULL,
    [Value9]                 FLOAT (53)   NULL,
    [From10]                 INT          NULL,
    [To10]                   INT          NULL,
    [Value10]                FLOAT (53)   NULL,
    [From11]                 INT          NULL,
    [To11]                   INT          NULL,
    [Value11]                FLOAT (53)   NULL,
    CONSTRAINT [PK_tbl_sales_commission_rangebased] PRIMARY KEY CLUSTERED ([CommissionRangeBasedId] ASC)
);

