CREATE TABLE [dbo].[tbl_enquiries] (
    [EnquiryId]                  INT           IDENTITY (1, 1) NOT NULL,
    [EnquiryTitle]               VARCHAR (200) NOT NULL,
    [EnquiryCode]                VARCHAR (100) NULL,
    [ReceivedDate]               DATETIME      NULL,
    [ContactCompanyID]           INT           CONSTRAINT [DF__tbl_enqui__Custo__625A9A57] DEFAULT (0) NOT NULL,
    [ContactId]                  INT           CONSTRAINT [DF__tbl_enqui__Conta__634EBE90] DEFAULT (0) NOT NULL,
    [RequiredByDate]             DATETIME      NULL,
    [DeliveryByDate]             DATETIME      NULL,
    [Status]                     INT           CONSTRAINT [DF__tbl_enqui__Statu__6442E2C9] DEFAULT (0) NOT NULL,
    [Origination]                INT           CONSTRAINT [DF__tbl_enqui__Origi__65370702] DEFAULT (0) NOT NULL,
    [PreviousQuoteNO]            VARCHAR (50)  NOT NULL,
    [PreviousOrderNO]            VARCHAR (50)  NOT NULL,
    [QuoteDestinition]           INT           CONSTRAINT [DF__tbl_enqui__Quote__662B2B3B] DEFAULT (0) NOT NULL,
    [SendUsing]                  INT           CONSTRAINT [DF__tbl_enqui__SendU__671F4F74] DEFAULT (0) NOT NULL,
    [SalesPersonId]              INT           CONSTRAINT [DF__tbl_enqui__Sales__681373AD] DEFAULT (0) NOT NULL,
    [ProcessId]                  INT           CONSTRAINT [DF__tbl_enqui__Proce__690797E6] DEFAULT (0) NOT NULL,
    [ArtworkOriginationTypeId]   INT           CONSTRAINT [DF__tbl_enqui__Artwo__69FBBC1F] DEFAULT (0) NOT NULL,
    [ProofRequiredId]            INT           CONSTRAINT [DF__tbl_enqui__Proof__6AEFE058] DEFAULT (0) NOT NULL,
    [ProductTypeId]              INT           CONSTRAINT [DF__tbl_enqui__Produ__6BE40491] DEFAULT (0) NOT NULL,
    [ProductCode]                INT           CONSTRAINT [DF__tbl_enqui__Produ__6CD828CA] DEFAULT (0) NOT NULL,
    [FrequencyId]                INT           CONSTRAINT [DF__tbl_enqui__Frequ__6DCC4D03] DEFAULT (0) NOT NULL,
    [DataFormat]                 VARCHAR (100) NOT NULL,
    [DataAvailable]              VARCHAR (100) NOT NULL,
    [EnquiryNotes]               NTEXT         NOT NULL,
    [PrintingNotes]              NTEXT         NULL,
    [ItemNotes]                  NTEXT         NOT NULL,
    [CoverSide1Colors]           INT           CONSTRAINT [DF__tbl_enqui__Cover__6EC0713C] DEFAULT (0) NOT NULL,
    [CoverSide2Colors]           INT           CONSTRAINT [DF__tbl_enqui__Cover__6FB49575] DEFAULT (0) NOT NULL,
    [CoverInkCoveragePercentage] FLOAT (53)    CONSTRAINT [DF__tbl_enqui__Cover__70A8B9AE] DEFAULT (0) NOT NULL,
    [CoverSpecialColorsId]       INT           CONSTRAINT [DF__tbl_enqui__Cover__719CDDE7] DEFAULT (0) NOT NULL,
    [TextSide1Colors]            INT           CONSTRAINT [DF__tbl_enqui__TextS__72910220] DEFAULT (0) NOT NULL,
    [TextSide2Colors]            INT           CONSTRAINT [DF__tbl_enqui__TextS__73852659] DEFAULT (0) NOT NULL,
    [TextInkCoveragePercentage]  FLOAT (53)    CONSTRAINT [DF__tbl_enqui__TextI__74794A92] DEFAULT (0) NOT NULL,
    [TextSpecialColorsId]        INT           CONSTRAINT [DF__tbl_enqui__TextS__756D6ECB] DEFAULT (0) NOT NULL,
    [OtherSide1Colors]           INT           CONSTRAINT [DF__tbl_enqui__Other__76619304] DEFAULT (0) NOT NULL,
    [OtherSide2Colors]           INT           CONSTRAINT [DF__tbl_enqui__Other__7755B73D] DEFAULT (0) NOT NULL,
    [OtherInkCoveragePercentage] FLOAT (53)    CONSTRAINT [DF__tbl_enqui__Other__7849DB76] DEFAULT (0) NOT NULL,
    [OtherSpecialColorsId]       INT           CONSTRAINT [DF__tbl_enqui__Other__793DFFAF] DEFAULT (0) NOT NULL,
    [ISCoverPaperSupplied]       SMALLINT      CONSTRAINT [DF__tbl_enqui__ISCov__7A3223E8] DEFAULT (0) NOT NULL,
    [ISTextPaperSupplied]        SMALLINT      CONSTRAINT [DF__tbl_enqui__ISTex__7B264821] DEFAULT (0) NOT NULL,
    [ISOtherPaperSupplied]       SMALLINT      CONSTRAINT [DF__tbl_enqui__ISOth__7C1A6C5A] DEFAULT (0) NOT NULL,
    [CoverPaperTypeId]           INT           CONSTRAINT [DF__tbl_enqui__Cover__7D0E9093] DEFAULT (0) NOT NULL,
    [TextPaperTypeId]            INT           CONSTRAINT [DF__tbl_enqui__TextP__7E02B4CC] DEFAULT (0) NOT NULL,
    [OtherPaperTypeId]           INT           CONSTRAINT [DF__tbl_enqui__Other__7EF6D905] DEFAULT (0) NOT NULL,
    [PaperNotes]                 NTEXT         NOT NULL,
    [Quantity1]                  INT           CONSTRAINT [DF__tbl_enqui__Quant__7FEAFD3E] DEFAULT (0) NOT NULL,
    [Quantity2]                  INT           CONSTRAINT [DF__tbl_enqui__Quant__00DF2177] DEFAULT (0) NOT NULL,
    [Quantity3]                  INT           CONSTRAINT [DF__tbl_enqui__Quant__01D345B0] DEFAULT (0) NOT NULL,
    [FinishingStyleId]           INT           CONSTRAINT [DF__tbl_enqui__Finis__02C769E9] DEFAULT (0) NOT NULL,
    [CoverStyleId]               INT           CONSTRAINT [DF__tbl_enqui__Cover__03BB8E22] DEFAULT (0) NOT NULL,
    [CoverFinishingId]           INT           CONSTRAINT [DF__tbl_enqui__Cover__04AFB25B] DEFAULT (0) NOT NULL,
    [PackingStyleId]             INT           CONSTRAINT [DF__tbl_enqui__Packi__05A3D694] DEFAULT (0) NOT NULL,
    [InsertStyleId]              INT           CONSTRAINT [DF__tbl_enqui__Inser__0697FACD] DEFAULT (0) NOT NULL,
    [NoOfInserts]                INT           CONSTRAINT [DF__tbl_enqui__NoOfI__078C1F06] DEFAULT (0) NOT NULL,
    [FinishingNotes]             NTEXT         NOT NULL,
    [DeliveryAddressId]          INT           CONSTRAINT [DF__tbl_enqui__Deliv__0880433F] DEFAULT (0) NOT NULL,
    [BillingAddressId]           INT           CONSTRAINT [DF__tbl_enqui__Billi__09746778] DEFAULT (0) NOT NULL,
    [DeclinedNotes]              VARCHAR (100) NULL,
    [SystemSiteId]               INT           NULL,
    [SalesPersonRead]            SMALLINT      CONSTRAINT [DF__tbl_enqui__Sales__0A688BB1] DEFAULT (0) NULL,
    [EstimatorRead]              SMALLINT      CONSTRAINT [DF__tbl_enqui__Estim__0B5CAFEA] DEFAULT (0) NULL,
    [CompanyName]                VARCHAR (255) NULL,
    [FlagId]                     INT           CONSTRAINT [DF__tbl_enqui__FlagI__0C50D423] DEFAULT (1) NULL,
    [CreatedBy]                  INT           NULL,
    [CreatedByCustomer]          BIT           CONSTRAINT [DF_tbl_enquiries_CreatedByCustomer] DEFAULT (0) NULL,
    [CreationDateTime]           DATETIME      NULL,
    [PaperSizeId]                INT           NULL,
    [CustomeSize]                BIT           NULL,
    [PaperWeight]                INT           NULL,
    [CoverSpecialColorSide2ID]   INT           NULL,
    [TextSpecialColorSide2ID]    INT           NULL,
    [OtherSpecialColorSide2ID]   INT           NULL,
    [NCRSet]                     INT           NULL,
    CONSTRAINT [PK_tbl_enquiries] PRIMARY KEY CLUSTERED ([EnquiryId] ASC)
);

