CREATE TABLE [dbo].[Template] (
    [ProductId]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [Code]                NVARCHAR (50)  NULL,
    [ProductName]         NVARCHAR (255) NULL,
    [Description]         TEXT           NULL,
    [Thumbnail]           TEXT           NULL,
    [Image]               TEXT           NULL,
    [IsDisabled]          BIT            NULL,
    [PDFTemplateWidth]    FLOAT (53)     NULL,
    [PDFTemplateHeight]   FLOAT (53)     NULL,
    [CuttingMargin]       FLOAT (53)     NULL,
    [MultiPageCount]      INT            NULL,
    [Orientation]         INT            NULL,
    [MatchingSetTheme]    NVARCHAR (150) NULL,
    [BaseColorID]         INT            NULL,
    [SubmittedBy]         INT            NULL,
    [SubmittedByName]     NVARCHAR (100) NULL,
    [SubmitDate]          DATETIME       NULL,
    [Status]              INT            NULL,
    [ApprovedBy]          INT            NULL,
    [ApprovedByName]      NVARCHAR (100) NULL,
    [UserRating]          INT            NULL,
    [UsedCount]           INT            NULL,
    [MPCRating]           INT            NULL,
    [RejectionReason]     NVARCHAR (500) NULL,
    [ApprovalDate]        DATETIME       NULL,
    [TempString]          NVARCHAR (500) NULL,
    [MatchingSetID]       INT            NULL,
    [FullView]            NVARCHAR (300) NULL,
    [SLThumbnail]         NVARCHAR (300) NULL,
    [SuperView]           NVARCHAR (300) NULL,
    [ColorHex]            NVARCHAR (9)   NULL,
    [TemplateOwner]       INT            NULL,
    [TemplateOwnerName]   NVARCHAR (200) NULL,
    [IsPrivate]           BIT            NULL,
    [ApprovedDate]        DATETIME       NULL,
    [IsCorporateEditable] BIT            NULL,
    [TemplateType]        INT            NULL,
    [isWatermarkText]     BIT            NULL,
    [isSpotTemplate]      BIT            NULL,
    [isCreatedManual]     BIT            NULL,
    [isEditorChoice]      BIT            NULL,
    [ProductCategoryId]   BIGINT         NULL,
    CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED ([ProductId] ASC)
);

