//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessRight
    {
        public AccessRight()
        {
            this.Rolerights = new HashSet<Roleright>();
        }
    
        public int RightId { get; set; }
        public int SectionId { get; set; }
        public string RightName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Roleright> Rolerights { get; set; }
    }
}
