//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityId { get; set; }
        public int ActivityTypeId { get; set; }
        public string ActivityCode { get; set; }
        public string ActivityRef { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public System.DateTime ActivityTime { get; set; }
        public Nullable<System.DateTime> ActivityStartTime { get; set; }
        public Nullable<System.DateTime> ActivityEndTime { get; set; }
        public Nullable<int> ActivityProbability { get; set; }
        public Nullable<int> ActivityPrice { get; set; }
        public Nullable<int> ActivityUnit { get; set; }
        public string ActivityNotes { get; set; }
        public int IsActivityAlarm { get; set; }
        public Nullable<System.DateTime> AlarmDate { get; set; }
        public Nullable<System.DateTime> AlarmTime { get; set; }
        public int ActivityLink { get; set; }
        public Nullable<bool> IsCustomerActivity { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<System.Guid> SystemUserId { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public int IsComplete { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> CompletionTime { get; set; }
        public Nullable<int> CompletionSuccess { get; set; }
        public string CompletionResult { get; set; }
        public Nullable<int> CompletedBy { get; set; }
        public Nullable<int> IsFollowedUp { get; set; }
        public Nullable<int> FollowedActivityId { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedtime { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<short> IsLocked { get; set; }
        public Nullable<int> LockedBy { get; set; }
        public Nullable<int> SystemSiteId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> FlagId { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
