//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppVersion
    {
        public int VersionId { get; set; }
        public string CurrentMISVersion { get; set; }
        public string CurrentWebStoreVersion { get; set; }
        public Nullable<System.DateTime> DBScriptDate { get; set; }
        public Nullable<System.DateTime> DeploymentDate { get; set; }
        public string DBScriptTag { get; set; }
    }
}
