//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignReport
    {
        public int CampaignReportId { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<int> TotalDeliverd { get; set; }
        public Nullable<int> TotalFailed { get; set; }
        public string Discription { get; set; }
        public string Report { get; set; }
        public Nullable<long> OrganisationId { get; set; }
    }
}
