//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmsTag
    {
        public CmsTag()
        {
            this.CmsPageTags = new HashSet<CmsPageTag>();
        }
    
        public long TagId { get; set; }
        public string TagName { get; set; }
        public string TagSlug { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isDisplay { get; set; }
    
        public virtual ICollection<CmsPageTag> CmsPageTags { get; set; }
    }
}
