//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostcentreWorkInstructionsChoice
    {
        public long Id { get; set; }
        public string Choice { get; set; }
        public long InstructionId { get; set; }
    
        public virtual CostcentreInstruction CostcentreInstruction { get; set; }
    }
}
