//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class InquiryItem
    {
        public int InquiryItemId { get; set; }
        public string Title { get; set; }
        public string Notes { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int InquiryId { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Inquiry Inquiry { get; set; }
    }
}
