//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int InvoiceDetailId { get; set; }
        public long InvoiceId { get; set; }
        public int DetailType { get; set; }
        public Nullable<long> ItemId { get; set; }
        public string InvoiceTitle { get; set; }
        public int NominalCode { get; set; }
        public double ItemCharge { get; set; }
        public double Quantity { get; set; }
        public double ItemTaxValue { get; set; }
        public int FlagId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Description { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<int> TaxId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Item Item { get; set; }
    }
}
