//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStockOption
    {
        public ItemStockOption()
        {
            this.ItemAddonCostCentres = new HashSet<ItemAddonCostCentre>();
        }
    
        public long ItemStockOptionId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<int> OptionSequence { get; set; }
        public Nullable<long> StockId { get; set; }
        public string StockLabel { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public string ImageURL { get; set; }
    
        public virtual ICollection<ItemAddonCostCentre> ItemAddonCostCentres { get; set; }
        public virtual Item Item { get; set; }
        public virtual StockItem StockItem { get; set; }
    }
}
