//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAttachment
    {
        public long ItemAttachmentId { get; set; }
        public string FileTitle { get; set; }
        public Nullable<short> isFromCustomer { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> ContactId { get; set; }
        public Nullable<int> SystemUserId { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<long> ItemId { get; set; }
        public string Comments { get; set; }
        public string Type { get; set; }
        public Nullable<short> IsApproved { get; set; }
        public string FileName { get; set; }
        public string FolderPath { get; set; }
        public string FileType { get; set; }
        public string ContentType { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
