//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemProductDetail
    {
        public int ItemDetailId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<bool> isInternalActivity { get; set; }
        public Nullable<bool> isAutoCreateSupplierPO { get; set; }
        public Nullable<bool> isQtyLimit { get; set; }
        public Nullable<int> QtyLimit { get; set; }
        public Nullable<int> DeliveryTimeSupplier1 { get; set; }
        public Nullable<int> DeliveryTimeSupplier2 { get; set; }
        public Nullable<bool> isPrintItem { get; set; }
        public Nullable<bool> isAllowMarketBriefAttachment { get; set; }
        public string MarketBriefSuccessMessage { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
