//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStockUpdateHistory
    {
        public int StockHistoryId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> LastAvailableQty { get; set; }
        public Nullable<int> LastModifiedQty { get; set; }
        public Nullable<int> LastOrderedQty { get; set; }
        public Nullable<int> ModifyEvent { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> OrderID { get; set; }
    }
}
