//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingVendor
    {
        public long VendorId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Solutation { get; set; }
        public string MailingSolutation { get; set; }
        public string Company { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<long> ListingId { get; set; }
    }
}
