//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingLink
    {
        public string LinkType { get; set; }
        public string LinkURL { get; set; }
        public string LinkTitle { get; set; }
        public Nullable<long> ListingId { get; set; }
        public long LinkId { get; set; }
    }
}
