//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingFloorPlan
    {
        public long FloorPlanId { get; set; }
        public Nullable<long> ListingId { get; set; }
        public string ImageURL { get; set; }
        public string PDFURL { get; set; }
        public Nullable<System.DateTime> LastMode { get; set; }
        public string ClientFloorplanID { get; set; }
    }
}
