//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineGuillotineCalc
    {
        public long Id { get; set; }
        public Nullable<long> MethodId { get; set; }
        public Nullable<long> PaperWeight1 { get; set; }
        public Nullable<long> PaperThroatQty1 { get; set; }
        public Nullable<long> PaperWeight2 { get; set; }
        public Nullable<long> PaperThroatQty2 { get; set; }
        public Nullable<long> PaperWeight3 { get; set; }
        public Nullable<long> PaperThroatQty3 { get; set; }
        public Nullable<long> PaperWeight4 { get; set; }
        public Nullable<long> PaperThroatQty4 { get; set; }
        public Nullable<long> PaperWeight5 { get; set; }
        public Nullable<long> PaperThroatQty5 { get; set; }
    
        public virtual LookupMethod LookupMethod { get; set; }
    }
}
