//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public Machine()
        {
            this.ItemSections = new HashSet<ItemSection>();
            this.MachineCostCentreGroups = new HashSet<MachineCostCentreGroup>();
            this.MachineInkCoverages = new HashSet<MachineInkCoverage>();
            this.MachineLookupMethods = new HashSet<MachineLookupMethod>();
            this.MachinePaginationProfiles = new HashSet<MachinePaginationProfile>();
            this.MachineResources = new HashSet<MachineResource>();
        }
    
        public int MachineId { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> MachineCatId { get; set; }
        public Nullable<int> ColourHeads { get; set; }
        public Nullable<bool> isPerfecting { get; set; }
        public Nullable<double> SetupCharge { get; set; }
        public Nullable<double> WashupPrice { get; set; }
        public Nullable<double> WashupCost { get; set; }
        public Nullable<double> MinInkDuctqty { get; set; }
        public Nullable<double> worknturncharge { get; set; }
        public Nullable<double> MakeReadyCost { get; set; }
        public Nullable<int> DefaultFilmId { get; set; }
        public Nullable<int> DefaultPlateId { get; set; }
        public int DefaultPaperId { get; set; }
        public Nullable<bool> isfilmused { get; set; }
        public Nullable<bool> isplateused { get; set; }
        public Nullable<bool> ismakereadyused { get; set; }
        public Nullable<bool> iswashupused { get; set; }
        public Nullable<double> maximumsheetweight { get; set; }
        public Nullable<double> maximumsheetheight { get; set; }
        public Nullable<double> maximumsheetwidth { get; set; }
        public Nullable<double> minimumsheetheight { get; set; }
        public Nullable<double> minimumsheetwidth { get; set; }
        public Nullable<double> gripdepth { get; set; }
        public Nullable<int> gripsideorientaion { get; set; }
        public Nullable<double> gutterdepth { get; set; }
        public Nullable<double> headdepth { get; set; }
        public Nullable<long> MarkupId { get; set; }
        public Nullable<double> PressSizeRatio { get; set; }
        public string Description { get; set; }
        public Nullable<double> Priority { get; set; }
        public Nullable<bool> DirectCost { get; set; }
        public Nullable<double> MinimumCharge { get; set; }
        public Nullable<double> CostPerCut { get; set; }
        public double PricePerCut { get; set; }
        public Nullable<bool> IsAdditionalOption { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public int LockedBy { get; set; }
        public Nullable<int> CylinderSizeId { get; set; }
        public Nullable<int> MaxItemAcrossCylinder { get; set; }
        public Nullable<double> Web1MRCost { get; set; }
        public Nullable<double> Web1MRPrice { get; set; }
        public Nullable<double> Web2MRCost { get; set; }
        public Nullable<double> Web2MRPrice { get; set; }
        public Nullable<double> ReelMRCost { get; set; }
        public double ReelMRPrice { get; set; }
        public Nullable<bool> IsMaxColorLimit { get; set; }
        public Nullable<int> PressUtilization { get; set; }
        public Nullable<double> MakeReadyPrice { get; set; }
        public Nullable<double> InkChargeForUniqueColors { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> FlagId { get; set; }
        public bool IsScheduleable { get; set; }
        public int SystemSiteId { get; set; }
        public int SpoilageType { get; set; }
        public Nullable<double> SetupTime { get; set; }
        public Nullable<double> TimePerCut { get; set; }
        public Nullable<double> MakeReadyTime { get; set; }
        public Nullable<double> WashupTime { get; set; }
        public Nullable<double> ReelMakereadyTime { get; set; }
        public Nullable<long> LookupMethodId { get; set; }
        public Nullable<long> OrganisationId { get; set; }
    
        public virtual ICollection<ItemSection> ItemSections { get; set; }
        public virtual ICollection<MachineCostCentreGroup> MachineCostCentreGroups { get; set; }
        public virtual ICollection<MachineInkCoverage> MachineInkCoverages { get; set; }
        public virtual ICollection<MachineLookupMethod> MachineLookupMethods { get; set; }
        public virtual ICollection<MachinePaginationProfile> MachinePaginationProfiles { get; set; }
        public virtual ICollection<MachineResource> MachineResources { get; set; }
    }
}
