//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaginationProfile
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<int> PaperSizeId { get; set; }
        public Nullable<int> LookupMethodId { get; set; }
        public Nullable<int> Orientation { get; set; }
        public Nullable<int> FinishStyleId { get; set; }
        public Nullable<double> MinHeight { get; set; }
        public Nullable<double> Minwidth { get; set; }
        public Nullable<double> Maxheight { get; set; }
        public Nullable<double> MaxWidth { get; set; }
        public Nullable<double> MinWeight { get; set; }
        public Nullable<double> MaxWeight { get; set; }
        public Nullable<int> MaxNoOfColors { get; set; }
        public string GrainDirection { get; set; }
        public Nullable<int> NumberUp { get; set; }
        public Nullable<int> NoOfDifferentTypes { get; set; }
        public Nullable<int> LockedBy { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> FlagId { get; set; }
        public int SystemSiteId { get; set; }
    }
}
