//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGateway
    {
        public int PaymentGatewayId { get; set; }
        public string BusinessEmail { get; set; }
        public string IdentityToken { get; set; }
        public bool isActive { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public string SecureHash { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
