//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategoryItem
    {
        public long ProductCategoryItemId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> ItemId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
