//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public long Id { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> PressId { get; set; }
        public Nullable<bool> IsPressrestrictionApplied { get; set; }
        public Nullable<int> GuilotineId { get; set; }
        public bool IsFirstTrim { get; set; }
        public bool IsSecondTrim { get; set; }
        public Nullable<bool> IsPaperSupplied { get; set; }
        public Nullable<bool> IsWholePack { get; set; }
        public int WorkingSheetSizeId { get; set; }
        public Nullable<bool> WorkingSheetSizeIsCustom { get; set; }
        public Nullable<double> WorkingSheetSizeHeight { get; set; }
        public Nullable<double> WorkingSheetSizeWidth { get; set; }
        public Nullable<int> ItemSheetSizeId { get; set; }
        public Nullable<bool> ItemSheetSizeIsCustom { get; set; }
        public Nullable<double> ItemSheetSizeHeight { get; set; }
        public Nullable<double> ItemSheetSizeWidth { get; set; }
        public Nullable<bool> IsItemGutterApplied { get; set; }
        public Nullable<double> ItemGutterHorizontal { get; set; }
        public Nullable<double> ItemGutterVertical { get; set; }
        public Nullable<bool> IsDoubleSided { get; set; }
        public Nullable<bool> IsWorknTurn { get; set; }
        public Nullable<bool> IsWorknTunble { get; set; }
        public Nullable<bool> IsMultipleQty { get; set; }
        public Nullable<bool> IsRunonQty { get; set; }
        public Nullable<int> RunonQty { get; set; }
        public Nullable<int> Qty1 { get; set; }
        public Nullable<int> Qty2 { get; set; }
        public Nullable<int> Qty3 { get; set; }
        public Nullable<int> BookletPagesPerSection { get; set; }
        public Nullable<int> BookletNoofSections { get; set; }
        public Nullable<int> BookletPages { get; set; }
        public Nullable<int> Side1Inks { get; set; }
        public Nullable<int> Side2Inks { get; set; }
        public Nullable<int> IsInkPrompted { get; set; }
        public string Description { get; set; }
        public Nullable<int> PadLeafQty { get; set; }
        public Nullable<int> NCRTopPaperId { get; set; }
        public Nullable<int> NCRBottomPaperId { get; set; }
        public Nullable<int> NCRMiddlePaperId { get; set; }
        public Nullable<int> NCRTotalParts { get; set; }
        public Nullable<int> LockedBy { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> FlagID { get; set; }
        public int SystemSiteId { get; set; }
        public string QtyPrefix { get; set; }
        public Nullable<bool> IsFilmSupplied { get; set; }
        public Nullable<bool> IsPlateSupplied { get; set; }
    }
}
