//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Purchase()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public int PurchaseId { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> date_Purchase { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public int ContactId { get; set; }
        public string SupplierContactCompany { get; set; }
        public int SupplierContactAddressID { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> JobID { get; set; }
        public string RefNo { get; set; }
        public string Comments { get; set; }
        public string FootNote { get; set; }
        public string UserNotes { get; set; }
        public Nullable<System.DateTime> NotesUpdateDateTime { get; set; }
        public Nullable<int> NotesUpdatedByUserId { get; set; }
        public Nullable<int> isproduct { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> LockedBy { get; set; }
        public Nullable<double> TotalTax { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<int> discountType { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> NetTotal { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastChangedBy { get; set; }
        public Nullable<int> FlagID { get; set; }
        public Nullable<int> SystemSiteId { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public string XeroAccessCode { get; set; }
    
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
    }
}
