//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportId { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public string FileName { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public string ReportDataSource { get; set; }
        public string NameSpace { get; set; }
        public int IsExternal { get; set; }
        public int IsFixed { get; set; }
        public string ReportTemplate { get; set; }
        public string ReportTemplateOriginal { get; set; }
        public short IsEditable { get; set; }
        public int ParentReportId { get; set; }
        public short IsByReflection { get; set; }
        public int CompanyId { get; set; }
        public Nullable<short> IsSystemReport { get; set; }
        public int ReportOrder { get; set; }
        public Nullable<bool> HasSubReport { get; set; }
        public string SubReportTemplate { get; set; }
        public string SubReportDataSource { get; set; }
        public Nullable<long> OrganisationId { get; set; }
    
        public virtual ReportCategory ReportCategory { get; set; }
    }
}
