//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareUpdate
    {
        public string PatchVersion { get; set; }
        public string PatchTitle { get; set; }
        public Nullable<System.DateTime> InstalledOnDate { get; set; }
        public string Description { get; set; }
        public string Manifest { get; set; }
        public Nullable<bool> IsApplied { get; set; }
        public Nullable<int> NoOfUserUpdated { get; set; }
    }
}
