//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Estimates = new HashSet<Estimate>();
            this.Items = new HashSet<Item>();
        }
    
        public short StatusId { get; set; }
        public string StatusName { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusType { get; set; }
    
        public virtual ICollection<Estimate> Estimates { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
