//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSubCategory
    {
        public StockSubCategory()
        {
            this.StockItems = new HashSet<StockItem>();
        }
    
        public long SubCategoryId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Fixed { get; set; }
        public long CategoryId { get; set; }
    
        public virtual StockCategory StockCategory { get; set; }
        public virtual ICollection<StockItem> StockItems { get; set; }
    }
}
