//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemuserPreference
    {
        public int SystemUserPreferenceId { get; set; }
        public Nullable<int> SystemUserId { get; set; }
        public string CallColor { get; set; }
        public string AppointmentColor { get; set; }
        public string NextActionColor { get; set; }
        public string OtherActionColor { get; set; }
        public string SaleColor { get; set; }
        public string EventColor { get; set; }
        public string ToDoColor { get; set; }
        public Nullable<bool> ShowPublic { get; set; }
        public Nullable<int> RecordRetrievalLimit { get; set; }
        public byte[] SchedulingPreference { get; set; }
        public Nullable<short> EnquiryRefreshTime { get; set; }
        public Nullable<short> EstimatesRefreshTime { get; set; }
        public Nullable<short> OrdersRefreshTime { get; set; }
        public Nullable<short> JobsRefreshTime { get; set; }
        public Nullable<short> SchedulingRefreshTime { get; set; }
        public Nullable<short> CRMReminderRefreshTime { get; set; }
        public Nullable<short> DefaultCalendar { get; set; }
        public string SmtpServer { get; set; }
        public string SmtpUserName { get; set; }
        public string SmtpPassword { get; set; }
        public string Pop3Server { get; set; }
        public string Pop3UserName { get; set; }
        public string Pop3Password { get; set; }
    }
}
