//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Completion { get; set; }
        public Nullable<int> IsTaskAlarmed { get; set; }
        public Nullable<System.DateTime> TaskAlarmDate { get; set; }
        public Nullable<System.DateTime> TaskAlarmTime { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> IsComplete { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> CompletionTime { get; set; }
        public Nullable<int> TotalWorkHours { get; set; }
        public Nullable<int> ActualWorkHours { get; set; }
        public string Notes { get; set; }
        public Nullable<int> IsPrivate { get; set; }
        public Nullable<int> IsTaskLinked { get; set; }
        public Nullable<int> LinkType { get; set; }
        public Nullable<int> LinkId { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdationDateTime { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<short> IsLocked { get; set; }
        public Nullable<int> LockedBy { get; set; }
        public Nullable<int> SystemSiteId { get; set; }
    }
}
