//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_machine_clickchargelookup
    {
        public long ID { get; set; }
        public long MethodID { get; set; }
        public Nullable<double> SheetCost { get; set; }
        public Nullable<int> Sheets { get; set; }
        public Nullable<double> SheetPrice { get; set; }
        public Nullable<double> TimePerHour { get; set; }
    
        public virtual tbl_lookup_methods tbl_lookup_methods { get; set; }
    }
}
