//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_group_detail
    {
        public int GroupDetailID { get; set; }
        public int ContactID { get; set; }
        public short IsCustomerContact { get; set; }
        public int GroupID { get; set; }
    
        public virtual tbl_groups tbl_groups { get; set; }
    }
}
