//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_section_flags
    {
        public int SectionFlagID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string FlagName { get; set; }
        public string FlagColor { get; set; }
        public string flagDescription { get; set; }
        public int CompanyID { get; set; }
        public string FlagColumn { get; set; }
        public Nullable<bool> isDefault { get; set; }
    
        public virtual tbl_sections tbl_sections { get; set; }
    }
}
