//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_costcentre_instructions
    {
        public tbl_costcentre_instructions()
        {
            this.tbl_costcentre_workinstructions_choices = new HashSet<tbl_costcentre_workinstructions_choices>();
        }
    
        public long InstructionID { get; set; }
        public string Instruction { get; set; }
        public Nullable<int> CostCentreID { get; set; }
        public Nullable<int> CostCenterOption { get; set; }
    
        public virtual ICollection<tbl_costcentre_workinstructions_choices> tbl_costcentre_workinstructions_choices { get; set; }
        public virtual tbl_costcentres tbl_costcentres { get; set; }
    }
}
