//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Correspondence
    {
        public int CorrespondenceID { get; set; }
        public string RefTableName { get; set; }
        public string RefFieldName { get; set; }
        public Nullable<int> RefKeyID { get; set; }
        public Nullable<short> Type { get; set; }
        public string Reference { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<short> ReferenceType { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Direction { get; set; }
        public string Address { get; set; }
        public Nullable<int> UID { get; set; }
    }
}
