//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_scheduled_costcenters
    {
        public int ScheduledCostCenterID { get; set; }
        public int SectionCostCenterID { get; set; }
        public int CostCenterID { get; set; }
        public int SystemCostCenterType { get; set; }
        public int ResourcesID { get; set; }
        public double CritMints { get; set; }
        public double SetupTime { get; set; }
        public double RunTime { get; set; }
        public string WorkInstructions { get; set; }
        public string CostCenterName { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EstimatedStartTime { get; set; }
        public Nullable<System.DateTime> EstimatedEndTime { get; set; }
    }
}
