//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_shippinginformation
    {
        public int ShippingID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> DeliveryNoteRaised { get; set; }
        public System.DateTime DeliveryDate { get; set; }
    }
}
