//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_weightconversion
    {
        public int ID { get; set; }
        public string Items { get; set; }
        public Nullable<double> Pound { get; set; }
        public Nullable<double> GSM { get; set; }
        public Nullable<double> KG { get; set; }
    }
}
