//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_purchasedetail
    {
        public int PurchaseDetailID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> packqty { get; set; }
        public string ItemCode { get; set; }
        public string ServiceDetail { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> NetTax { get; set; }
        public Nullable<int> freeitems { get; set; }
        public Nullable<double> ItemBalance { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual tbl_purchase tbl_purchase { get; set; }
    }
}
