//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_machines
    {
        public tbl_machines()
        {
            this.tbl_machine_costcentre_groups = new HashSet<tbl_machine_costcentre_groups>();
            this.tbl_machine_ink_coverage = new HashSet<tbl_machine_ink_coverage>();
            this.tbl_machine_lookup_methods = new HashSet<tbl_machine_lookup_methods>();
            this.tbl_machine_pagination_profile = new HashSet<tbl_machine_pagination_profile>();
            this.tbl_machine_resource = new HashSet<tbl_machine_resource>();
            this.tbl_machine_guilotine_ptv = new HashSet<tbl_machine_guilotine_ptv>();
            this.tbl_machine_spoilage = new HashSet<tbl_machine_spoilage>();
        }
    
        public int MachineID { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> MachineCatID { get; set; }
        public Nullable<int> ColourHeads { get; set; }
        public Nullable<bool> isPerfecting { get; set; }
        public Nullable<double> SetupCharge { get; set; }
        public Nullable<double> WashupPrice { get; set; }
        public Nullable<double> WashupCost { get; set; }
        public Nullable<double> MinInkDuctqty { get; set; }
        public Nullable<double> worknturncharge { get; set; }
        public Nullable<double> MakeReadyCost { get; set; }
        public Nullable<int> DefaultFilmid { get; set; }
        public Nullable<int> DefaultPlateid { get; set; }
        public int DefaultPaperid { get; set; }
        public Nullable<bool> isfilmused { get; set; }
        public Nullable<bool> isplateused { get; set; }
        public Nullable<bool> ismakereadyused { get; set; }
        public Nullable<bool> iswashupused { get; set; }
        public Nullable<double> maximumsheetweight { get; set; }
        public Nullable<double> maximumsheetheight { get; set; }
        public Nullable<double> maximumsheetwidth { get; set; }
        public Nullable<double> minimumsheetheight { get; set; }
        public Nullable<double> minimumsheetwidth { get; set; }
        public Nullable<double> gripdepth { get; set; }
        public Nullable<int> gripsideorientaion { get; set; }
        public Nullable<double> gutterdepth { get; set; }
        public Nullable<double> headdepth { get; set; }
        public Nullable<double> Va { get; set; }
        public Nullable<double> PressSizeRatio { get; set; }
        public string Description { get; set; }
        public Nullable<double> Priority { get; set; }
        public Nullable<bool> DirectCost { get; set; }
        public Nullable<double> MinimumCharge { get; set; }
        public Nullable<double> CostPerCut { get; set; }
        public double PricePerCut { get; set; }
        public Nullable<bool> IsAdditionalOption { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public int LockedBy { get; set; }
        public Nullable<int> CylinderSizeID { get; set; }
        public Nullable<int> MaxItemAcrossCylinder { get; set; }
        public Nullable<double> Web1MRCost { get; set; }
        public Nullable<double> Web1MRPrice { get; set; }
        public Nullable<double> Web2MRCost { get; set; }
        public Nullable<double> Web2MRPrice { get; set; }
        public Nullable<double> ReelMRCost { get; set; }
        public double ReelMRPrice { get; set; }
        public Nullable<bool> IsMaxColorLimit { get; set; }
        public Nullable<int> PressUtilization { get; set; }
        public Nullable<double> MakeReadyPrice { get; set; }
        public Nullable<double> InkChargeForUniqueColors { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> FlagID { get; set; }
        public bool IsScheduleable { get; set; }
        public int SystemSiteID { get; set; }
        public int SpoilageType { get; set; }
        public Nullable<double> SetupTime { get; set; }
        public Nullable<double> TimePerCut { get; set; }
        public Nullable<double> MakeReadyTime { get; set; }
        public Nullable<double> WashupTime { get; set; }
        public Nullable<double> ReelMakereadyTime { get; set; }
    
        public virtual ICollection<tbl_machine_costcentre_groups> tbl_machine_costcentre_groups { get; set; }
        public virtual ICollection<tbl_machine_ink_coverage> tbl_machine_ink_coverage { get; set; }
        public virtual ICollection<tbl_machine_lookup_methods> tbl_machine_lookup_methods { get; set; }
        public virtual ICollection<tbl_machine_pagination_profile> tbl_machine_pagination_profile { get; set; }
        public virtual ICollection<tbl_machine_resource> tbl_machine_resource { get; set; }
        public virtual ICollection<tbl_machine_guilotine_ptv> tbl_machine_guilotine_ptv { get; set; }
        public virtual ICollection<tbl_machine_spoilage> tbl_machine_spoilage { get; set; }
    }
}
