//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_system_email_emailsID_and_sectionsID
    {
        public int ID { get; set; }
        public Nullable<int> EmailID { get; set; }
        public string SectionID { get; set; }
    }
}
