//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cmsTags
    {
        public tbl_cmsTags()
        {
            this.tbl_cmsPageTags = new HashSet<tbl_cmsPageTags>();
        }
    
        public int TagID { get; set; }
        public string TagName { get; set; }
        public string TagSlug { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isDisplay { get; set; }
    
        public virtual ICollection<tbl_cmsPageTags> tbl_cmsPageTags { get; set; }
    }
}
