//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cmsDefaultSettings
    {
        public int SettingsID { get; set; }
        public Nullable<int> SkinID { get; set; }
        public Nullable<bool> isDisplayFeaturedProducts { get; set; }
        public Nullable<bool> isDisplayPopularProducts { get; set; }
        public Nullable<bool> isDisplayPromotionalProducts { get; set; }
        public Nullable<bool> isDisplayChooseUsIcons { get; set; }
        public Nullable<bool> isDisplaySecondaryPages { get; set; }
        public Nullable<bool> isDisplayKeywords { get; set; }
        public Nullable<bool> isDisplayTermsAndConditions { get; set; }
        public string SocialNetworking1Link { get; set; }
        public string SocialNetworking1Icon { get; set; }
        public string SocialNetworking2Link { get; set; }
        public string SocialNetworking2Icon { get; set; }
        public string SocialNetworking3Link { get; set; }
        public string SocialNetworking3Icon { get; set; }
        public string SocialNetworking4Link { get; set; }
        public string SocialNetworking4Icon { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<bool> isDefaultSettings { get; set; }
        public string ChooseUsIcon1 { get; set; }
        public string ChooseUsIcon2 { get; set; }
        public string ChooseUsIcon3 { get; set; }
        public string ChooseUsIcon4 { get; set; }
        public string TermsAndConditionsURL { get; set; }
        public Nullable<int> PalleteID { get; set; }
        public string WebMasterTag { get; set; }
        public string WebAnalyticCode { get; set; }
        public Nullable<int> MapType { get; set; }
        public string MapURL { get; set; }
        public string RedirectWebstoreURL { get; set; }
        public Nullable<bool> isAddCropMarks { get; set; }
        public string MapLat { get; set; }
        public string MapLong { get; set; }
        public Nullable<bool> EmailBrokerArtworkOrder { get; set; }
        public Nullable<bool> includeEmailBrokerArtworkOrderReport { get; set; }
        public Nullable<bool> includeEmailBrokerArtworkOrderXML { get; set; }
        public Nullable<bool> includeEmailBrokerArtworkOrderJobCard { get; set; }
        public Nullable<bool> makeEmailBrokerArtworkOrderProductionReady { get; set; }
        public Nullable<bool> isTextWatermark { get; set; }
        public string WatermarkText { get; set; }
        public string BackgroundImageURL { get; set; }
        public Nullable<bool> isIncludeVAT { get; set; }
    
        public virtual tbl_cmsSkins tbl_cmsSkins { get; set; }
    }
}
