//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rights
    {
        public tbl_rights()
        {
            this.tbl_rolerights = new HashSet<tbl_rolerights>();
        }
    
        public int RightID { get; set; }
        public int SectionID { get; set; }
        public string RightName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tbl_rolerights> tbl_rolerights { get; set; }
    }
}
