//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inquiry_Attachments
    {
        public int AttachmentID { get; set; }
        public string OrignalFileName { get; set; }
        public string AttachmentPath { get; set; }
        public int InquiryID { get; set; }
        public string Extension { get; set; }
    
        public virtual tbl_Inquiry tbl_Inquiry { get; set; }
    }
}
