//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_markup
    {
        public tbl_markup()
        {
            this.tbl_prefixes = new HashSet<tbl_prefixes>();
        }
    
        public int MarkUpID { get; set; }
        public string MarkUpName { get; set; }
        public Nullable<double> MarkUpRate { get; set; }
        public Nullable<int> IsFixed { get; set; }
        public int SystemSiteID { get; set; }
    
        public virtual ICollection<tbl_prefixes> tbl_prefixes { get; set; }
    }
}
