//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PayPalResponses
    {
        public tbl_PayPalResponses()
        {
            this.tbl_PrePayments = new HashSet<tbl_PrePayments>();
        }
    
        public long PayPalResponseID { get; set; }
        public Nullable<long> RequestID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public string TransactionID { get; set; }
        public Nullable<double> PaymentPrice { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string ReasonFault { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string TransactionType { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentType { get; set; }
        public string PayerEmail { get; set; }
        public string PayerStatus { get; set; }
        public string ReceiverEmail { get; set; }
    
        public virtual ICollection<tbl_PrePayments> tbl_PrePayments { get; set; }
    }
}
