//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_items_RelatedItems
    {
        public Nullable<int> ItemID { get; set; }
        public int Id { get; set; }
        public Nullable<int> RelatedItemID { get; set; }
    
        public virtual tbl_items tbl_items { get; set; }
        public virtual tbl_items tbl_items1 { get; set; }
    }
}
