//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ContactRoles
    {
        public tbl_ContactRoles()
        {
            this.tbl_contacts = new HashSet<tbl_contacts>();
        }
    
        public int ContactRoleID { get; set; }
        public string ContactRoleName { get; set; }
    
        public virtual ICollection<tbl_contacts> tbl_contacts { get; set; }
    }
}
