//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_financialyeardetail
    {
        public int ID { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public Nullable<int> AccountNo { get; set; }
        public Nullable<double> OpenningBalance { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
    }
}
