//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_costcentre_groups
    {
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public short Sequence { get; set; }
        public int SystemSiteID { get; set; }
    }
}
