//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_campaign_clickthroughs
    {
        public int ClickThroughID { get; set; }
        public int CampaignID { get; set; }
        public Nullable<int> ClickThruCountTotal { get; set; }
        public Nullable<int> ClickThruCount { get; set; }
        public string ClickThruUpdateField { get; set; }
        public string ClickThruText { get; set; }
        public string ClickThruURL { get; set; }
        public Nullable<int> AutoResponseID { get; set; }
        public string StoredProcedure { get; set; }
    }
}
