//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_stockitems_issue_log
    {
        public long ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> SectionCostCentreID { get; set; }
        public Nullable<int> SectionCostCentreDetailID { get; set; }
        public Nullable<int> StockID { get; set; }
        public Nullable<int> IssuedQty { get; set; }
        public Nullable<int> IssuedBy { get; set; }
        public Nullable<System.DateTime> IssueDateTime { get; set; }
    }
}
