//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ContactCompanyTerritories
    {
        public tbl_ContactCompanyTerritories()
        {
            this.tbl_addresses = new HashSet<tbl_addresses>();
            this.tbl_contacts = new HashSet<tbl_contacts>();
            this.tbl_ContactDepartments = new HashSet<tbl_ContactDepartments>();
            this.tbl_TerritoryItems = new HashSet<tbl_TerritoryItems>();
        }
    
        public int TerritoryID { get; set; }
        public string TerritoryName { get; set; }
        public Nullable<int> ContactCompanyID { get; set; }
        public string TerritoryCode { get; set; }
        public Nullable<bool> isDefault { get; set; }
    
        public virtual ICollection<tbl_addresses> tbl_addresses { get; set; }
        public virtual tbl_contactcompanies tbl_contactcompanies { get; set; }
        public virtual ICollection<tbl_contacts> tbl_contacts { get; set; }
        public virtual ICollection<tbl_ContactDepartments> tbl_ContactDepartments { get; set; }
        public virtual ICollection<tbl_TerritoryItems> tbl_TerritoryItems { get; set; }
    }
}
