//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_items_PriceMatrix
    {
        public int PriceMatrixID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> PricePaperType1 { get; set; }
        public Nullable<double> PricePaperType2 { get; set; }
        public Nullable<double> PricePaperType3 { get; set; }
        public Nullable<bool> IsDiscounted { get; set; }
        public Nullable<int> QtyRangeFrom { get; set; }
        public Nullable<int> QtyRangeTo { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<double> PriceStockType4 { get; set; }
        public Nullable<double> PriceStockType5 { get; set; }
        public Nullable<double> PriceStockType6 { get; set; }
        public Nullable<double> PriceStockType7 { get; set; }
        public Nullable<double> PriceStockType8 { get; set; }
        public Nullable<double> PriceStockType9 { get; set; }
        public Nullable<double> PriceStockType10 { get; set; }
        public Nullable<double> PriceStockType11 { get; set; }
        public Nullable<int> FlagID { get; set; }
        public Nullable<int> SupplierSequence { get; set; }
        public Nullable<int> ContactCompanyID { get; set; }
    
        public virtual tbl_items tbl_items { get; set; }
    }
}
