//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentGateways
    {
        public int PaymentGatewayID { get; set; }
        public string BusinessEmail { get; set; }
        public string IdentityToken { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> BrokerContactCompanyID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public string SecureHash { get; set; }
    
        public virtual tbl_PaymentMethods tbl_PaymentMethods { get; set; }
    }
}
