//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cmsPageCategory
    {
        public tbl_cmsPageCategory()
        {
            this.tbl_cmsPages = new HashSet<tbl_cmsPages>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<tbl_cmsPages> tbl_cmsPages { get; set; }
    }
}
