//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_regionalsettings
    {
        public int Laguage { get; set; }
        public string LanguageValue { get; set; }
        public string Color { get; set; }
        public string ColorValue { get; set; }
        public string Organization { get; set; }
        public string OrganizationValue { get; set; }
        public string State { get; set; }
        public string StateValue { get; set; }
        public string Centre { get; set; }
        public string CentreValue { get; set; }
        public string ZipCode { get; set; }
        public string ZipCodeValue { get; set; }
        public string Metre { get; set; }
        public string MetreValue { get; set; }
        public string Weight { get; set; }
        public string WeightValue { get; set; }
        public string PaperMeasure { get; set; }
        public string PaperMeasureValue { get; set; }
        public string License { get; set; }
        public string LicenceMeasure { get; set; }
        public Nullable<short> IsSelected { get; set; }
    }
}
