//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NewsLetterSubscribers
    {
        public int SubscriberID { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Status { get; set; }
        public string SubscriptionCode { get; set; }
        public System.DateTime SubscribeDate { get; set; }
        public Nullable<System.DateTime> UnSubscribeDate { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> ContactCompanyID { get; set; }
        public Nullable<int> FlagID { get; set; }
    
        public virtual tbl_contacts tbl_contacts { get; set; }
    }
}
