//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoicedetails
    {
        public int InvoiceDetailID { get; set; }
        public int InvoiceID { get; set; }
        public int DetailType { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string InvoiceTitle { get; set; }
        public int NominalCode { get; set; }
        public double ItemCharge { get; set; }
        public double Quantity { get; set; }
        public double ItemTaxValue { get; set; }
        public int FlagID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<int> TaxID { get; set; }
    
        public virtual tbl_invoices tbl_invoices { get; set; }
        public virtual tbl_items tbl_items { get; set; }
    }
}
