//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inquiry
    {
        public tbl_Inquiry()
        {
            this.tbl_Inquiry_Attachments = new HashSet<tbl_Inquiry_Attachments>();
            this.tbl_Inquiry_Items = new HashSet<tbl_Inquiry_Items>();
        }
    
        public int InquiryID { get; set; }
        public string Title { get; set; }
        public int ContactID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> ContactCompanyID { get; set; }
        public Nullable<System.DateTime> RequireByDate { get; set; }
        public Nullable<int> SystemUserID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDirectInquiry { get; set; }
        public Nullable<int> FlagID { get; set; }
        public string InquiryCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> BrokerContactCompanyID { get; set; }
    
        public virtual tbl_contacts tbl_contacts { get; set; }
        public virtual ICollection<tbl_Inquiry_Attachments> tbl_Inquiry_Attachments { get; set; }
        public virtual ICollection<tbl_Inquiry_Items> tbl_Inquiry_Items { get; set; }
    }
}
