//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cmsOffers
    {
        public int OfferID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> OfferType { get; set; }
        public string Description { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
