//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_systemusers
    {
        public int SystemUserID { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string UserType { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<short> IsAccountDisabled { get; set; }
        public Nullable<short> IsTillSupervisor { get; set; }
        public Nullable<float> CostPerHour { get; set; }
        public string CurrentMachineName { get; set; }
        public string CurrentMachineIP { get; set; }
        public Nullable<int> LockedBy { get; set; }
        public Nullable<short> IsScheduleable { get; set; }
        public Nullable<int> CompanySiteID { get; set; }
        public string ReplyEmail { get; set; }
        public Nullable<bool> CanSendEmail { get; set; }
        public Nullable<int> IsSystemUser { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EmailSignature { get; set; }
        public string SmtpServer { get; set; }
        public string SmtpUserName { get; set; }
        public string SmtpPassword { get; set; }
        public string UserAuthToken { get; set; }
        public Nullable<bool> canDesignTemplate { get; set; }
        public Nullable<bool> canApproveTemplate { get; set; }
    
        public virtual tbl_company_sites tbl_company_sites { get; set; }
    }
}
