//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_report_notes
    {
        public int ID { get; set; }
        public string FootNotes { get; set; }
        public string HeadNotes { get; set; }
        public string AdvertitorialNotes { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ReportCategoryID { get; set; }
        public int SystemSiteID { get; set; }
        public string ReportBanner { get; set; }
        public string ReportTitle { get; set; }
        public string BannerAbsolutePath { get; set; }
        public Nullable<bool> isDefault { get; set; }
    
        public virtual tbl_reportcategory tbl_reportcategory { get; set; }
    }
}
