//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowPreference
    {
        public int Id { get; set; }
        public int SystemSiteId { get; set; }
        public bool ShowTaxInformation { get; set; }
        public bool ShippingNoteordertojob { get; set; }
        public bool CopyJobDescriptionToInvoice { get; set; }
        public bool EstimateTitleMandatory { get; set; }
        public bool GoodsOrderForm { get; set; }
        public bool RoundSellingPrice { get; set; }
        public bool ShippingNoteIquirytoorder { get; set; }
        public bool ShowTax2AndTax3Information { get; set; }
        public int Nearest { get; set; }
        public bool ItemTitleMandatory { get; set; }
        public bool OrderTitleMandatory { get; set; }
        public Nullable<bool> ShowZeroValueCostCentre { get; set; }
    }
}
