//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostcentreResource
    {
        public Nullable<long> CostCentreId { get; set; }
        public Nullable<System.Guid> ResourceId { get; set; }
        public int CostCenterResourceId { get; set; }
    
        public virtual CostCentre CostCentre { get; set; }
    }
}
