//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomCopy
    {
        public string SignboardHeadline { get; set; }
        public string SignboardDescription { get; set; }
        public string BrochureHeadline { get; set; }
        public string BrochureDescription { get; set; }
        public string BrochureFeature1 { get; set; }
        public string BrochureFeature2 { get; set; }
        public string BrochureFeature3 { get; set; }
        public string BrochureFeature4 { get; set; }
        public string BrochureLifeStyle1 { get; set; }
        public string BrochureLifeStyle2 { get; set; }
        public string BrochureLifeStyle3 { get; set; }
        public Nullable<long> ListingId { get; set; }
        public long CustomCopyId { get; set; }
    }
}
