//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomizedFieldsData
    {
        public int Id { get; set; }
        public int FieldID { get; set; }
        public int CustomerId { get; set; }
        public short ISCustomer { get; set; }
        public string Value { get; set; }
        public int CompanyId { get; set; }
    }
}
