//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryCarrier
    {
        public long CarrierId { get; set; }
        public string CarrierName { get; set; }
        public string Url { get; set; }
        public string ApiKey { get; set; }
        public string ApiPassword { get; set; }
        public Nullable<bool> isEnable { get; set; }
    }
}
