//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNoteDetail
    {
        public int DeliveryDetailid { get; set; }
        public int DeliveryNoteId { get; set; }
        public string Description { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<double> GrossItemTotal { get; set; }
    
        public virtual DeliveryNote DeliveryNote { get; set; }
        public virtual Item Item { get; set; }
    }
}
