//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldVariable
    {
        public long VariableId { get; set; }
        public string VariableName { get; set; }
        public string RefTableName { get; set; }
        public string CriteriaFieldName { get; set; }
        public Nullable<int> VariableSectionId { get; set; }
        public string VariableTag { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string KeyField { get; set; }
        public Nullable<int> VariableType { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<int> Scope { get; set; }
        public string WaterMark { get; set; }
        public string DefaultValue { get; set; }
        public string InputMask { get; set; }
        public Nullable<long> OrganisationId { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public string VariableTitle { get; set; }
    }
}
