//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.Items = new HashSet<Item>();
        }
    
        public long InvoiceId { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public string InvoiceName { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> ContactId { get; set; }
        public string OrderNo { get; set; }
        public Nullable<short> InvoiceStatus { get; set; }
        public Nullable<double> InvoiceTotal { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string AccountNumber { get; set; }
        public string Terms { get; set; }
        public Nullable<System.DateTime> InvoicePostingDate { get; set; }
        public Nullable<System.Guid> InvoicePostedBy { get; set; }
        public Nullable<System.Guid> LockedBy { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<bool> IsArchive { get; set; }
        public Nullable<double> TaxValue { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<int> FlagID { get; set; }
        public string UserNotes { get; set; }
        public Nullable<System.DateTime> NotesUpdateDateTime { get; set; }
        public Nullable<int> NotesUpdatedByUserID { get; set; }
        public Nullable<int> SystemSiteId { get; set; }
        public Nullable<long> EstimateId { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsProformaInvoice { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.Guid> ReportSignedBy { get; set; }
        public Nullable<System.DateTime> ReportLastPrintedDate { get; set; }
        public string HeadNotes { get; set; }
        public string FootNotes { get; set; }
        public string XeroAccessCode { get; set; }
        public Nullable<long> OrganisationId { get; set; }
    
        public virtual CompanyContact CompanyContact { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
