//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStateTax
    {
        public long ItemStateTaxId { get; set; }
        public Nullable<long> CountryId { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<long> ItemId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual Item Item { get; set; }
    }
}
