//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRelatedItem
    {
        public Nullable<long> ItemId { get; set; }
        public int Id { get; set; }
        public Nullable<long> RelatedItemId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
    }
}
