//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemVDPPrice
    {
        public long ItemVDPPriceId { get; set; }
        public Nullable<int> ClickRangeTo { get; set; }
        public Nullable<int> ClickRangeFrom { get; set; }
        public Nullable<double> PricePerClick { get; set; }
        public Nullable<double> SetupCharge { get; set; }
        public Nullable<long> ItemId { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
