//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineSpoilage
    {
        public int MachineSpoilageId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> SetupSpoilage { get; set; }
        public Nullable<float> RunningSpoilage { get; set; }
        public Nullable<int> NoOfColors { get; set; }
    }
}
