//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineClickChargeZone
    {
        public long Id { get; set; }
        public Nullable<long> MethodId { get; set; }
        public Nullable<long> From1 { get; set; }
        public Nullable<long> To1 { get; set; }
        public Nullable<long> Sheets1 { get; set; }
        public Nullable<double> SheetCost1 { get; set; }
        public double SheetPrice1 { get; set; }
        public Nullable<long> From2 { get; set; }
        public Nullable<long> To2 { get; set; }
        public Nullable<long> Sheets2 { get; set; }
        public Nullable<double> SheetCost2 { get; set; }
        public double SheetPrice2 { get; set; }
        public Nullable<long> From3 { get; set; }
        public Nullable<long> To3 { get; set; }
        public Nullable<long> Sheets3 { get; set; }
        public Nullable<double> SheetCost3 { get; set; }
        public double SheetPrice3 { get; set; }
        public Nullable<long> From4 { get; set; }
        public Nullable<long> To4 { get; set; }
        public Nullable<long> Sheets4 { get; set; }
        public Nullable<double> SheetCost4 { get; set; }
        public double SheetPrice4 { get; set; }
        public Nullable<long> From5 { get; set; }
        public Nullable<long> To5 { get; set; }
        public Nullable<long> Sheets5 { get; set; }
        public Nullable<double> SheetCost5 { get; set; }
        public double SheetPrice5 { get; set; }
        public Nullable<long> From6 { get; set; }
        public Nullable<long> To6 { get; set; }
        public Nullable<long> Sheets6 { get; set; }
        public Nullable<double> SheetCost6 { get; set; }
        public double SheetPrice6 { get; set; }
        public Nullable<long> From7 { get; set; }
        public Nullable<long> To7 { get; set; }
        public Nullable<long> Sheets7 { get; set; }
        public Nullable<double> SheetCost7 { get; set; }
        public double SheetPrice7 { get; set; }
        public Nullable<long> From8 { get; set; }
        public Nullable<long> To8 { get; set; }
        public Nullable<long> Sheets8 { get; set; }
        public Nullable<double> SheetCost8 { get; set; }
        public double SheetPrice8 { get; set; }
        public Nullable<long> From9 { get; set; }
        public Nullable<long> To9 { get; set; }
        public Nullable<long> Sheets9 { get; set; }
        public Nullable<double> SheetCost9 { get; set; }
        public double SheetPrice9 { get; set; }
        public Nullable<long> From10 { get; set; }
        public Nullable<long> To10 { get; set; }
        public Nullable<long> Sheets10 { get; set; }
        public Nullable<double> SheetCost10 { get; set; }
        public double SheetPrice10 { get; set; }
        public Nullable<long> From11 { get; set; }
        public Nullable<long> To11 { get; set; }
        public Nullable<long> Sheets11 { get; set; }
        public Nullable<double> SheetCost11 { get; set; }
        public double SheetPrice11 { get; set; }
        public Nullable<long> From12 { get; set; }
        public Nullable<long> To12 { get; set; }
        public Nullable<long> Sheets12 { get; set; }
        public Nullable<double> SheetCost12 { get; set; }
        public double SheetPrice12 { get; set; }
        public Nullable<long> From13 { get; set; }
        public Nullable<long> To13 { get; set; }
        public Nullable<long> Sheets13 { get; set; }
        public Nullable<double> SheetCost13 { get; set; }
        public double SheetPrice13 { get; set; }
        public Nullable<long> From14 { get; set; }
        public Nullable<long> To14 { get; set; }
        public Nullable<long> Sheets14 { get; set; }
        public Nullable<double> SheetCost14 { get; set; }
        public double SheetPrice14 { get; set; }
        public Nullable<long> From15 { get; set; }
        public Nullable<long> To15 { get; set; }
        public Nullable<long> Sheets15 { get; set; }
        public Nullable<double> SheetCost15 { get; set; }
        public double SheetPrice15 { get; set; }
        public Nullable<short> isaccumulativecharge { get; set; }
        public Nullable<short> IsRoundUp { get; set; }
        public Nullable<double> TimePerHour { get; set; }
    
        public virtual LookupMethod LookupMethod { get; set; }
    }
}
