//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineCylinder
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Circumference { get; set; }
        public Nullable<double> Width { get; set; }
        public int SystemSiteId { get; set; }
    }
}
