//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsLetterSubscriber
    {
        public int SubscriberId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Status { get; set; }
        public string SubscriptionCode { get; set; }
        public System.DateTime SubscribeDate { get; set; }
        public Nullable<System.DateTime> UnSubscribeDate { get; set; }
        public Nullable<long> ContactId { get; set; }
        public Nullable<int> ContactCompanyID { get; set; }
        public Nullable<int> FlagId { get; set; }
    
        public virtual CompanyContact CompanyContact { get; set; }
    }
}
