//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class prefix
    {
        public string EstimatePrefix { get; set; }
        public Nullable<long> EstimateStart { get; set; }
        public Nullable<long> EstimateNext { get; set; }
        public string InvoicePrefix { get; set; }
        public Nullable<long> InvoiceStart { get; set; }
        public Nullable<long> InvoiceNext { get; set; }
        public string JobPrefix { get; set; }
        public Nullable<long> JobStart { get; set; }
        public Nullable<long> JobNext { get; set; }
        public string POPrefix { get; set; }
        public Nullable<long> POStart { get; set; }
        public Nullable<long> PONext { get; set; }
        public string GOFPrefix { get; set; }
        public Nullable<long> GOFStart { get; set; }
        public Nullable<long> GOFNext { get; set; }
        public string ITEMPrefix { get; set; }
        public Nullable<long> ITEMStart { get; set; }
        public Nullable<long> ITEMNext { get; set; }
        public string DeliveryNPrefix { get; set; }
        public Nullable<long> DeliveryNStart { get; set; }
        public Nullable<long> DeliveryNNext { get; set; }
        public string JobCardPrefix { get; set; }
        public Nullable<long> JobCardStart { get; set; }
        public Nullable<long> JobCardNext { get; set; }
        public string GRNPrefix { get; set; }
        public Nullable<long> GRNStart { get; set; }
        public Nullable<long> GRNNext { get; set; }
        public string ProductPrefix { get; set; }
        public Nullable<long> ProductStart { get; set; }
        public Nullable<long> ProductNext { get; set; }
        public string FinishedGoodsPrefix { get; set; }
        public long FinishedGoodsStart { get; set; }
        public long FinishedGoodsNext { get; set; }
        public string OrderPrefix { get; set; }
        public long OrderStart { get; set; }
        public long OrderNext { get; set; }
        public string EnquiryPrefix { get; set; }
        public long EnquiryStart { get; set; }
        public long EnquiryNext { get; set; }
        public string StockItemPrefix { get; set; }
        public Nullable<long> StockItemStart { get; set; }
        public Nullable<long> StockItemNext { get; set; }
        public int SystemSiteID { get; set; }
        public long PrefixId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<long> MarkupId { get; set; }
        public Nullable<int> JobManagerId { get; set; }
        public Nullable<int> OrderManagerId { get; set; }
        public Nullable<long> OrganisationId { get; set; }
    
        public virtual Markup Markup { get; set; }
    }
}
