//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategoryFoldLine
    {
        public int FoldLineId { get; set; }
        public Nullable<long> ProductCategoryId { get; set; }
        public Nullable<bool> FoldLineOrientation { get; set; }
        public Nullable<double> FoldLineOffsetFromOrigin { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
