//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScopeVariable
    {
        public long ScopeVariableId { get; set; }
        public long Id { get; set; }
        public long VariableId { get; set; }
        public string Value { get; set; }
        public Nullable<int> Scope { get; set; }
    
        public virtual FieldVariable FieldVariable { get; set; }
    }
}
