//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.CampaignEmailVariables = new HashSet<CampaignEmailVariable>();
            this.PhraseFields = new HashSet<PhraseField>();
            this.RoleSections = new HashSet<RoleSection>();
            this.SectionFlags = new HashSet<SectionFlag>();
        }
    
        public int SectionId { get; set; }
        public string SectionName { get; set; }
        public int SecOrder { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string href { get; set; }
        public string SectionImage { get; set; }
        public bool Independent { get; set; }
    
        public virtual ICollection<CampaignEmailVariable> CampaignEmailVariables { get; set; }
        public virtual ICollection<PhraseField> PhraseFields { get; set; }
        public virtual ICollection<RoleSection> RoleSections { get; set; }
        public virtual ICollection<SectionFlag> SectionFlags { get; set; }
    }
}
