//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionFlag
    {
        public int SectionFlagId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string FlagName { get; set; }
        public string FlagColor { get; set; }
        public string flagDescription { get; set; }
        public Nullable<long> OrganisationId { get; set; }
        public string FlagColumn { get; set; }
        public Nullable<bool> isDefault { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
