//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartForm
    {
        public SmartForm()
        {
            this.SmartFormDetails = new HashSet<SmartFormDetail>();
        }
    
        public long SmartFormId { get; set; }
        public string Name { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> OrganisationId { get; set; }
        public string Heading { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<SmartFormDetail> SmartFormDetails { get; set; }
    }
}
