//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartFormDetail
    {
        public long SmartFormDetailId { get; set; }
        public long SmartFormId { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<long> VariableId { get; set; }
        public string CaptionValue { get; set; }
    
        public virtual FieldVariable FieldVariable { get; set; }
        public virtual SmartForm SmartForm { get; set; }
    }
}
