//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public System.Guid SystemUserId { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string FullName { get; set; }
        public string UserType { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<short> IsAccountDisabled { get; set; }
        public Nullable<float> CostPerHour { get; set; }
        public Nullable<short> IsScheduleable { get; set; }
        public Nullable<int> IsSystemUser { get; set; }
        public string UserAuthToken { get; set; }
    }
}
