//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public Template()
        {
            this.TemplateBackgroundImages = new HashSet<TemplateBackgroundImage>();
            this.TemplateColorStyles = new HashSet<TemplateColorStyle>();
            this.TemplateFonts = new HashSet<TemplateFont>();
            this.TemplateObjects = new HashSet<TemplateObject>();
            this.TemplatePages = new HashSet<TemplatePage>();
            this.Items = new HashSet<Item>();
        }
    
        public long ProductId { get; set; }
        public string Code { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string Thumbnail { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<double> PDFTemplateWidth { get; set; }
        public Nullable<double> PDFTemplateHeight { get; set; }
        public Nullable<double> CuttingMargin { get; set; }
        public Nullable<int> MultiPageCount { get; set; }
        public Nullable<int> Orientation { get; set; }
        public string MatchingSetTheme { get; set; }
        public Nullable<int> BaseColorID { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public string SubmittedByName { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string ApprovedByName { get; set; }
        public Nullable<int> UserRating { get; set; }
        public Nullable<int> UsedCount { get; set; }
        public Nullable<int> MPCRating { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string TempString { get; set; }
        public Nullable<int> MatchingSetID { get; set; }
        public string FullView { get; set; }
        public string SLThumbnail { get; set; }
        public string SuperView { get; set; }
        public string ColorHex { get; set; }
        public Nullable<int> TemplateOwner { get; set; }
        public string TemplateOwnerName { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> IsCorporateEditable { get; set; }
        public Nullable<int> TemplateType { get; set; }
        public Nullable<bool> isWatermarkText { get; set; }
        public Nullable<bool> isSpotTemplate { get; set; }
        public Nullable<bool> isCreatedManual { get; set; }
        public Nullable<bool> isEditorChoice { get; set; }
        public Nullable<long> ProductCategoryId { get; set; }
    
        public virtual ICollection<TemplateBackgroundImage> TemplateBackgroundImages { get; set; }
        public virtual ICollection<TemplateColorStyle> TemplateColorStyles { get; set; }
        public virtual ICollection<TemplateFont> TemplateFonts { get; set; }
        public virtual ICollection<TemplateObject> TemplateObjects { get; set; }
        public virtual ICollection<TemplatePage> TemplatePages { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
