//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTarget
    {
        public int TargetId { get; set; }
        public Nullable<int> TargetTypeId { get; set; }
        public int SystemUserId { get; set; }
        public Nullable<System.DateTime> TargetFrom { get; set; }
        public Nullable<System.DateTime> TargetTo { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<short> IsActive { get; set; }
    }
}
