//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReport
    {
        public int UserReportId { get; set; }
        public int SystemUserId { get; set; }
        public int ReportId { get; set; }
        public short IsDefault { get; set; }
        public Nullable<int> ReportCategoryId { get; set; }
    }
}
