//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableExtension
    {
        public int Id { get; set; }
        public Nullable<int> FieldVariableId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public string VariablePrefix { get; set; }
        public string VariablePostfix { get; set; }
        public Nullable<bool> CollapsePrefix { get; set; }
        public Nullable<bool> CollapsePostfix { get; set; }
    }
}
