//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationUtility.Preview
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherDetail
    {
        public long VoucherDetailId { get; set; }
        public Nullable<long> VoucherId { get; set; }
        public Nullable<int> DebitAccount { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreditAccount { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    }
}
