using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DomainModel = MPC.Models.DomainModels;
using ApiModel = MPC.MIS.Areas.Api.Models;

namespace MPC.MIS.Areas.Api.ModelMappers
{
    public static class MachineClickChargeZoneMapper
    {
        public static DomainModel.MachineClickChargeZone CreateFrom(this ApiModel.MachineClickChargeZone source)
        {
            return new DomainModel.MachineClickChargeZone
            {
                Id = source.Id,
                MethodId = source.MethodId,
                From1 = source.From1,
                To1 = source.To1,
                Sheets1 = source.Sheets1,
                SheetCost1 = source.SheetCost1,
                SheetPrice1 = source.SheetPrice1,
                From2 = source.From2,
                To2 = source.To2,
                Sheets2 = source.Sheets2,
                SheetCost2 = source.SheetCost2,
                SheetPrice2 = source.SheetPrice2,
                From3 = source.From3,
                To3 = source.To3,
                Sheets3 = source.Sheets3,
                SheetCost3 = source.SheetCost3,
                SheetPrice3 = source.SheetPrice3,
                From4 = source.From4,
                To4 = source.To4,
                Sheets4 = source.Sheets4,
                SheetCost4 = source.SheetCost4,
                SheetPrice4 = source.SheetPrice4,
                From5 = source.From5,
                To5 = source.To5,
                Sheets5 = source.Sheets5,
                SheetCost5 = source.SheetCost5,
                SheetPrice5 = source.SheetPrice5,
                From6 = source.From6,
                To6 = source.To6,
                Sheets6 = source.Sheets6,
                SheetCost6 = source.SheetCost6,
                SheetPrice6 = source.SheetPrice6,
                From7 = source.From7,
                To7 = source.To7,
                Sheets7 = source.Sheets7,
                SheetCost7 = source.SheetCost7,
                SheetPrice7 = source.SheetPrice7,
                From8 = source.From8,
                To8 = source.To8,
                Sheets8 = source.Sheets8,
                SheetCost8 = source.SheetCost8,
                SheetPrice8 = source.SheetPrice8,
                From9 = source.From9,
                To9 = source.To9,
                Sheets9 = source.Sheets9,
                SheetCost9 = source.SheetCost9,
                SheetPrice9 = source.SheetPrice9,
                From10 = source.From10,
                To10 = source.To10,
                Sheets10 = source.Sheets10,
                SheetCost10 = source.SheetCost10,
                SheetPrice10 = source.SheetPrice10,
                From11 = source.From11,
                To11 = source.To11,
                Sheets11 = source.Sheets11,
                SheetCost11 = source.SheetCost11,
                SheetPrice11 = source.SheetPrice11,
                From12 = source.From12,
                To12 = source.To12,
                Sheets12 = source.Sheets12,
                SheetCost12 = source.SheetCost12,
                SheetPrice12 = source.SheetPrice12,
                From13 = source.From13,
                To13 = source.To13,
                Sheets13 = source.Sheets13,
                SheetCost13 = source.SheetCost13,
                SheetPrice13 = source.SheetPrice13,
                From14 = source.From14,
                To14 = source.To14,
                Sheets14 = source.Sheets14,
                SheetCost14 = source.SheetCost14,
                SheetPrice14 = source.SheetPrice14,
                From15 = source.From15,
                To15 = source.To15,
                Sheets15 = source.Sheets15,
                SheetCost15 = source.SheetCost15,
                SheetPrice15 = source.SheetPrice15,
                isaccumulativecharge = source.isaccumulativecharge,
                IsRoundUp = source.IsRoundUp,
                TimePerHour = source.TimePerHour,
                ZoneName = source.ZoneName

            };
        }
        public static ApiModel.MachineClickChargeZone CreateFrom(this DomainModel.MachineClickChargeZone source)
        {
            return new ApiModel.MachineClickChargeZone
            {
                Id = source.Id,
                MethodId = source.MethodId,
                From1 = source.From1,
                To1 = source.To1,
                Sheets1 = source.Sheets1,
                SheetCost1 = source.SheetCost1,
                SheetPrice1 = source.SheetPrice1,
                From2 = source.From2,
                To2 = source.To2,
                Sheets2 = source.Sheets2,
                SheetCost2 = source.SheetCost2,
                SheetPrice2 = source.SheetPrice2,
                From3 = source.From3,
                To3 = source.To3,
                Sheets3 = source.Sheets3,
                SheetCost3 = source.SheetCost3,
                SheetPrice3 = source.SheetPrice3,
                From4 = source.From4,
                To4 = source.To4,
                Sheets4 = source.Sheets4,
                SheetCost4 = source.SheetCost4,
                SheetPrice4 = source.SheetPrice4,
                From5 = source.From5,
                To5 = source.To5,
                Sheets5 = source.Sheets5,
                SheetCost5 = source.SheetCost5,
                SheetPrice5 = source.SheetPrice5,
                From6 = source.From6,
                To6 = source.To6,
                Sheets6 = source.Sheets6,
                SheetCost6 = source.SheetCost6,
                SheetPrice6 = source.SheetPrice6,
                From7 = source.From7,
                To7 = source.To7,
                Sheets7 = source.Sheets7,
                SheetCost7 = source.SheetCost7,
                SheetPrice7 = source.SheetPrice7,
                From8 = source.From8,
                To8 = source.To8,
                Sheets8 = source.Sheets8,
                SheetCost8 = source.SheetCost8,
                SheetPrice8 = source.SheetPrice8,
                From9 = source.From9,
                To9 = source.To9,
                Sheets9 = source.Sheets9,
                SheetCost9 = source.SheetCost9,
                SheetPrice9 = source.SheetPrice9,
                From10 = source.From10,
                To10 = source.To10,
                Sheets10 = source.Sheets10,
                SheetCost10 = source.SheetCost10,
                SheetPrice10 = source.SheetPrice10,
                From11 = source.From11,
                To11 = source.To11,
                Sheets11 = source.Sheets11,
                SheetCost11 = source.SheetCost11,
                SheetPrice11 = source.SheetPrice11,
                From12 = source.From12,
                To12 = source.To12,
                Sheets12 = source.Sheets12,
                SheetCost12 = source.SheetCost12,
                SheetPrice12 = source.SheetPrice12,
                From13 = source.From13,
                To13 = source.To13,
                Sheets13 = source.Sheets13,
                SheetCost13 = source.SheetCost13,
                SheetPrice13 = source.SheetPrice13,
                From14 = source.From14,
                To14 = source.To14,
                Sheets14 = source.Sheets14,
                SheetCost14 = source.SheetCost14,
                SheetPrice14 = source.SheetPrice14,
                From15 = source.From15,
                To15 = source.To15,
                Sheets15 = source.Sheets15,
                SheetCost15 = source.SheetCost15,
                SheetPrice15 = source.SheetPrice15,
                isaccumulativecharge = source.isaccumulativecharge,
                IsRoundUp = source.IsRoundUp,
                TimePerHour = source.TimePerHour,
                ZoneName = source.ZoneName,
                VariableString = GetVariableString(source)

            };
        }
        private static string GetVariableString(MPC.Models.DomainModels.MachineClickChargeZone source)
        {
            string sv = "{clickchargezone, ID=&quot;" + source.Id + "&quot;,caption=&quot;" + source.ZoneName + "&quot;}";
            return sv;
        }
    }
}